### ISSUE TITLE
Known problematic extensions

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#100]
This thread is for <ins>known problematic extensions</ins> which need special configuration or are disabled because e.g. private browsing incompatibility or other unknown reasons.

Please not open another thread and keep this one clean to get an quick overview which addons needs to be fixed (since this isn't an user.js problem).

I will update and check the extensions you might report over here and possible add workarounds or contact the developers. 

**Disabled/disappear (e.g. from toolbar):**
- [IP Address and Domain Information](https://addons.mozilla.org/en-US/firefox/addon/ip-address-and-domain-info/?src=search) 2.0.4 (disappears from toolbar)
- [ZenMate](https://addons.mozilla.org/en-US/firefox/addon/zenmate-security-privacy-vpn/?src=search) 5.1.1.1 as reported over #53 (because broken crypto you get insecure connection dialog, add api.zenmate.biz + sever address to exclusion)
- [Random Agent Spoofer](https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/) (see [#287](https://github.com/dillbyrne/random-agent-spoofer/issues/287))
- [Shodan Firefox Add-on](https://addons.mozilla.org/en-US/firefox/addon/shodan-firefox-addon/?src=api) 0.1.1-signed (see #12)
- [A9 ToolBar](http://toolbar.a9.com/)
- .....

**Needs manual configuration:**
- [Session Manager](https://addons.mozilla.org/en-US/firefox/addon/session-manager/?src=search) 0.8.1.8 (ensure you enabled cache + backup every xyz time [or manually])
- .....

**Comment by Atavic** [comment]
Shodan is calling your browser after a few minutes everytime you use their addon.

**Comment by pyllyukko** [comment]
I guess all this is going to change after Firefox switches to [WebExtensions](https://wiki.mozilla.org/WebExtensions).

**Comment by Atavic** [comment]
Electrolysis compatibility list: https://www.arewee10syet.com/
https://github.com/ghacksuserjs/ghacks-user.js/issues/12#issuecomment-282507380

**Comment by pyllyukko** [comment]
#245

**Comment by Atavic** [comment]
Some addons do not integrate well, as [these ones](https://github.com/gorhill/uBlock/issues/1992), because of uBo internals: https://github.com/gorhill/uBlock/issues/1170#issuecomment-168989068

**Comment by pyllyukko** [comment]
I'll close this now. If needed, we can open up a new issue for [WebExtensions](https://wiki.mozilla.org/WebExtensions).

**Comment by Atavic** [comment]
New one: https://github.com/pyllyukko/user.js/issues/348

**Comment by TerkiKerel** [comment]
I tested it: CanvasBlocker extension "fake read out api" (block mode) does not work with "privacy.resistFingerprinting". 

The privacy.resistFingerprinting=true overrides canvas fingerprint.
