### ISSUE TITLE
Questions and notices on first run

### ISSUE THREAD

**Issue by szepeviktor** [pyllyukko/user.js#102]
I use Firefox without installation: [extract, use, delete](https://github.com/szepeviktor/windows-workstation/blob/master/ff-dev/START-ffdev.cmd#L33-L36) so I need to suppress initial questions and notices. Here they are:

``` js
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.toolbarbuttons.introduced.pocket-button", false);
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyBypassNotification", true);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.displayedE10SPrompt.1", 1);
user_pref("browser.displayedE10SNotice", 4);
user_pref("browser.urlbar.userMadeSearchSuggestionsChoice", true);
```

Please consider including them in the README.

**Comment by pyllyukko** [comment]
> Please consider including them in the README.

I will. At least the default browser question has been bugging me also. In the README? Don't you mean in the settings file itself?

**Comment by szepeviktor** [comment]
> Don't you mean in the settings file itself?

I think you your project is for installed browsers.
My first step in cleaning out Firefox's inside was to not install it.

**Comment by pyllyukko** [comment]
> I think your project is for installed browsers.

But many times I need to create fresh profiles with the hardening and then the dialogs are back.

> My first step in cleaning out Firefox's inside was to not install it, sort of disposable browser :smile:

I see.

**Comment by szepeviktor** [comment]
> My first step in cleaning out Firefox's inside was to not install it

BTW I run Firefox (binary+profile) on a ramdisk.

**Comment by CHEF-KOCH** [comment]
Another way would be to ONCE create a profile (secure one) and make your changes, then backup it by compress it to rar/zip/whatever then Install another firefox/fresh ... unzip the secure profile use the profile manager to navigate to the extracted profile and start with it.

**Comment by szepeviktor** [comment]
I set up every part of the profile on setup.exe extraction: settings, extensions, certificates, bookmarks.

**Comment by szepeviktor** [comment]
> At least the default browser question has been bugging me also.

Isn't it already included?
https://github.com/pyllyukko/user.js/blob/master/user.js#L512-L513

**Comment by CHEF-KOCH** [comment]
This won't work on OS level. This is only Firefox internal check but the OS related 'default Browser' can't be changed by abou:config. So you must minimum start FF once so that the OS recognize it or you need to install FF and within the OS given option you need to navigate to the executable.

**Comment by szepeviktor** [comment]
Thank you for the explanation.
As I've mentioned I use an extract-and-run Firefox.

**Comment by Atavic** [comment]
You can try to [Restore Firefox Profile](https://addons.mozilla.org/EN-uS/firefox/addon/febe/)

**Comment by szepeviktor** [comment]
Actually I start with fresh Firefox every day, so I don't have to carry anything but:

- Firefox setup
- user.js
- cert db with my CA
- and a 5kB batch  file
