### ISSUE TITLE
user.js for Chromium

### ISSUE THREAD

**Issue by szepeviktor** [pyllyukko/user.js#115]
Is there a plan to add a Prefernces file for Chromium?
https://www.chromium.org/administrators/configuring-other-preferences

**Comment by CHEF-KOCH** [comment]
This would require another configuration file which is different from the existent one.

**Comment by szepeviktor** [comment]
You're right.

**Comment by CHEF-KOCH** [comment]
No support for me on this but if someone other want ... :8ball:

**Comment by pyllyukko** [comment]
> Is there a plan to add a Prefernces file for Chromium?

It's already a handful trying to keep up with just one browser's ever growing set of features and changes on this project, so no.

But how about switching to Firefox instead? ;)

**Comment by szepeviktor** [comment]
I am Firefox + [custom user.js](https://github.com/szepeviktor/windows-workstation/blob/master/ff-dev/user.js) user.
For detecting usability issues I run a portable Chromium and a portable Google Chrome also.

**Comment by pyllyukko** [comment]
> I am Firefox + custom user.js user.

Ah, that's right. Didn't notice your handle at first, before commenting on the issue :)

**Comment by CHEF-KOCH** [comment]
> But how about switching to Firefox instead? ;)

:+1: :laughing: ....

**Comment by CHEF-KOCH** [comment]
[Kill-ID](http://www.almisoft.de/?cont=kchrome) is the equivalent of user.js, it's a tool since Chrome doesn't allow modification on first start or while it's running. I think it's the best solution you can get.

**Comment by szepeviktor** [comment]
Thank you.
I keep Chrome and Chromium closed, almost always.
