### ISSUE TITLE
Convert to GitHub Pages?

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#122]
Because, .... [why not](https://pages.github.com/)?

**Comment by CHEF-KOCH** [comment]
This of course need a little bit work:
* Which design? I prefer a clean and not to dark one
* Re-write some things to make it compatible ... just markdown thngs ... d'oh!
* Enjoy the new page :+1:

**Comment by pyllyukko** [comment]
I'll consider this :)

Is there something we're missing currently, or something we can't provide through the project page? What would be the benefits, besides eye-candy (nicer pages that is)?

**Comment by CHEF-KOCH** [comment]
Sorry you got me with the benefits question, I don't know some except it looks easier and I could easier link into the page because shorter url.

* What I see you can add Google Analytics ID
* Maybe I can add this better into our addon in the future?

But besides this I don't know any benefit sr. Well, I quickly did my test and it already looks 'good' matter of taste of course. Please look here https://chef-koch.github.io/user.js/

I think the skin looks nice, fresh and clean. It also looks good on mobile devices. I used the 'Leap Day' skin. 

What do you think? :+1: or :-1:  ?

**Comment by pyllyukko** [comment]
Yeah it looks nice, but I guess that's all there is and we manage quite nicely with just the project page for now. Maybe in the future we need to revisit this, when there are clear benefits on having a separate page. So let's keep this in mind still.

Oh, and...

> add Google Analytics ID

Never!! :D

**Comment by CHEF-KOCH** [comment]
Speaking about the 'evil' Google and such do you have an payPal ID or some other address to send donations? Maybe this can be added into your Readme.

**Comment by pyllyukko** [comment]
> Speaking about the 'evil' Google and such do you have an PayPal ID or some other address to send donations? Maybe this can be added into your Readme.

I think Bitcoin would be the only viable option, but I'm fine... there's no need to add any donation options.

> .... a cup of :coffee: is waiting for you my friend ... :wink:

Thanks anyway :) I appreciate the thought!
