### ISSUE TITLE
Add TOC, or move README sections to Wiki

### ISSUE THREAD

**Issue by onebree** [pyllyukko/user.js#126]
Just a small suggestion. I see that the README is quite long, with many external links throughout. Personally, all the information would be easier to consume if the single file was divided into several wiki articles here.

I am interested in hearing what others have to say. I mean, even if the wiki option was turned down, I think a TOC in the README would be the best alternative.

**Comment by uberspot** [comment]
I'd personally prefer a TOC in the README. You don't have to open a browser to read the wiki remotely. Assuming you have the repo cloned locally (which makes sense).
Also https://github.com/ekalinin/github-markdown-toc <- this is automatic.

**Comment by onebree** [comment]
@uberspot I think that TOC generator is a great idea. If anything, the README needs to be polished up for correct heading structures.

**Comment by CHEF-KOCH** [comment]
I'm unsure about this, I guess some people will never ever read a readme and some hardly 'need' it. So, generally it should be available, especially if we maybe gonna to re-do the page via [sh-page](https://github.com/pyllyukko/user.js/issues/122). 

But I will keep an eye on the Wiki and will see if I can update it.

**Comment by onebree** [comment]
@CHEF-KOCH  I just changed the issue title. I just want there to be a way to navigate the README better, since you have to read the WHOLE document to see what's inside. Whereas wiki posts or a table of contents lets you skip around.

**Comment by nodiscc** [comment]
I use https://github.com/thlorenz/doctoc when I need to create a large TOC

**Comment by pyllyukko** [comment]
I guess the README is a bit lengthy indeed and TOC would be handy.

**Comment by pyllyukko** [comment]
What do you think about @nodiscc's [suggestion](https://github.com/nodiscc/user.js/blob/toc/README.md)?

**Comment by pyllyukko** [comment]
#225
