### ISSUE TITLE
sync via services.sync.prefs.sync booleans

### ISSUE THREAD

**Issue by jawz101** [pyllyukko/user.js#127]
I don't know if this is well known but supposedly you're able to sync any random about:config entry by creating a boolean with the convention:
services.sync.prefs.sync.[config name] = true
ex:
services.sync.prefs.sync.beacon.enabled = true

personally, I do this with all of my custom prefs vs. using the userprefs.js... or at least complementing it.

I'm pretty sure this document still applies.  I also add the little sync rotating icon to my toolbar to confirm that as I make changes it rotates, acknowledging it sync those settings I change.
https://developer.mozilla.org/en-US/docs/Archive/Mozilla/Firefox_Sync/Syncing_custom_preferences

**Comment by CHEF-KOCH** [comment]
Nice find, didn't know that this is still possible. 

Maybe I will add in Wiki, I guess not everyone uses Sync (even you can set your own server and sync with it instead of Mozillas) but's definitely worth to mention.

**Comment by jawz101** [comment]
it does still work :)
https://gist.github.com/jawz101/c8cb310f0fec8492f054

**Comment by pyllyukko** [comment]
Nice tip! As I don't use sync myself, I had no idea that this was possible too.
