### ISSUE TITLE
Update for Firefox [currently: 47.0.0]

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#13]
Hey, thanks, the project seems promising, it's exactly what I'm looking for, but sad it's pretty outdated atm. Some settings are deprecated (means the value is already set to the ones mentioned in the user.js) and some not exists anymore due security reasons (e.g. most of the cipher stuff).

Here is my list what I've found, I checked each entry against the current Firefox release.

Not existing anymore:

``` bash
browser.frames.enabled 
browser.polaris.enabled
javascript.options.methodjit.chrome
javascript.options.methodjit.content
browser.safebrowsing.remoteLookups
datareporting.healthreport.uploadEnabled
browser.newtabpage.enhanced
network.negotiate-auth.allow-insecure-ntlm-v1
browser.sessionstore.postdata
browser.sessionstore.enabled
browser.history_expire_days
browser.history_expire_sites
browser.history_expire_visits
browser.download.manager.retention
plugins.hide_infobar_for_outdated_plugin
security.warn_viewing_mixed
security.warn_entering_weak
network.http.spdy.enabled.v3
security.enable_tls_session_tickets
security.enable_ssl3
security.ssl3.rsa_null_sha
security.ssl3.rsa_null_md5
security.ssl3.ecdhe_rsa_null_sha
security.ssl3.ecdhe_ecdsa_null_sha
security.ssl3.ecdh_rsa_null_sha
security.ssl3.ecdh_ecdsa_null_sha
security.ssl3.rsa_seed_sha
security.ssl3.rsa_rc4_40_md5
security.ssl3.rsa_rc2_40_md5
security.ssl3.rsa_1024_rc4_56_sha
security.ssl3.rsa_camellia_128_sha
security.ssl3.ecdh_rsa_rc4_128_sha
security.ssl3.ecdh_rsa_aes_128_sha
security.ssl3.ecdh_ecdsa_rc4_128_sha
security.ssl3.ecdh_ecdsa_aes_128_sha
security.ssl3.dhe_rsa_camellia_128_sh
security.ssl3.dhe_dss_des_ede3_sha
security.ssl3.dhe_rsa_des_ede3_sha
security.ssl3.ecdh_ecdsa_des_ede3_sha
security.ssl3.ecdh_rsa_des_ede3_sha
security.ssl3.ecdhe_ecdsa_des_ede3_sha
security.ssl3.ecdhe_rsa_des_ede3_sha
security.ssl3.rsa_fips_des_ede3_sha
security.ssl3.ecdh_rsa_des_ede3_sha
security.ssl3.ecdh_rsa_aes_256_sha
security.ssl3.ecdh_ecdsa_des_ede3_sha
security.ssl3.ecdh_ecdsa_aes_256_sha
security.ssl3.rsa_camellia_256_sha
security.ssl3.dhe_rsa_camellia_256_sha
security.ssl3.dhe_dss_camellia_256_sha
security.ssl3.dhe_dss_aes_256_sha
security.ssl3.dhe_dss_aes_128_sha
security.ssl3.dhe_dss_aes_256_sha
security.ssl3.dhe_dss_camellia_128_sha
security.ssl3.dhe_dss_camellia_256_sha
security.ssl3.dhe_dss_des_ede3_sha
```

Deprecated (already set default to true/false):

``` bash
media.webspeech.recognition.enable already default false
browser.send_pings already false
dom.indexedDB.enabled already true
security.mixed_content.block_active_content already true
dom.vr.enabled already false
network.jar.open-unsafe-types already false
plugins.click_to_play true 
extensions.update.enabled already true
loop.enabled already false
security.csp.enable already true
privacy.clearOnShutdown.cache default true 
privacy.clearOnShutdown.cookies
privacy.clearOnShutdown.downloads
privacy.clearOnShutdown.formdata
privacy.clearOnShutdown.history
privacy.clearOnShutdown.sessions
security.ssl.warn_missing_rfc5746 already 1
security.ask_for_password already 0
network.stricttransportsecurity.preloadlist already true 
network.http.spdy.enabled already true
network.http.spdy.enabled.v3-1 already true
security.ssl.enable_ocsp_stapling already true
security.tls.version.min already 1
security.tls.version.max already 3
security.ssl3.ecdhe_ecdsa_aes_128_gcm_sha256 is already true
security.ssl3.ecdhe_rsa_aes_128_gcm_sha256 is already true 
security.ssl3.dhe_rsa_aes_256_sha is already true
security.ssl3.rsa_aes_256_sha is already true
browser.urlbar.filter.javascript is already true
```

And some problems I've found:

``` bash
// Needs to be changed to 
network.http.referer.spoofSource   .. false (default) and true 
network.http.sendRefererHeader should be 0 
network.cookie.cookieBehavior should be 2

// Only if ghostery installed - I would prefer Disconnect over Ghostery since it's full FOSS and there is no send home function
extensions.ghostery.privateBrowsing

// Wrong
browser.sessionstore.privacy_level default 0 
and browser.sessionstore.privacy_level_deferred 1
 security.OCSP.enabled is 1 (default) not true
```

If the HTTPS-everywhere addon is installed we do not need the <code>security.mixed_content.block_display_content</code> stuff, or we not need the addon, since the addon does exactly the same, except some exclusions and some redirects (including the send home feature observatory). HTTPS-everywhere is much overrated imho for example NoScript also have now 2 years (or more) the HTTPS option implemented to force HTTPS. So in my point of view we don't need both addons or as said if it's already forced in the user.js file we can remove (or in NoScript disable it).

**Comment by pyllyukko** [comment]
> Hey, thanks, the project seems promising, it's exactly what I'm looking for, but sad it's pretty outdated atm. Some settings are deprecated (means the value is already set to the ones mentioned in the user.js) and some not exists anymore due security reasons (e.g. most of the cipher stuff).

Thanks for the input.

> Deprecated (already set default to true/false):
> 
> media.webspeech.recognition.enable already default false
> browser.send_pings already false
> dom.indexedDB.enabled already true
> security.mixed_content.block_active_content already true
> dom.vr.enabled already false
> network.jar.open-unsafe-types already false
> plugins.click_to_play true 
> extensions.update.enabled already true
> loop.enabled already false
> security.csp.enable already true
> privacy.clearOnShutdown.cache default true 
> privacy.clearOnShutdown.cookies
> privacy.clearOnShutdown.downloads
> privacy.clearOnShutdown.formdata
> privacy.clearOnShutdown.history
> privacy.clearOnShutdown.sessions
> security.ssl.warn_missing_rfc5746 already 1
> security.ask_for_password already 0
> network.stricttransportsecurity.preloadlist already true 
> network.http.spdy.enabled already true
> network.http.spdy.enabled.v3-1 already true
> security.ssl.enable_ocsp_stapling already true
> security.tls.version.min already 1
> security.tls.version.max already 3
> security.ssl3.ecdhe_ecdsa_aes_128_gcm_sha256 is already true
> security.ssl3.ecdhe_rsa_aes_128_gcm_sha256 is already true 
> security.ssl3.dhe_rsa_aes_256_sha is already true
> security.ssl3.rsa_aes_256_sha is already true
> browser.urlbar.filter.javascript is already true

This is intended. I want to explicitly define even the settings, that are "secure" by default. This is also documented in the fine print of [ What does it do?](https://github.com/pyllyukko/user.js/blob/master/README.md#user-content-what-does-it-do). Just so that they are also safe after I might tweak them and restart Firefox.

> And some problems I've found:
> 
> // Needs to be changed to 
> network.http.referer.spoofSource   .. false (default) and true 
> network.http.sendRefererHeader should be 0 
> network.cookie.cookieBehavior should be 2

These should be in order. See the discussion in #2.

I need to get back to the rest of this issue later. I appreciate the input and will review these.

**Comment by pyllyukko** [comment]
> Not existing anymore:
> 
> browser.frames.enabled

-> 18b3f5a33f6833eb0e4709f72a57bdd1c162e54a

**Comment by pyllyukko** [comment]
Another thing is the obsolete settings. We can't remove stuff "blindly". Of course this needs to be somewhat backwards compatible and this should also be usable with Firefox [ESR](https://www.mozilla.org/en-US/firefox/organizations/faq/).

Unfortunately, it is not very clear when Mozilla removes or renames settings/functionality/feature. Usually the documentations drag behind and still have obsolete settings described in them.

Pretty much the only situation, when I would feel confident to start removing some of these settings is, when there is a closed ticket in Mozilla's bug tracker stating that something has been completely removed/obsoleted and sufficient amount of time has passed from that ticket being closed.

Even though it's not desired to have unnecessary or obsolete stuff in the ```user.js``` file, the only possible downside I see is the cosmetic aspect of having unnecessary clutter.

**Comment by pyllyukko** [comment]
> browser.safebrowsing.remoteLookups

-> 3518ff05caa65c972e40a0e61ee7dc246482672b

**Comment by CHEF-KOCH** [comment]
Sorry for the late news, we are now hit the 39.x stable branch. 

* [Release Notes](https://www.mozilla.org/en-US/firefox/39.0/releasenotes/)
* [Security Advisories for FF](https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox/#firefox39)

For lazy people the most _important_ stuff/changes are:
* Malware detection service for downloads now covers common Mac file types (this is for .dmg, .pkg, .osx und .app. files and will be checked [if enabled] via [safebrowsing](https://support.mozilla.org/kb/how-does-phishing-and-malware-protection-work))
* NSS accepts export-length DHE keys with regular DHE cipher suites
* NSS incorrectly permits skipping of ServerKeyExchange 
* Removed support for insecure SSLv3 for network communications <-- this means we normally not need anymore to touch the ciphers since the most insecure are removed now

I'm still working on a final solution that should work with all sites, the sad thing that there is no addon yet available to add exclusions, even the _security_ promising addons not allowing that and there is also not any database of _secure_ sites that still use the old RC4 (e.g. addons page and schneier.com). So I finally think that the only solution could be to document this or as written in another thread, to simply add a addon which offers a better gui for this. 

> Another thing is the obsolete settings. We can't remove stuff "blindly". Of course this needs to be somewhat backwards compatible and this should also be usable with Firefox ESR.

Sure we can and we must, because it's also removed from ESR versions (see also latest TOR Browser Bundle release) and of course more settings confuse the people instead that it helps. Mozilla did that now and I ask myself why you against such procedure.

**Comment by CHEF-KOCH** [comment]
**FF 40 changes**:
* [New download filter](https://blog.mozilla.org/security/2015/08/11/expanded-malware-protection-in-firefox/) which protects more against malware 
* Some [hello chat](https://support.mozilla.org/en-US/kb/add-context-firefox-hello-conversations) client changes 
* [Closed security holes](https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox/#firefox40)
* [New performance tools](https://hacks.mozilla.org/2015/06/new-performance-tools-in-firefox-developer-edition-40/)
* All other [release notes](https://www.mozilla.org/en-US/firefox/40.0/releasenotes/)

**Comment by Hunter-Github** [comment]
Please also note that safebrowsing (now?) sends cookies to Google. Which means there's no way this feature can be enabled for any privacy-conscious user. https://support.mozilla.org/en-US/kb/how-does-phishing-and-malware-protection-work#w_how-do-i-use-the-phishing-and-malware-protection-features :

> In both cases, existing cookies you have from google.com, our list provider, may also be sent.

**Comment by CHEF-KOCH** [comment]
Hi, I already talked about that, in fact it doesn't sends anything important to Google (also remember not all that comes from Google, MS, Apple is automatically bad, server can be compromised even that this big ones never noticed that!). Mozilla have an partnership with Google, Tor and others so generally they can be trusted, since we are talking about metadata that can be easily revealed, [some guys already inspected this](https://news.ycombinator.com/item?id=9779990). The only one that are maybe problematically seems that the MD5-hashes from Google (that's what will be downloaded) are compared locally on your machine. See [also #14](https://github.com/amq/firefox-debloat/issues/14) + [#3](https://github.com/amq/firefox-debloat/issues/3).

Generally I'm also against this since everyone use an AV or cares about bandwidth consumption (e.g. on cellular data activity's) I recommend myself to disable it, but not because possible data leakage.

Overall I think it should be optional, but there is also an GUI option for this since FF32, so everyone can easy disable/enable it as per needs.

**Comment by pyllyukko** [comment]
> Overall I think it should be optional, but there is also an GUI option for this since FF32, so everyone can easy disable/enable it as per needs.

Indeed. I think we could comment out the safe browsing settings, so people can choose whether to use it or not and it's easily configured through the GUI.

I would still leave ```browser.safebrowsing.downloads.enabled``` as it leaks too much info: https://github.com/pyllyukko/user.js/commit/6d72adb6cc4c0e13cee3d3336201d612c9431065#commitcomment-12001719

**Comment by fmarier** [comment]
A late reply to @Hunter-Github's [comment](https://github.com/pyllyukko/user.js/issues/13#issuecomment-130960084).

> Please also note that safebrowsing (now?) sends cookies to Google.

While this is true, please note that the Safe Browsing cookie is now [in a separate cookie jar](https://bugzilla.mozilla.org/show_bug.cgi?id=897516) so it's not the same cookie as the one that Google uses if you log into GMail for example.

If you use visit Google sites you'll have two cookies:

- the normal Google cookies that follows you around as you visit their sites
- the Safe Browsing cookie that is only used to download Safe Browsing lists

**Comment by CHEF-KOCH** [comment]
Firefox 44.0 (26. January 2016)

**Other changes**
* RC4 is not disabled in release versions of Firefox and no longer accepted. [[bug 1201025](https://bugzilla.mozilla.org/show_bug.cgi?id=1201025)]
* Support for Brotli compression algorithm has been added. [[bug 366559](https://bugzilla.mozilla.org/show_bug.cgi?id=366559) and [bug 1211916](https://bugzilla.mozilla.org/show_bug.cgi?id=1211916)]
* Warning page when RC4 is the only supported cipher.
* Firefox will no longer trust the Equifax Secure Certificate Authority 1024-bit root certificate or the UTN - DATACorp SGC
* To support unicode-range descriptor for webfonts, font matching under Linux now uses the same font matching code as other platforms
* Firefox uses a SHA-256 signing certificate for Windows builds as recommended by Microsoft.

**Developer Changes**
* Add-on signing is enforced in Firefox 44 Stable. This means that it is no longer possible to override the security feature. The consequence is that you cannot load unsigned add-ons in Firefox Stable anymore.
* Allow about:pages to load remote content. [[bug 1204983](https://bugzilla.mozilla.org/show_bug.cgi?id=1204983)]
* Size restrictions for extension icons to prevent too large toolbar icons from deforming the toolbar. [[bug 1208715](https://bugzilla.mozilla.org/show_bug.cgi?id=1208715)]
* MediaStream.stop() has been deprecated, MediaStream.addTrack()/removeTrack() have been added. [[bug 1103188](http://mediastream.addtrack()/removeTrack())]
* Visual tools for Animation and Layout & Styles have been improved.
* WebRTC interfaces have been unprefixed: in particular mozRTCPeerConnection is now RTCPeerConnection, mozRTCIceCandidate is now RTCIceCandidate, and mozRTCSessionDescription is now RTCSessionDescription.

**Firefox for Android**
* Support added for urls with the mms protocol ([multimedia messaging service](https://en.wikipedia.org/wiki/Multimedia_Messaging_Service)).
* Long-press on search label in "quick search bar" opens customize search providers.
* Firefox users are prompted when "intent URLs" are about to be opened in private browsing tabs.
* New web-based Firefox accounts page.
* Support for cloud printing using Android print service.
* Users may set their homepage when starting Firefox.

**about:config changes**
* Mozilla will set media.mediasource.webm.enabled in Firefox to true.

**Comment by pyllyukko** [comment]
Thanks for the update!

> Add-on signing is enforced in Firefox 44 Stable. This means that it is no longer possible to override the security feature. The consequence is that you cannot load unsigned add-ons in Firefox Stable anymore.

Relates to #49.

> Allow about:pages to load remote content. [bug 1204983]

This sounds like something that could be abused for attacks.

**Comment by CHEF-KOCH** [comment]
**Firefox 44.0.2** 

Download | 44.0.2 - en-US | (32-bit) - https://download-installer.cdn.mozilla.net/pub/firefox/releases/44.0.2/win32/en-US/Firefox%20Setup%2044.0.2.exe
Download | 44.0.2 - en-US | (64-bit) - https://download-installer.cdn.mozilla.net/pub/firefox/releases/44.0.2/win64/en-US/Firefox%20Setup%2044.0.2.exe

Download | 44.0.2 - All Languages | (32-bit) - https://download-installer.cdn.mozilla.net/pub/firefox/releases/44.0.2/win32/
Download | 44.0.2 - All Languages | (64-bit) - https://download-installer.cdn.mozilla.net/pub/firefox/releases/44.0.2/win64/ 


No interesting changes we must look in.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
45.0 is when xpinstall.signatures.required;false stops working according to the wiki and the setting still works for me on 44.0.2, additionally at that point people will have to launch unsigned extensions in "temporary" mode. (I don't know anything about the latter.)

**Comment by fmarier** [comment]
> 45.0 is when xpinstall.signatures.required;false stops working according to the wiki

What wiki page did you see this on?

It has been postponed to 46:

- https://wiki.mozilla.org/Add-ons/Extension_Signing
- https://blog.mozilla.org/addons/2016/01/22/add-on-signing-update/

**Comment by CHEF-KOCH** [comment]
Firefox [45](http://www.ghacks.net/2016/03/08/firefox-45-find-out-what-is-new/)

Except the hello stuff I not found something we need to worry/look at. But we already have this disabled.

**Comment by CHEF-KOCH** [comment]
Firefox [45.0.2](https://www.mozilla.org/en-US/firefox/45.0.2/releasenotes/) Final is out.

No about:config related changes.

**Comment by CHEF-KOCH** [comment]
Firefox [46.0.0](https://www.mozilla.org/en-US/firefox/46.0.0/releasenotes/) Final is out.

No about:config related changes.

**Comment by licaon-kter** [comment]
This needs attention I guess: 

> **Include default domains for inline autocompletion**

> When you type in Firefox's address bar, suggestions are displayed as you type. Firefox uses previously visited domains for that, but since there are none when you start using the browser after initial installation, it uses a fallback now.
> 
> Basically, what it does is grab top sites using Alexa (or similar services), and provide those as an initial list for inline autocompletion.

[[info](https://gecko.readthedocs.org/en/latest/mobile/android/fennec/defaultdomains.html#domain-auto-completion)]

**Comment by CHEF-KOCH** [comment]
We already disabled autocompletation entirely. It's also opt-in feature, if you new install Firefox then you see a green button after you want to type something into the search. 

Anyway thanks for the heads-up on this.

**Comment by pyllyukko** [comment]
Thanks for the update!

> Support for the .onion extension has been added. It is turned off by default but can be enabled in Firefox by setting the preference network.dns.blockDotOnion to false.

Relates to #132.

> We already disabled autocompletation entirely.

Indeed. Should be taken care of.

**Comment by licaon-kter** [comment]
> Indeed. Should be taken care of.

I did not see any config mentioned there (so I can check user.js coverage), hence my post.
It's good if it's already covered.

**Comment by pyllyukko** [comment]
> I did not see any config mentioned there (so I can check user.js coverage), hence my post.
> It's good if it's already covered.

Should be covered with ```browser.urlbar.autoFill```, ```browser.urlbar.maxRichResults``` & ```browser.urlbar.autocomplete.enabled```.

**Comment by CHEF-KOCH** [comment]
* https://ftp.mozilla.org/pub/firefox/releases/46.0.1/
* https://www.mozilla.org/en-US/firefox/46.0.1/releasenotes/ (not avbl. as time of writing)

No about:config related changes.

**Comment by CHEF-KOCH** [comment]
Firefox 47 is out. No interesting about:config changes because focus was on [WebExtensions](https://blog.mozilla.org/addons/2016/03/11/webextensions-in-firefox-47/). 

```bash
en-US
x86: https://ftp.mozilla.org/pub/firefox/releases/47.0/win32/en-US/

x64: https://ftp.mozilla.org/pub/firefox/releases/47.0/win64/en-US/

All languages:
https://ftp.mozilla.org/pub/firefox/releases/47.0/win32/
https://ftp.mozilla.org/pub/firefox/releases/47.0/win64/
```

With 48 there will be some changes for us.

**Comment by nodiscc** [comment]
I've re read this issue and believe it can be archived/closed. Tracking added/deprecated/changed preferences in latest and upcoming Firefox releases can be done by subscribing to RSS feeds (mainly on DXR) listed at **https://github.com/pyllyukko/user.js#mozilla-documentation**
