### ISSUE TITLE
Mozillas New Browser 'Servo' Infos + support?

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#131]
I didn't know that Mozilla is working on another Browser, so this was a little bit 'shocking' for me because in my point of few the energy had better been spent on fixing Mozilla's known problems with Firefox but okay - now we need to deal with this.

According to the page and some other statements it's unclear if this one will replace Firefox and it's also unclear how the development will go one.

So if anyone have 'real' information it would be good to show over here because if it would be clear that Firefox will maybe cut off support then we need to support this 'new' Browser.

What I 'think' is that maybe the Servo features will be adopted in Firefox which would be 'better' - but's speculation.  

<ins>Research</ins>:
- http://news.softpedia.com/news/mozilla-s-new-servo-browser-will-be-released-in-june-2016-501759.shtml
- https://www.youtube.com/embed/wN_ePJ7AY5U?feature=oembed
- http://venturebeat.com/2016/03/16/mozilla-will-release-the-first-tech-demo-of-servo-its-next-generation-browser-engine-in-june/
- https://groups.google.com/forum/#!topic/mozilla.dev.servo/dcrNW6389g4
- https://servo.org/

**Comment by fmarier** [comment]
> So if anyone have 'real' information it would be good to show over here because if it would be clear that Firefox will maybe cut off support then we need to support this 'new' Browser.

(Disclaimer: I'm a Mozilla security engineer.) I wouldn't worry too much about that in the foreseeable future. Mozilla is investing heavily into Firefox quality this year and Servo is still a research browser (part of the Research team at Mozilla) that can't yet render all of the things needed by the modern web.

**Comment by CHEF-KOCH** [comment]
New [Tofino UI](https://medium.com/project-tofino/browsers-innovators-dilemma-and-project-tofino-ef634c6164f0#.5zg6s6naf) - [statements](https://medium.com/@david_bryant/embed-everything-9aeff6911da0#.m50taagz5). [Api Wrapper for Gecko](https://github.com/mozilla/positron) + [Code](https://github.com/mozilla/tofino). 

There is also an [explanation](https://medium.com/project-tofino/designing-a-browser-that-isn-t-a-browser-685b63c4b6f1#.j5ukfeid3) of the upcoming changes.


Sorry Mozilla, if you do that, then I switch to Chromium you try to copy Chrome for several years, the Addon changes, the sandbox and many more

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH I hope Mozilla comes to its senses.  Otherwise, there are going to be some big forks of the current codebase.  Maybe Firefox without Mozilla will actually be a good thing, hard to know.

The big question is whether or not a sufficient number of people at Mozilla are able to see the problems that the rest of the tech world has no problem seeing.  And, if they are able to see it, will they do anything about it, or just keep quiet.

**Comment by CHEF-KOCH** [comment]
Sorry guys, after a long talk with an Mozilla supporter/Maintainer my decision is now clear I switch to Chromium (tested several months now and it works great) and compile the builds at my own which is a lot of easier because you can just compile with specific flags so that you not need any about:config mess. I believe in layer security and not addon security and Chrome is by default better in this, there is no doubt about that. 

My personal focus is just only to browser as much secure as possible and I not see that Mozilla will handle it in the near future same like as Google because it more or less requires an re-write from sketch otherwise you run into troubles like e10s (which was the reason why it was not now enabled in FF 46 because mostly crashes). Also most certificate changes are faster by Google, you report something and it get response, I tried several times with Mozilla, closed tickets or no response. It's not that I not gave not enough details, I always try to give as much as possible on information ...

This is again the end of an great product for me, I had (as mentioned) this story with Opera and I loved the mail integration (was good enough .. just add proper encryption it's all I ever wanted) until they decide to kill it and now we get exactly the same story again .. can't believe it's real ... I can't tell much about my and Mozilla's discussion because it includes coming features but it's not what I want. I want a clean browser which only opt-in (optional) stuff I want or an setup which allows me to 'tweak' a little bit to e.g. opt-in/opt-out features ... In 2016 this still seems impossible. Simply things and logical failures holding us back (e.g. I asked about chance to get about:config reset [without that you need create a new profile on a per-extension basis] and I'm to old to fight for this again and again any longer. 

I will for sure sometimes look here around and try to finish my addon so that someone can pick-up it and maintain it for 'coming' changes but I will not spent any longer that much time here. 

Greetings
CK :heart:

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH Thanks for your efforts.  Maybe you can send a more refined version of your above statement to some of the execs at Mozilla (if they listen... I don't know), and perhaps publish it in a blog or site that will receive more readership than a GitHub comment.

**Comment by CHEF-KOCH** [comment]
[Maybe we could together start an git-sh page](https://github.com/CHEF-KOCH/BetterFireFox) which would lists and add our wishes, I not found any good page for that. The Mozilla own bugtracker is especially for beginners hard to handle, there exist a lot of outdated/deprecated stuff and it's just counterproductive to give Mozilla 100 links instead of one which explains everything which the user maybe really want. There is not really an discussion ground, there exist several forums and such ... sure but it's not as easy as GitHub because you not see directly stuff which is already done or on our radar.

The thing is I not get any money from that and I ask myself why I should do all the work, to 'make Firefox great again'. 

I added all members which contribute here to this project, feel free to add your wishes ideas and whatever.

**Comment by pyllyukko** [comment]
Sorry to hear you're switching away from Firefox.

Thanks for all the contributions and active dialog in here! :heart:

I'm still sticking with Firefox and continue struggling with the moving target that it is :)

**Comment by licaon-kter** [comment]
Looks like they at least try to takle issues, will see how they fare along: 

> In Firefox 48 we pushed hard to make the WebRequest API a solid foundation for privacy and security
> add-ons such as Ghostery, RequestPolicy and NoScript. With the current implementation of the
> onErrorOccurred function, it is now possible for Ghostery to be written as a WebExtension.
> 
> The addition of reliable origin information was a major requirement for existing Firefox security
> add-ons performing cross-origin checks such as NoScript or uBlock Origin. This feature is unique to
> Firefox, and is one of our first expansions beyond parity with the Chrome APIs for WebExtensions.

[[Source](https://blog.mozilla.org/addons/2016/04/29/webextensions-in-firefox-48/)]

**Comment by CHEF-KOCH** [comment]
It's alive now:

https://blog.servo.org/2016/06/30/servo-nightlies/
https://youtu.be/jJXW072MatI
https://wiki.mozilla.org/Oxidation
based on Rust (worst programming language ever) -> http://www.rust-lang.org/

**Comment by nodiscc** [comment]
I think this issue can be archived/closed. It has no direct link with this project.
