### ISSUE TITLE
Googles 'untrusted/pending' CA list

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#133]
... is available [here](https://mozillacaprogram.secure.force.com/CA/PendingCACertificateReport). The list will be constantly updated. 

Source:
- http://www.theregister.co.uk/2016/03/23/google_now_publishing_a_list_of_cas_it_doesnt_trust/

**Comment by CHEF-KOCH** [comment]
No one find this interesting? :_slap:

**Comment by CHEF-KOCH** [comment]
ANyone know why <code>U.S. Federal Public Key Infrastructure (US FPKI)</code> is on the list? I downloaded the certificate from the ftp and I found this is for remotecomputers only. I not understand why I or anyone want to give them remove access especially because it's not needed for Browsing itself. it also shows email but I don't get it, because this server is not widely used.

**Comment by nodiscc** [comment]
What should we do about this? I think it's moderately relatd to user.js. Should this issue be closed?

**Comment by CHEF-KOCH** [comment]
I think it's interesting to keep an eye on it, in case we get some new stuff which may needs to be removed. Since I not have time to check each certificate I hope others may can help or find possible certificates which are in other context known to be 'untrusted'.

**Comment by Atavic** [comment]
That's Mozilla Trusted Third Party list (TTP) CA list, apparently.

**Comment by Atavic** [comment]
[There's even more:](https://github.com/pyllyukko/user.js/issues/73#issuecomment-248397337) Certificate Revocation Lists are downloaded in the background.

**Comment by nodiscc** [comment]
Yeah actually I think this can be closed. While it is an interesting topic it has no direct relation to `user.js`

> in case we get some new stuff which may needs to be removed

The [CA trimming guide](https://github.com/pyllyukko/user.js/blob/master/CAs.md) assumes the user removes _all_ CAs, and only manually allows a restricted CA set defined in the script. So really there is nothing more which may need to be removed.
