### ISSUE TITLE
Http images do not load

### ISSUE THREAD

**Issue by Riyyi** [pyllyukko/user.js#139]
Some images are not displayed at all, on the website itself, but do load once you call the url with the .jpg in it. I know this has something to do with the main site using https but the content on the page is linked with just http://.

Does anybody know what I need to change in the user.js to make this work? I'm at a loss.

Site example: https://tweakers.net/ / Ebay when you search for something

**Comment by fmarier** [comment]
Try setting `security.mixed_content.block_display_content` to `false`.

**Comment by Gitoffthelawn** [comment]
I found so many problems with the eBay site that I don't even bother with them anymore.

**Comment by Riyyi** [comment]
> security.mixed_content.block_display_content
That did the trick, thanks!
