### ISSUE TITLE
add notice in readme about cas.sh requiring ca-certificates

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [pyllyukko/user.js#140]
i tried to run `cas.sh` on my windows install (with cygwin) and tried to use the basic list but this happened:

```
importing CAs:
error: file `/usr/share/ca-certificates/mozilla/AddTrust_External_Root.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/Baltimore_CyberTrust_Root.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/COMODO_Certification_Authority.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/Deutsche_Telekom_Root_CA_2.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/DigiCert_High_Assurance_EV_Root_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/DigiCert_Global_Root_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/Entrust.net_Secure_Server_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/Entrust.net_Premium_2048_Secure_Server_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/Entrust_Root_Certification_Authority.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/Equifax_Secure_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/GTE_CyberTrust_Global_Root.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/GeoTrust_Global_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/GeoTrust_Primary_Certification_Authority.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/GlobalSign_Root_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/Go_Daddy_Class_2_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/Go_Daddy_Root_Certificate_Authority_-_G2.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/Starfield_Class_2_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/StartCom_Certification_Authority.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/UTN_USERFirst_Hardware_Root_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/ValiCert_Class_2_VA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/Verisign_Class_3_Public_Primary_Certification_Authority_-_G3.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/VeriSign_Class_3_Public_Primary_Certification_Authority_-_G5.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/thawte_Primary_Root_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/thawte_Primary_Root_CA_-_G3.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/SecureTrust_CA.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/QuoVadis_Root_CA_2.crt' not found!
error: file `/usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt' not found!
```

so it assumes that your OS has the `ca-certificates` package installed and also that its in `/usr/share/ca-certificates/`, and i guess using linux is implied.

i think these should be noted in the readme

**Comment by berrythesoftwarecodeprogrammar** [comment]
im currently trying to get it to work though. i installed `ca-certificates` in cygwin but it didnt seem to install correctly since it didnt make any directories

**Comment by berrythesoftwarecodeprogrammar** [comment]
hmm looks like i get the same problem on my linux server which has `ca-certificates` installed.. there is no directory like that

**Comment by berrythesoftwarecodeprogrammar** [comment]
ok it seems like in your distro ca-certs are stored in individual files in subdirectories of `/usr/share/ca-certificates/`? but in cygwin and centOS it seems they are all packaged into a single file? `/etc/ssl/certs/ca-bundle.crt`
im not sure

**Comment by pyllyukko** [comment]
Indeed the cas.sh requires ca-certificates package. We trust that the distro and package management have authentic CAs in place. That way we don't need to have any separate verification for the CAS and don't need to download or bundle them.

I have only used the cas.sh with Slackware & Debian, which both have individual certificate files in that directory. Also the ```update-ca-certificates``` and ```c_rehash``` tools work in such a way, that the certs are separate. Also that is how parts of OpenSSL verify the certs, it calculates the ```issuer_hash``` and looks for that particular cert file from e.g. ```OPENSSLDIR/certs/issuer_hash.#```.

It seems that CentOS (/RH) indeed has only the CA bundle file with all the certs in there. Which differs from these other distros.

I'll need to look into ways to make this work in CentOS/RH, but I don't have any quick/easy fixes for that currently.

Thanks for reporting this.

**Comment by ileyd** [comment]
See: https://stackoverflow.com/questions/23644473/how-can-i-split-a-ca-certificate-bundle-into-separate-files

The appropriate file to use for EL-based and Fedora systems would be `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`

**Comment by pyllyukko** [comment]
Yes, it would need some additional processing. I think it might be better to split them and then ```c_rehash``` them.
