### ISSUE TITLE
Is firefox on linux supported?

### ISSUE THREAD

**Issue by bobafetthotmail** [pyllyukko/user.js#141]
I mean Firefox for Linux, not Icewasel (Debian opensource-only Firefox) nor whatever modification.

I think it should be compatible, as this is a firefox config file.

Can I try to use this or will it blow up my PC?  :)

I know how to make backups of firefox profile so I can restore everything in case it does screw up my Firefox, I'm just asking here to avoid wasting time testing it (and as future reference for others).

**Comment by licaon-kter** [comment]
Yes

/close as invalid

**Comment by pyllyukko** [comment]
Yes it is.
