### ISSUE TITLE
FF46+ pocket change

### ISSUE THREAD

**Issue by Roman-Nopantski** [pyllyukko/user.js#143]
@pyllyukko 
FF45 and under uses: user_pref("browser.pocket.enabled", false);
FF46+ now uses: user_pref("extensions.pocket.enabled", false);
So you may want to add the new pref at around line 304 of the current user.js

**Comment by CHEF-KOCH** [comment]
Pocket will be addon in the future. We not need to touch this until it get's integrated. FF 50.

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH Pocket is currently included with the releases.  Are you saying it will be removed and made as an extension again at FF 50?

**Comment by CHEF-KOCH** [comment]
Yeah. I hear every stuff which is included such as Pocket/Hello gets separated as opt-in via addon/extension. It's planed for 50, maybe because current issue in 51.

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH LOL.  That's funny because, as you know, Pocket was just an extension until recently.  Sometimes I wonder if Mozilla has a real plan, or if it's just determined by "who's in charge today".

Don't get me wrong, I think it's great if they acknowledge their mistakes and reverse their decisions... I've just rarely seen a company make so many bad decisions.

**Comment by Roman-Nopantski** [comment]
@CHEF-KOCH "We not need to touch this until it get's integrated. FF 50". So you're saying, based on speculation, that you are not interested in keeping the user.js accurate and backward compatible (which is one of pyllyukko's objectives)? Got it.

**Comment by pyllyukko** [comment]
> FF45 and under uses: user_pref("browser.pocket.enabled", false);
> FF46+ now uses: user_pref("extensions.pocket.enabled", false);
> So you may want to add the new pref at around line 304 of the current user.js

Thanks!

**Comment by CHEF-KOCH** [comment]
@Roman-Nopantski it's not speculation.
