### ISSUE TITLE
README information on ciphers is out of date

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#158]
https://github.com/pyllyukko/user.js/#ciphers

> Here's a list of the ciphers with default config and Firefox 27.0.1:

**Comment by CHEF-KOCH** [comment]
Nice but we already have #148. If you think I'm wrong on removing it, we may could find an compromises. To still mention it even it's 1 year outdated is a bit beyond me even on a pc without access someone could use an portable version.

Maybe we could find a way to deal with both. Personally I would only mention the fallback ciphers and then add´maybe an note to (if on high security pages like github) remove them if you know what you're doing.

**Comment by nodiscc** [comment]
Yes #148 looks good.

**Comment by pyllyukko** [comment]
Yes, it is out of date. No, we are not going to completely remove it.
