### ISSUE TITLE
Keyboard fingerprinting

### ISSUE THREAD

**Issue by Roman-Nopantski** [pyllyukko/user.js#159]
@pyllyukko For your consideration (from my upcoming new release)

// 2507: disable keyboard fingerprinting (FF38+)
   // The Keyboard API allows scripts to track the "read parameter" of pressed keys, which vary
   // between types of keyboards layouts such as QWERTY, AZERTY, Dvorak, and between languages.
   // https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
   // https://www.privacy-handbuch.de/handbuch_21v.htm
user_pref("dom.keyboardevent.code.enabled", false); //default true
user_pref("dom.beforeAfterKeyboardEvent.enabled", false); // default false
user_pref("dom.keyboardevent.dispatch_during_composition", false); // default false

The last two prefs are already false by default, but I included them for future-proofing

Edit: Android has the same defaults.

**Comment by CHEF-KOCH** [comment]
This is one stuff which is requires for WebAPI's and it's to useful to disable. it doesn't matter if it 'reads' any parameter as long it not submits it without permissions and this is not the case.

**Comment by Roman-Nopantski** [comment]
@CHEF-KOCH now I'm confused, are you saying we should implement this (assuming no issues with android)?

Yes, the pressed keys have to be in a form/text field. The wording needs a cleanup eg:
// disable keyboard fingerprinting (FF38+) (physical keyboards)
   // The Keyboard API allows tracking the "read parameter" of pressed keys in forms on
   // web pages. These parameters vary between types of keyboards layouts such as QWERTY,
   // AZERTY, Dvorak, and between various languages, eg German vs English.

Android - yes, we need to make sure it has no negative side effects. The defaults on Android are the same. I edited the first comment to include this information. BTW, that bug link suggests to me that, as resolved, it setting only applies to physical keyboards. I assume anyone running android is on a smartphone?

As for the rest, I see it as always looking at worse case scenarios - such as having to allow (1st party) JS to run etc. It is better to harden than do nothing at all.

**Comment by CHEF-KOCH** [comment]
* A lot of users running Android on RasperryPI or Emulator -> Keyboard.
* Yes it's default on Android too, for a reason.
* No, basically I was saying we not need to touch these settings or mark them as optional (comment out) because it may get a change in the near future (if it really compromises the security or fingerprint aspect I'm sure someone already had reported it on Tor but I not found something) and I get every notification from there since I commit here and there stuff. 
* I do agree stuff which requires external dependencies to interfere with other stuff like Mega <-> dom storage is maybe critical.

But I not found something which could abuse this, every Browser use it, even the OS itself and several apps.

**Comment by Roman-Nopantski** [comment]
-  thanks .. android on rasp pi .. got it.
-  maybe as commented out is best, with a warning for android users? I only ever focus on the desktop version, and never consider mobile. Just throwing the information here to be used or discarded :)
-  absolutely up to pyllukko, and your comments and information are great, thanks

**Comment by pyllyukko** [comment]
This is interesting.

For some reason, even though I set ```dom.keyboardevent.code.enabled``` to ```false```, [this example](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent#Example) still seemed to work. Any idea?

**Comment by Roman-Nopantski** [comment]
I'm not sure. Maybe it requires a restart (I doubt it, but some do). I can't get it to work in my Windows FF47 - I'll have to try it in a clean portable FF.

**Comment by Roman-Nopantski** [comment]
test page: http://unixpapa.com/js/testkey.html

**Comment by Gitoffthelawn** [comment]
Fantastic discussion.

@Roman-Nopantski Great links for running tests... thanks!

> I assume anyone running android is on a smartphone?

@CHEF-KOCH mentioned Android on the Raspberry PI and emulators... also keep in mind smartphones, tablets, and other devices using bluetooth keyboards.  Plus, there are many tools to share keyboards over WiFi, and even over the internet.  And, of course, there are physical keyboards integrated into some smartphones and a few tablets.

Again, great discussion.

**Comment by Roman-Nopantski** [comment]
@Gitoffthelawn I don't think those two test links are what we're looking for. I got the same information on a vanilla FF with and without the pref set. I don't have a second language/local installed (Windows), but was going to remap my keyboard, reboot, and see what happens (it is after all, trying to detect specific keyboard layouts)

**Comment by Gitoffthelawn** [comment]
@Roman-Nopantski Thanks for pointing that out.... much appreciated.

**Comment by pyllyukko** [comment]
Somewhat related article: [Websites can track us by the way we type – here’s how to stop it](https://nakedsecurity.sophos.com/2015/07/30/websites-can-track-us-by-the-way-we-type-heres-how-to-stop-it/) (just leaving it here for future reference)

The "Keyboard Privacy" add-on is only available for Chrome, but the article has some nice details, info and further links about the fingerprinting technology.

**Comment by Roman-Nopantski** [comment]
Timing attacks suck. I know TBB have built in a lot of random microsecond stuff, and not just in key presses. I wish Mozilla would just pull their finger out and implement a lot of the work TBB have done into the core FF product.

**Comment by fmarier** [comment]
> I wish Mozilla would just pull their finger out and implement a lot of the work TBB have done into the core FF product.

There are folks working on this and it's tracked here: https://wiki.mozilla.org/Security/Tor_Uplift/Tracking

**Comment by Roman-Nopantski** [comment]
@fmarier Thanks. That's awesome. Then the marketing department can tell the world how invasive chrome is, and how seriously private FF can be (not that it can't be already said to be so).

**Comment by Roman-Nopantski** [comment]
FYI: Not assigned yet, but part of the Tor Uplift and looks like it (and many other items) will be tied to the `privacy.resistFingerprinting` pref

Keyboard layout is leaked by KeyboardEvent
https://bugzilla.mozilla.org/show_bug.cgi?id=1222285

**Comment by Roman-Nopantski** [comment]
Might as well close this as it's covered under #203

**Comment by pyllyukko** [comment]
K.
