### ISSUE TITLE
[Talk] Ghostery Vs. Disconnect.me Vs. uBlock

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#16]
Since I'm not a fan of closed source I like to start a _talk_ about the necessary/suggestion of the Ghostery addon. Personally I use [uBlock on Firefox](https://github.com/gorhill/uBlock/) (addon also works on mobile versions too). With an extra filter list which does do the same as Disconnect.me or Ghostery. And nobody knows without deep packing inspection if Ghostery really sends anything back even if the GhostRank option is disabled - we simply must trust them.

Here is my current external uBlock list:
```
! Acceptable Ads
! https://adblockplus.org/en/acceptable-ads
! GNU privacy filter
http://gnuzilla.gnu.org/filters/blacklist.txt
! YouTube all suggestions and comments
! https://easylist-downloads.adblockplus.org/yt_annoyances_full.txt
! YouTube suggestions 
https://easylist-downloads.adblockplus.org/yt_annoyances_suggestions.txt
! YouTube annoyances
! https://easylist-downloads.adblockplus.org/yt_annoyances_other.txt
! YouTube Remove Comments
https://easylist-downloads.adblockplus.org/yt_annoyances_comments.txt
! Cookie removal - http://liamja.co.uk/Prebake/
!https://raw.github.com/liamja/Prebake/master/obtrusive.txt
! Fanboy's Anti-Facebook Filter
!https://secure.fanboy.co.nz/fanboy-antifacebook.txt
```

uBlock itself already comes with the most important ones like _Fanboy's Social Blocking List_, _Anti-ThirdpartySocial_, _Fanboy's Enhanced Tracking List_ and _Dan Pollock's hosts file_ (the last also blocks some super/ever cookies).

Remember that uBlock also have [the ability to block everything via noop](https://github.com/gorhill/uBlock/wiki/Advanced-user-features) (for advanced users only) and make exclusions via white-/blacklist per sites only (Imho much better instead of million of external lists which may lead in huge troubles).

Another benefit of removing such addons like Ghostery/Disconnect are that most people already using an Adblocker such uBlock, AdBlock (or on mobile devices AdAway, AdBlock Plus, uBlock, AdGuard) which safes memory if we load the lists in the already running addon instead of adding just another one like Ghostery/Disconnect.

**Comment by uberspot** [comment]
Does privacy badger offer anything extra to the ublock + extra lists combo(i imagine not)? What lists does it use?

**Comment by CHEF-KOCH** [comment]
I already analyzed a lot of _security addons_ (102), most of them are not necessary if someone with knowledge choose the "correct" ones. e.g. HTTPS-everywhere isn't necessary but much over-hyped with false statements or misleading information all over the web. Let me explain why:

HTTPS-everywhere claims to _secure_ the web, in fact it does not secure anything, it just redirect all sites (except some exceptions [or your own]) due SSL/TLS. But what we learned from the NSA leaks that doesn't automatically means it uses "secure" connections or not compromised web pages. E.g. NSA's Bullrun/Five/Six/Nine-Eye programs was designed to use fake certificates or compromise the encryption on the protocol layer itself. Since there is no database or indicator if the site is secure or not I'm not a fan of such _over-hyped_ plugins (because I generally think we need more protocol security and not more addons! If the 20 or more years old protocols would be replaced with secure ones like IPSec (well Bullrun can also bypass IpSec in some rare situations) nobody would need any plugin - that's a fact. 

So back to the the plugin itself, it was good in the _old times_ but since Mozilla fixes a lot of security things very fast I don't see any recommendation anymore for such plugins. We already can use our about:config stuff which also offers the ability to _force_ SSL/TLS for the websites. And if someone use NoScript (since one or two years) - there is exactly a similar function already implemented it's called [HTTPS](https://noscript.net/faq#https) (under /Advanced/HTTPS/Behavior + Cookies + Permission_. 

So we have 1) option already in Firefox + 2) NoScript - so why we need that addon? If an site really claims to be secure, it uses SSL/TLS by default and not need any redirection (like all banking sites). 3) + We can fine control the settings within Firefox (if you see the mixed content warning you can manually set exception -> HTTPS-everywhere does not respect this and do this automatically - I see this critical since the page may change and actual example seems ghacks.net which try's to use SSL/TLS in the near future - actually with HTTPS-everyhwere enabled it had troubles (due wrong implementation) and without there is a dialog/warning.

About other plugins:
Privacy Badger
Policeman 
RequestPolicy
Disable Plugin & Mimetype Enumeration (not found actually the about
[all others option] for _security reasons_ like KeeFox 

> Does privacy badger offer anything extra to the ublock + extra lists combo(i imagine not)? What lists does it use? 

Short answer no! - Complicated answer: No, but! If you unsure what to choose you can (imho since uBlock 0.6.x release import the rules from privacy badger). Since uBlock get a lot of faster updates compared to the mentioned addons it already take care about the trackers and if they are up-2-date and working, if something is not working just make a issues report and I'm sure it will be imminently fixed!

**Please remember**: More addons also cause more memory usage + the possibility that sites like panopticlick detect the mime!

I do admit that in some rare situations it's good to have an external GUI to control stuff (like NoScript for JavaScript,..) but that also always means with more options there is a potential risk for mistakes. 

From my tests there is absolute no necessary of using so many addons together, if we use uBlock + Noscript + CertPatrol/Ref Control + maybe (if you like to control the important options from a GUI) Random Agent Spoofer but nothing more, the rest is more or less optional depending on the own needs. 

Interesting Wiki stuff about uBlock:
* [Does uBlock block ads or just hide them?](https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F)
* [Overview of uBlock's network filtering engine](https://github.com/gorhill/uBlock/wiki/Overview-of-uBlock%27s-network-filtering-engine)
[How to whitelist a web site](https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site)
.. and [all others](https://github.com/gorhill/uBlock/wiki).

If you read them and choose the correct settings, it should be clear that you can safe a lot of memory and addons with the correct tracker lists. 

Maybe I someday start a global database or someone else to submit/download a configuration to "really" secure the web.

Imho, one of the goals should be to use as less as possible addons, for security and efficiency reasons and better talk about the filter and the configurations - it's more important against the question which addons to choose - or which not.

**Comment by pyllyukko** [comment]
> Since I'm not a fan of closed source I like to start a talk about the necessary/suggestion of the Ghostery addon. Personally I use uBlock on Firefox (addon also works on mobile versions too). With an extra filter list which does do the same as Disconnect.me or Ghostery. And nobody knows without deep packing inspection if Ghostery really sends anything back even if the GhostRank option is disabled - we simply must trust them.

Yes, GhostRank simply must be disabled. Even though it wouldn't be open source per se, shouldn't this still be good enough: "[You can review the source](https://www.ghostery.com/en/faq#q6-general)"?

**Comment by CHEF-KOCH** [comment]
_Sorry for my long posts but I always think context is needed for a quality discussion (always!)._
The problem with the source is that even it's open it doesn't automatically means it's bad and without source it doesn't mean it's always bad - what I'm trying to say is that the server connection is still present, which means besides the source nobody knows if we can trust them with statements like "standard web server log information, such as IP address (we do not store IP addresses) and HTTP headers" - since this can't be proofed. Even with GhostRank disabled that means there are (during the filter update) connections that normal user can't see (and also not the hosts names of the update sources).

The facts are: 
* Ghostery was made by an [ad company Evidon](https://www.ghostery.com/en/faq#q10-general), ..
*... they are [saying that they sell the user data without any real private information in it](https://purplebox.ghostery.com/post/1016023438) - [no proof at all](http://en.wikipedia.org/wiki/Ghostery). 
* The GhostRank is _still_ enabled by default/new install?! (sorry didn't tested the last 3 releases)
* The list is already merged with the AdBlocks/uBlocks easylist + privacy tracker from fanboy (last tested Jan. 2014)
* Ghostery database is updated weekly and the default setting for new trackers is unblocked. - uBlock also offers a _automatic update_ feature 
* Tor Browser Bundle neither use Ghostery or Disconnect (only as default search engine for now) or any other "security" addons (except NoScript and HTTPS-Everywhere) by default (I guess there are always reasons for that to avoid such data information leakage).
* Are We Private Yet? - **Presented by Ghostery** - I've never see an institution which official says there addon is worse against others - is that really representative?
* The risk of bad configuration on Disconnect is almost zero since it doesn't have any similar function like GhostRank
* Ghostery blocks HTTP requests (same as AdBlock/uBlock)
* Wikipedia (en) References FAQ 17 _What does Evidon do with Ghostrank information? (FAQ 17)_ was removed from the official Ghostery FAQ page (I only see [today checked] 16).

No matter how good or bad the addon seems or it claims to be, as long there is already an alternative I not really understand why we not should use that?! But personally I not use any of it except uBlock and just enable/add the _correct_ tracker list to it so without watching or inspecting every single change after every update I think Ghostery or Disconnect.me does not offer anything better protection compared to uBlock or NoScript.

**Comment by pyllyukko** [comment]
> Sorry for my long posts but I always think context is needed for a quality discussion (always!).

No problem. Glad you're giving so much input.

> what I'm trying to say is that the server connection is still present, which means besides the source nobody knows if we can trust them with statements like "standard web server log information, such as IP address (we do not store IP addresses) and HTTP headers" - since this can't be proofed. Even with GhostRank disabled that means there are (during the filter update) connections that normal user can't see (and also not the hosts names of the update sources).

Some connections are always made with blacklists and I think that's a fair tradeoff.

> Are We Private Yet? - Presented by Ghostery - I've never see an institution which official says there addon is worse against others - is that really representative?

I realize that. That's why the bullet point was under Ghostery :) Maybe we could have a disclaimer in the README still.

> Ghostery blocks HTTP requests (same as AdBlock/uBlock)

Quick note about AdBlock... I really never felt that I need it at all with Ghostery + NoScript. Don't see any annoying ads with this setup.

> No matter how good or bad the addon seems or it claims to be, as long there is already an alternative I not really understand why we not should use that?! But personally I not use any of it except uBlock and just enable/add the correct tracker list to it so without watching or inspecting every single change after every update I think Ghostery or Disconnect.me does not offer anything better protection compared to uBlock or NoScript.

I'm really starting to feel, that we need a pros/cons matrix with references on the wiki or something to get to the bottom of this.

**Comment by CHEF-KOCH** [comment]
If I have time I will capture the host names with tcpdump + wireshark (including the traffic during the update process so that (if I somehow able to download/fork the current source) I can compare it with the binary of the current Ghostery addon release to see what's really going on, the rest is more or less FUD without proof since nobody tested the update sources (I also don't see it mentioned in the FAQ) - the addon itself, don't get me wrong is safe to use because Mozilla already scanned it (but not the connections). But the main point is that open projects for non profit company's or institutions should always be preferred for several reasons. E.g. it's much easier to make a pull requests for Disconnect.me or Adblock/uBlock. 

> Quick note about AdBlock... I really never felt that I need it at all with Ghostery + NoScript. Don't see any annoying ads with this setup.

Sure, that also can be said with uBlock/AdBlock + NoScript. It's depending on the site you are visiting and what is used as filters. The problem about NoScript is that it's difficult/hard to monitor all background scripts and such - that's why I prefer uBlock - because the GUI is easy to understand and no beginner I know open the Mozilla Develop tools/console (because there are too much input for beginners) and most of them are not necessary if you only want to watch host names or background scripts.

Another thing what comes to my mind is that it's possible to compile/make the addon without any GhostRank option and add an mini FAQ which sources are downloaded during the update. I guess that break the update compatibility of the addon but with permission it's fork-able (but the question is really if there are needs and people already may use other addons - e.g. Adblock Edge is a Fork of AdBlock but's now discontinued due interest). The fact uBlock and others [already have more benefits](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-default-deny) is still a killer for me.

**Comment by pyllyukko** [comment]
So I tried to open this issue a bit on the README (77a70110ac247302867d985776fc4a6a19b33cb3). Feel free to comment.

**Comment by CHEF-KOCH** [comment]
Thank you, looks good so far, in the meantime [uMatrix](https://github.com/gorhill/uMatrix/releases) for Firefox (atm in a earlier alpha stage) was released [but works quite good so far]. The difference is that uBlock uses a pattern based filters system while uMatrix use another system (I suggest that only experts use uMatrix because it really really can log anything and in the wrong hands it also can block addon update capability - but warning is in uMatrix dashboard implemented).  General it also offers (similar to Random Agent Spoofer) _security features toggles_ like _Strict HTTPS_ (same as HTTPS-everywhere). 

[url=http://abload.de/image.php?img=umatrixsecdzusi.png][img]http://abload.de/thumb/umatrixsecdzusi.png[/img][/url]

> .. notable alternative is to use [uBlock](https://github.com/gorhill/uBlock), but at least currently the installation needs some more work as it's not available in Mozilla's add-on repository.

[Yes it is](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin), called uBlock Origin (from Gorhill) - there now only two main developers (Chris and Alex) - but my fault I not directly liked to it. 

In the meantime I tested/talked to a lot of more people (e.g. in the RAS GitHub issues page) about to harden e.g. supercookies/evercookies. If all stuff is getting really added to RAS, we maybe could think about to recommend to use this addon or adopt his settings to the Firefox configurations file.

**Comment by CHEF-KOCH** [comment]
Tracking Protection is available as a feature since Firefox 35 and newer, and uses Disconnect's blocklist.

**Comment by pyllyukko** [comment]
> Tracking Protection is available as a feature since Firefox 35 and newer, and uses Disconnect's blocklist.

True that and of course we have that enabled also: 9383830efe1c1b49b78fa3d4d70b23fdf53e1429

**Comment by pyllyukko** [comment]
> Tracking Protection is available as a feature since Firefox 35 and newer, and uses Disconnect's blocklist.

Here is a nice paper about the subject: https://kontaxis.github.io/trackingprotectionfirefox/#papers

**Comment by CHEF-KOCH** [comment]
uBlock 0.9.8.2 merged Disconnect.me filter lists:

* [Basic tracking list by Disconnect](https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt)
* [Malvertising filter list by Disconnect‎](https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt)
* [Malware filter list by Disconnect‎](https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt)

**Comment by berrythesoftwarecodeprogrammar** [comment]
ive disabled firefox's tracking protection because i have the disconnect links in ublock, among with many other lists. i use ublock and umatrix together and theyre great. ublock should be recommended to people as an ad/tracking/whatever blocker since its fairly easy to use. umatrix however is for power users who want control over every request their browser makes

**Comment by Hunter-Github** [comment]
+1 on uMatrix. uBlock and uMatrix can work together just fine, and so far Raymond Hill has been trustworthy.

**Comment by MacProGirl** [comment]
Is there an easy way to benchmark Ghostery against uBlock? I was thinking to use both and then see how many scipts Ghostery blocks after uBlock has blocked first.

That of course is only possible if Ghostery i blocking after uBlock. 

Is that order possible to change? What decides that order to begin with? 

Thanks!

**Comment by pyllyukko** [comment]
> I was thinking to use both and then see how many scipts Ghostery blocks after uBlock has blocked first.

I wouldn't recommend using several content blocker simultaneously. Haven't tried it though, but you'll most likely run into problems.

**Comment by nodiscc** [comment]
@MacProGirl Comparing uBlock/ghostery blocklist files would be a good way to do it. My uBlock Origin setup currently has 124 553 network filters and 55 537 cosmetic filters. This certainly overlaps at least a part of ghostery's filters. [about:addons memory](https://addons.mozilla.org/fr/firefox/addon/about-addons-memory/?src=userprofile) is also interesting to benchmark addon memory usage.

I advise running only ublock origin (and requestpolicy + self-destructing cookies).

> Is that order possible to change? What decides that order to begin with? 

In my experience with ublock and requestpolicy this can be very tricky to determine and seems to depend on a lot of factors (addon installation order, and more)

**Comment by CHEF-KOCH** [comment]
You not need more than one blocker, because e.g. uBlock and/or uMatrix are much powerful compared to Ghostery. You can block each single http request, which isn't possible with Ghostery. people often recommend to use both of them, but I don't see any benefit it's just more work and wasting resources (not much but anyway) and can make troubles if both are enabled and blocking other things so on the error level it's problematic (for beginners).

The self-destuction cookies addon was long time good but the feature is already implemented within Firefox, just search on the security settings tab and you can block every third-party cookie, or all of them, or per site which will be cleaned anyway after a shutdown.

**Comment by nodiscc** [comment]
@CHEF-KOCH Self-destructing cookies destroys cookies for a site right after you close the site's tabs, so I would believe it is more efficient that Firefox's cookie cleaning policy?

uMatrix and RequestPolicy both do a very good job (RP has a better UI in my opinion), Policeman was [also mentioned](https://github.com/RequestPolicyContinued/requestpolicy/issues/484#issuecomment-59962520). All of them overlap.

> Is that order possible to change? What decides that order to begin with?

For reference we could not determine this in https://github.com/RequestPolicyContinued/requestpolicy/issues/603

**Comment by CHEF-KOCH** [comment]
That's correct. But it will not destroy HSTS cookies + I don't know if we really need it anymore, because the normal cookies will be destroyed after the session, I don't know if that is directly after you closes it tab or time depending of course another special case is the offline storage which is isolated, I don't know if this addon cleans this. Think about it that each new addon needs more memory and it's possible a security risk because you need to install it first right after the FF start + the time between it's configurated. I do agree that there is currently no option to immediately destroy the cookies. In this case you could create separate or isolate the profile, speaking of creating profiles for normal surfing or blogging. In fact the most secure thingy already can be handled by FF itself via user.js, just block every cookie and after that you can make exclusions (e.g. for Firefox sync). 

I don't know why everyone always popup with RequestPolicy, it's from eff I know but that doesn't mean you still need it, the rules working similar to traditional uBlock/uMatrix filters or the 'new' dynamic filters which are more and more necessary. 

As I said you only need one, maybe as nodisc said, to better or quicker handle exclusions for cookies self-destruction cookies too.

**Comment by nodiscc** [comment]
> it will not destroy HSTS cookies

This is true and why should set your cookies to expire after the browser closes anyway (handled by user.js). But it prevents tracking users across visits during the same browser session (except if you block all cookies, which I find very cumbersome since it breaks many sites). SDC is a nice compromise.

> I don't know why everyone always popup with RequestPolicy

I use it daily and sometimes help maintaining it. There's an active continuation of the project at https://requestpolicycontinued.github.io/, https://github.com/requestpolicycontinued/requestpolicy and the original author [agreed to redirect users to the active fork](https://github.com/RequestPolicy/requestpolicy/issues/407). It is not from EFF, never was. It is way more usable than uMatrix (even non-technical people can use it - you can set it to blacklist mode - low security - or whitelist - higher security, breaks more sites, though this can be mitigated by using [subscriptions](https://github.com/RequestPolicyContinued/subscriptions)). uMatrix can handle blocking requests by type (scripts, static, etc...) but there's actually no way to know the actual type of a resource without downloading it (the file extension means nothing), so this is possibly broken. There's an ongoing discussion about differences betwwen the 2 addons at https://github.com/RequestPolicyContinued/requestpolicy/issues/692

> I always recommend to use CCleaner

I advise against CCleaner since it is proprietary software. [Bleachbit](http://bleachbit.sourceforge.net/) is cross platform and Free Software, and supports more cleaners than CCleaner.

**Comment by CHEF-KOCH** [comment]
To track someone or to fingerprint isn't the same. Cookies/JS must be enabled for several pages, this is why Tor enabled it by default, because the entire web is depending on it but that doesn't automatically mean that you will be tracked but it always means that you will fingerprinted (this is normal), IP, sometimes MAC (e.g. with IPv6) and and and. But e.g. boards need this to ban users. Please stop the discussion that everything is evil, the real evil thing's can't be blocked with any addon. If you found evil cookies, let's start a database about them and send it to mozilla to update there own safe-browsing database (and you will see a small popup ..). But to over and over re-spell the same thing like on the entire net is nothing but useless. Without them almost nothing works.

Yes, I know about RequestPolicy and the eff continued project of it but uBlock is much more agressive, I know what I'm talking about. Just read all the 80+ pages and compare with RP and you will see nothing actually can beat it. And this is for sure. uBlock got a lot of more commits is more under active development than in the entire RP era. RP is from eff, they commit most of initial changes, see [here](https://www.eff.org/deeplinks/2011/03/tracking-protection-lists) and the real successor [Privacy Badger](https://www.bestvpn.com/blog/9682/privacy-badger-alpha-a-new-browser-extension-by-the-eff/) (which is exactly the same under different name).

> but there's actually no way to know the actual type of a resource without downloading it  

Well, this is how the entire net works, just block it or download/scan it not even Rp can change it. Useless to talk about it because the opener not understand how stuff works in this case. They talked about Opera, Opera is Chrome Engine (now) and this is a way different discussion, we are here with FF with Gecko engine this works quite different in so many ways. generally to block Ip adresses (which is not [yet?]) avbl. in uMatrix/uBlock makes not much sense, they may can be changed so this is just nothing but ... 'this addon have this and this addon have that' discussion. Makes no sense. best is to block the DNS/Domain, no addons needed for that. uMatrix/ublock are also only ads blocker and nothing but it The new gimmicks which was added are mostly because people started to asking for it. 

> I advise against CCleaner since it is proprietary software.

This is also FUD. CCleaner is also free software here is a cloud function and professional/business but it's not nessary the free also can monitor everything. 

> supports more cleaners than CCleaner.

Nope, just download the free and open source winap2.ini and you have over 800+ software which can be cleaned, all for free, all by the community. 

Don't get me wrong, just because Schneier use this, no means CCleaner is bad. It makes a fantastic job, maybe BleachBit too, but I bet there are also other projects too. So CCleaner is still most used and trusted software, I don't see any problem to recommend it. To say 'this o this' is better without anything just the source argument is blah blah. Windows is also closed an million people trust it, and some not, this is normal. 

So back to topic please.

**Comment by nodiscc** [comment]
>RP is from eff, they commit most of initial changes

[No.](https://requestpolicycontinued.github.io/About.html)

>uBlock is much more aggressive
>read all the 80+ pages and compare with RP 

They have different purposes and can't be compared. uBlock uses blacklists to block _known_ tracking/advertising methods, RPc blocks _all cross-site requests_ unless you allow them. This prevents unwanted connections to third parties during browsing.

> CCleaner is also free software 
> Did you found any security problems in CCleaner or other problems

It is closed source.
No. I still prefer using a Free Software alternative when one is available.

> So back to topic please. 

Yes. uBlock is enough. Use RP/uMatrix if you want additional control over cross-site requests. Use noscript if you want additional control on javascript.

**Comment by CHEF-KOCH** [comment]
> No

Yes, the same guys working on HTTPSE and the 'new' addon.

> They have different purposes and can't be compared 

Sure they can, umatrix also can block tracking/ads stuff, there is not that GUI option avb. but you can manually (see first comment) copy and paste it. But I agree uMatrix is for advanced user as explained over [here](https://github.com/gorhill/uMatrix/wiki/Using-uBlock-with-uMatrix).

> It is closed source. No. I still prefer using a Free Software alternative when one is available.
> I advise against CCleaner since it is proprietary software. Bleachbit is cross platform and Free Software, and supports more cleaners than CCleaner.

Well your own words, you said 'free' even closed is free. Btw I tried that software which doesn't have any monitoring feature - CCleaner still wins here if it comes to cookies.

Anyway you not need both and it doesn't change the fact you need anyway connect to internet, for downloading the lists (you trust) or to connect to certain domains and use dynamic filters/own to see via logger what is going on. Ghostery can#t do this, and btw Ghostery is also open source and I still can't download the source even after I tried to contact the author (without success). So the 'open source' argument is as always nothing.

**Comment by CHEF-KOCH** [comment]
I'm closing this now, because it's a fact uBlock is a lot of better and if you are advanced user you can just use uMatrix and you not need both (of course you can do whatever you want) but because given reasons it makes not that much sense except memory wasting for loading the domains into it.

**Comment by Ratator** [comment]
Hi CHEF-KOCH, thank you for the talk.
Your recommendation is only to install uOrigin?
What is with Canvas? I think the CanvasBlocker is also needet, or not?

**Comment by pyllyukko** [comment]
> What is with Canvas? I think the CanvasBlocker is also needet, or not?

* #38 
* #345
