### ISSUE TITLE
[Info] I'm leaving the project

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#162]
Hello community, 
I will maintain my thread(s) here and update the Wiki as much as it's possible but I will no longer contribute to the project itself since I've decided to switch to Chromium and my focus lies now there.  

I wish everyone good luck and I hope we still can stay in contact if something is unclear - of course if someone mention me I will see if I can answer on it. My FF addon is still something which is on my radar so I not gave up on it. It's more time management reasons and I need to set priorities. 

Thanks for all the interesting stuff, I know some discussions were not easy because we may had different point of views but this is something which makes a project more interesting (imho). 

CK

**Comment by Roman-Nopantski** [comment]
Thanks @CHEF-KOCH for all your work, much appreciated

**Comment by pyllyukko** [comment]
Thanks for all the contributions!

> Thanks for all the interesting stuff, I know some discussions were not easy because we may had different point of views but this is something which makes a project more interesting (imho).

Indeed! :) Different point of views encourage more argumentation and the argumentation requires even more knowledge (should at least) on the subject, so it makes you dig deeper into the subjects at hand.
