### ISSUE TITLE
IRC, anyone?

### ISSUE THREAD

**Issue by pyllyukko** [pyllyukko/user.js#167]
Do we need an IRC channel for discussion (as the threads get quite big sometimes)? I created `#user.js` on [Freenode](https://freenode.net/) just in case.

Just thought about asking/inviting the regulars, before adding it to the README and having no one there or something :P

Feel free to join.

**Comment by Roman-Nopantski** [comment]
Personally, I think it's better all recorded here. Threads don't really get that long, and you can always start a new one with a summary etc. That said, there may be times when some sort of IM/chat can be better to work out ideas, and I think that should come down to the participants. Having a channel set up ready to go is great - as long as anything substantial from those chats get noted here, which I'm sure they will be.

**Comment by Gitoffthelawn** [comment]
I think GitHub works well for discussing any issues.  Many people rarely, if ever, check IRC these days.  Plus, we don't want important details in two different places.

**Comment by pyllyukko** [comment]
Indeed the idea was to grab all useful excerpts from the channel to here, so that the information will be available.

**Comment by pyllyukko** [comment]
> Or use Gitter maybe ?

Not familiar with Gitter. I'll look into it.

**Comment by pyllyukko** [comment]
There is now [Gitter room](https://gitter.im/user-js/Lobby).
