### ISSUE TITLE
security.enable_tls_session_tickets

### ISSUE THREAD

**Issue by N4melessGitter** [pyllyukko/user.js#169]
'security.enable_tls_session_tickets' got removed a while ago and replaced with 'security.ssl.disable_session_identifiers' which is missing in your user.js.

https://bugzilla.mozilla.org/show_bug.cgi?id=917049
https://bugzilla.mozilla.org/show_bug.cgi?id=967977

**Comment by pyllyukko** [comment]
Thanks!
