### ISSUE TITLE
Disable  E10S remote "knobs"

### ISSUE THREAD

**Issue by licaon-kter** [pyllyukko/user.js#172]
https://asadotzler.com/2016/06/06/firefox-48-beta-release-and-e10s/ 

```
...
When we launch Firefox 48, approximately 1% of eligible Firefox users will get updated 
to E10S immediately. The 1% of release users should get us up to a population similar 
to what we have in Beta so we’ll be able compare the two. About ten days after launch, 
we’ll get another round of feedback and analysis related to the release users with and 
without E10S. Assuming all is well, we’ll turn the knobs so that the rest of the eligible 
Firefox users get updated to E10S over the following weeks. If we run into issues, we 
can slow the roll-out, pause it, or even disable E10S for those who got it.
*We have all the knobs.*
...
```

So they have remote control abilities of everyone’s Firefox instances or what?

**Comment by Roman-Nopantski** [comment]
I'm not 100% sure, but if you have telemetry and health reports etc disabled, then they have no idea if you are eligible. Additionally, I think experiments handle this

// disable experiments
   // https://wiki.mozilla.org/Telemetry/Experiments
user_pref("experiments.enabled", false);
user_pref("experiments.manifest.uri", "");
user_pref("experiments.supported", false);
user_pref("experiments.activeExperiment", false);
// disable mozilla permission to silently opt you into tests
user_pref("network.allow-experiments", false);

**Comment by pyllyukko** [comment]
> I'm not 100% sure, but if you have telemetry and health reports etc disabled, then they have no idea if you are eligible. Additionally, I think experiments handle this

I hope so. It says so in the wiki: "Experiments are available to anyone who has Telemetry enabled", but the blog post doesn't state whether experiments is the mechanism to deploy this E10S thingie.

**Comment by Gitoffthelawn** [comment]
@pyllyukko Mozilla's communication and documentation (outside of MDN) is very poor, IMHO.

**Comment by pyllyukko** [comment]
<https://blog.mozilla.org/futurereleases/2016/08/02/whats-next-for-multi-process-firefox/>

**Comment by nodiscc** [comment]
This page https://wiki.mozilla.org/Electrolysis/Experiments seems to attest that e10s A/B testing methods indeed rely on Telemetry Experiments being enabled.

I think this issue can be closed.
