### ISSUE TITLE
[doc] rewrite installation procedure

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#173]
Followup to https://github.com/pyllyukko/user.js/issues/134, feedback is welcome.

----------------------------------------

# How to use the user.js file

## Download

Different download methods are available:

 * Clone using git: `git clone https://github.com/pyllyukko/user.js`
 * Download and extract the [ZIP file](https://github.com/pyllyukko/user.js/archive/master.zip) containing the latest version.
 * Download the latest `user.js` [directly](https://raw.githubusercontent.com/pyllyukko/user.js/master/user.js)

### Install for a single profile

Copy `user.js` in your current user profile, or (recommended) to a fresh, newly created Firefox profile directory.

The file should be located at:
  * Windows: `%APPDATA%\Roaming\Mozilla\Firefox\*.profilename\user.js`
  * Linux: `~/.mozilla/firefox/*.profilename/user.js`
  * Mac: ???
  * Android: `/data/data/org.mozilla.firefox/files/mozilla/XXXXXXXX.your_profile_name` and see 
[issue #14](https://github.com/pyllyukko/user.js/issues/14)
  * Jolla + Alien Dalvik: `/opt/alien/data/data/org.mozilla.firefox/files/mozilla/XXXXXXXX.your_profile_name`

Do note that these settings alter your browser behaviour quite a bit, so it is recommended to either create a completely new [profile][15] for Firefox or backup your existing profile directory before putting the ```user.js``` file in place.

### Install system-wide

Create `local-settings.js` in Firefox installation directory, with the following contents:

```
pref("general.config.obscure_value", 0);
pref("general.config.filename", "mozilla.cfg");
```

This file should be located at:
 * Win: `C:\Program Files (x86)\Mozilla Firefox\default\pref\`
 * Linux: This file is not required
 * Mac: ???

In `user.js`, Change `user_pref(` to  one of:
 * `pref(` (the value will be used as default value on Firefox profile creation, it can be changed in about:config)
 * `lockPref(` (the value will be used as default value on Firefox profile creation, will be locked and can't be changed) in `user.js` or in Firefox's `about:config` or settings. 

Copy `user.js` to the Firefox installation directory. The file should be located at:

  * Win: `C:\Program Files (x86)\Mozilla Firefox\mozilla.cfg`
  * Linux: `/etc/firefox/firefox.js`
  * Mac: ???

### Updating using git

For any of the above methods, you can keep your browser's `user.js` with the latest version available here: Clone the repository, and create a symoblic link from the appropriate location to the `user.js` file in the repository. Just run `git pull` in the repository when you want to update, then restart Firefox:

````
cd ~/.mozilla/firefox
git clone 'https://github.com/pyllyukko/user.js.git'
cd XXXXXXXX.your_profile_name
ln -s ../user.js/user.js user.js
````

### Verifying

Verify that the settings are effective from [about:support](http://kb.mozillazine.org/Troubleshooting_Information_report#Modified_Preferences) (check the "Important Modified Preferences" and "user.js Preferences" sections).

--------------------------------------------

 - [x] some installation paths are missing
 - [x] References: https://developer.mozilla.org/en-US/Firefox/Enterprise_deployment, ...
 - [x] Add info regarding portable app

**Comment by pyllyukko** [comment]
I think the ```git``` instructions should also be included. Maybe in it's own h3 in the beginning with a title of "obtaining" or "downloading" etc. What do you think?

**Comment by nodiscc** [comment]
Updated with download methods and symlink trick.

**Comment by nodiscc** [comment]
https://github.com/pyllyukko/user.js/pull/174

**Comment by pyllyukko** [comment]
Great. Thanks!

**Comment by pyllyukko** [comment]
I'm tempted to change the OS part to a table like:

| OS      | Path |
| ------- | ---- |
| Windows | `%APPDATA%\Roaming\Mozilla\Firefox\*.profilename\user.js` |
| Linux   | `~/.mozilla/firefox/*.profilename/user.js` |
| Mac     | ??? |
| Android | `/data/data/org.mozilla.firefox/files/mozilla/XXXXXXXX.your_profile_name` and see [issue #14](https://github.com/pyllyukko/user.js/issues/14) |
| Jolla + Alien Dalvik | `/opt/alien/data/data/org.mozilla.firefox/files/mozilla/XXXXXXXX.your_profile_name` |

What do you think?

**Comment by nodiscc** [comment]
Excellent idea

**Comment by pyllyukko** [comment]
I think we should also decide the "format" of the profile directory. Now there's ```*.profilename``` & ```XXXXXXXX.your_profile_name``` and to avoid confusion we should use only one of them.

Just to be consistent.

**Comment by pyllyukko** [comment]
Also: https://github.com/pyllyukko/user.js/commit/a162fdfd5d1f7697428a95122d87ac2149460450#commitcomment-18805138

**Comment by nodiscc** [comment]
Let's go with `*.your_profile_name`? (shorter but explicit)  
https://github.com/pyllyukko/user.js/commit/a162fdfd5d1f7697428a95122d87ac2149460450#commitcomment-18805445

**Comment by Roman-Nopantski** [comment]
Gee guys .. way to leave out all us portable app users :~

`..\Data\Profile`

**Comment by nodiscc** [comment]
@Roman-Nopantski is it `Data\Profile\*.your_profile_name`? Or just Data\Profile\ (meaning portable installation can only have one profile?)

**Comment by pyllyukko** [comment]
> Let's go with *.your_profile_name? (shorter but explicit)

I think ```XXXXXXXX.your_profile_name``` is better and Mozilla seems to use it also (at least [here](http://kb.mozillazine.org/Profile_folder_-_Firefox#Navigating_to_the_profile_folder)).

**Comment by nodiscc** [comment]
Fine either way

**Comment by pyllyukko** [comment]
> Gee guys .. way to leave out all us portable app users :~

Please provide more detail and we'll add it. Or make a PR?

**Comment by Roman-Nopantski** [comment]
That's all the info you need @nodiscc that's it, nothing else), it's a relative path
`..\App\profile` .. that's all, nothing else. What more can I say?

If you unpack your portable FF to eg:
X:\Portable\Firefox\ then your profile would be X:\Portable\Firefox\ `App\profile`
or
P:\WfTs83\epic\Pd86K\banana\ then your profile would be P:\WfTs83\epic\Pd86K\banana\ `App\profile`

**Comment by nodiscc** [comment]
> App\profile
> Data\Profile

I understand the relative path bit. I meant, is user.js at

 * `Data\Profile\*.your_profile_name\user.js` ?
 * `Data\Profile\user.js` ?
 * `App\Profile\user.js` ?
 * `App\Profile\user.js` ?

The `..\` part is not needed here (we don't go up a directory)

**Comment by Roman-Nopantski** [comment]
once again .. it's `\\App\profile\` .. nothing else (I know we were not going up a dir, but I wanted to signify that it was relative - I should have used `\\' )

eg.. to make it totally clear `\\App\profile\user.js`
