### ISSUE TITLE
How to disable "check your plugins" on startup

### ISSUE THREAD

**Issue by lackofbettername** [pyllyukko/user.js#177]
Looked through user.js to see how to disable it but I'm really dumb.

**Comment by Roman-Nopantski** [comment]
`user_pref("plugins.update.url", "");`
This pref is not in the user.js but you can remove mozilla's plugin update URL. Note that pretty soon only flash will be supported and eventually that will be killed off as well. The update not so long ago only checked for silverlight, flash and java.

`user_pref("plugin.scan.plid.all", false);`
If you disable all plugins (or alternatively don't have java/flash/silverlight installed) then there's nothing to check. I also think 64bit will not load plugins (not sure about 64bit flash?)

**Comment by pyllyukko** [comment]
See #52
