### ISSUE TITLE
Why is devtools.chrome.enabled included?

### ISSUE THREAD

**Issue by mindstormer12** [pyllyukko/user.js#179]
What makes `devtools.chrome.enabled` a privacy/security threat?

**Comment by Atavic** [comment]
> The Chrome DevTools are a set of web authoring and debugging tools built into Google Chrome.

Are you a chrome developer? If so, exclude it.
Aren't you a dev? Leave it included.

**Comment by mindstormer12** [comment]
That doesn't answer my question.

**Comment by pyllyukko** [comment]
It was introduced in 9715f3cc7e85da807f3872bb29d2bbc79615387f to make sure remote debugging is not enabled/available.

But apparently it has some additional features, such as [limiting scratchpad privileges](https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Debugging_JavaScript#Scratchpad).

And also apparently to defend against self-XSS (yes, it's a thing) attacks:
* <https://bugzil.la/922161>
* <https://developer.mozilla.org/en-US/docs/Tools/Browser_Console#Browser_Console_command_line>
