### ISSUE TITLE
how to remove addon check on open

### ISSUE THREAD

**Issue by lackofbettername** [pyllyukko/user.js#182]
Just wondering how to remove the firefox addon page when opening the browser.  Thanks :)

**Comment by licaon-kter** [comment]
What?

**Comment by lackofbettername** [comment]
https://www.mozilla.org/en-US/plugincheck/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_campaign=plugincheck-update

The plugin update page.  Just wondering how to disable it.

**Comment by Atavic** [comment]
In Add-ons Manager you can tell to never check for updates, either globally - click on the gear icon - or per addon - click on More

**Comment by pyllyukko** [comment]
Didn't I answer this already at https://github.com/pyllyukko/user.js/issues/177#issuecomment-246302790?

**Comment by Atavic** [comment]
Yes , the page doesn't spawn if a specific value is commented out:
https://github.com/pyllyukko/user.js/issues/52#issuecomment-146524672

**Comment by pyllyukko** [comment]
Maybe we should add a FAQ that has this documented? Although it wouldn't be frequently asked question**s**, but a question. I guess there will be more eventually.

**Comment by Atavic** [comment]
There are many comments on the file.
