### ISSUE TITLE
Browser warnings

### ISSUE THREAD

**Issue by szepeviktor** [pyllyukko/user.js#192]
Have you seen these test sites?
https://cryptoreport.websecurity.symantec.com/checker/views/sslCheck.jsp

You may include it in the README, maybe.

**Comment by szepeviktor** [comment]
It seems Firefox does not warn on "SHA-1 (expires 2017)".

**Comment by fmarier** [comment]
> It seems Firefox does not warn on "SHA-1 (expires 2017)".

Not yet, but the plan is to try again soon: https://blog.mozilla.org/security/2016/10/18/phasing-out-sha-1-on-the-public-web/

The previous attempt unearthed lots of broken systems and had to be postponed: https://blog.mozilla.org/security/2016/01/06/man-in-the-middle-interfering-with-increased-security/

**Comment by pyllyukko** [comment]
Looks good. I'll add it to the README. Thanks!
