### ISSUE TITLE
SHA1 certificates blocking appears broken

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#194]
In my `about:config` the following option is set:

    security.pki.sha1_enforcement_level;2

However following the test suite from #192 (https://cryptoreport.websecurity.symantec.com/checker/views/sslCheck.jsp), I found that the browser still accepts connections to https://ssltest1.bbtest.net/, which it should not:

The Certificate Details > Certificate Signature Algorithm value is `PKCS #1 SHA-1 With RSA Encryption`.

Edit: after re-reading #192: 

>>    It seems Firefox does not warn on "SHA-1 (expires 2017)".

>Not yet, but the plan is to try again soon: https://blog.mozilla.org/security/2016/10/18/phasing-out-sha-1-on-the-public-web/

>The previous attempt unearthed lots of broken systems and had to be postponed: https://blog.mozilla.org/security/2016/01/06/man-in-the-middle-interfering-with-increased-security/

Then I assume the `security.pki.sha1_enforcement_level` switch has no effect at all? If so, this should be clearly commented in the file (https://github.com/pyllyukko/user.js/blob/master/user.js#L613).

Firefox 50.0~b1-1

**Comment by pyllyukko** [comment]
Indeed. Setting ```security.pki.sha1_enforcement_level``` to ```1``` will fix that. I'll clarify the README.

**Comment by fmarier** [comment]
> Then I assume the security.pki.sha1_enforcement_level switch has no effect at all?

It does have an effect, but the effect has recently changed. Looking at the [latest code](https://dxr.mozilla.org/mozilla-central/rev/f9f3cc95d7282f1fd83f66dd74acbcdbfe821915/security/certverifier/CertVerifier.h#143-152), we have:

- 0 = all SHA1 certs are allowed
- 1 = all SHA1 certs are blocked (including perfectly valid ones from 2015 and earlier)
- 2 = deprecated option that now maps to 1
- 3 = only allowed for locally-added roots (e.g. anti-virus)
- 4 = only allowed for locally-added roots or for certs in 2015 and earlier

I'm switching to 4 and will submit a PR for this too.

**Comment by fmarier** [comment]
> I'm switching to 4 and will submit a PR for this too.

That's #196.

**Comment by fmarier** [comment]
> I found that the browser still accepts connections to https://ssltest1.bbtest.net/, which it should not:

My explanation was wrong in #192. It's not the year of expiry that matters, but rather the **year of issuance** (`notBefore`).

SHA-1 certs **issued before 2016** are valid, but SHA-1 certs issued in 2016 are not (it's no longer allowed).

I'm not sure what the above Symantec test site is supposed to test because their cert was issued in 2014 and therefore should be considered valid by browsers.

**Comment by nodiscc** [comment]
Thanks for your explanations.

A sane default for user.js would be 4.

A hardened default would be 1. What proportion of websites does this break? Is it acceptable? When will the last valid SHA1 certificate expire (ie. how long do we have to wait to turn this to 1 definitely?)

**Comment by Atavic** [comment]
On January 1, 2017 Microsoft will stop trusting SHA-1 SSL certificates.
I have a CA that expires, after 20 years, in 2019.

**Comment by fmarier** [comment]
> What proportion of websites does this break? Is it acceptable?

I don't know about the breakage rate, but I suspect a number of websites still rely on their old 2015-issued SHA1 certs.

> When will the last valid SHA1 certificate expire (ie. how long do we have to wait to turn this to 1 definitely?)

Regardless of when these old certs expire, Mozilla will be changing this pref to `3` in 2017, that what [this announcement](https://blog.mozilla.org/security/2016/10/18/phasing-out-sha-1-on-the-public-web/) is about.

Also Firefox [now defaults to `4`](http://searchfox.org/mozilla-central/rev/445097654c1cc1098ee0171a29c439afe363a588/netwerk/base/security-prefs.js#59) as of version 52.

**Comment by Gitoffthelawn** [comment]
It appears 2017 came early.  The default in Firefox 50.1.0 is `3`.
