### ISSUE TITLE
Automate addons download/installation

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#198]
As seen in the issues, some users have put together a script to download and install their favorite extensions. This project could add a Makefile or shell script to take care of this with the recommended addons. This is how I do it (Makefile used to build Debian live system/installer): https://github.com/nodiscc/dbu/blob/master/Makefile#L37 (see ffaddons and xpi targets)

What do you think?

**Comment by pyllyukko** [comment]
Why not. It would be cool, if the Makefile would actually build the whole profile directory, but I'm not sure if that's possible. There might be some switches in FF to populate the dir without starting the browser.

**Comment by nodiscc** [comment]
I'm no longer working on this.

You can find a basic script that installs a few Firefox addons (https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/
 and https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/), system-wide on a Debian-based system here: https://github.com/nodiscc/debian-live-config/blob/master/Makefile.extra#L16
