### ISSUE TITLE
[Suggestion] An addon to clear DOM Storage

### ISSUE THREAD

**Issue by BananaMangoFestival** [pyllyukko/user.js#199]
As far as we can't disable `dom.storage.enabled` without having browsing problems, I recommand this [addon](https://addons.mozilla.org/en-US/firefox/addon/volatile-storage/) that allows you to clear Local Storage, manually or when Firefox starts up and exits.

**Comment by fmarier** [comment]
If you clear your cookies at browser shutdown, it should also clear your local storage, indexeddb, etc.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
Doesn't Self Destructing Cookies also have DOM control? I'm pretty sure.
