### ISSUE TITLE
Disable Social Service API

### ISSUE THREAD

**Issue by robattila128** [pyllyukko/user.js#202]
https://activations.cdn.mozilla.net/en-US/

If you don't use any social-services, you can disable this API completely

> user_pref("social.directories", "");
> user_pref("social.shareDirectory", "");
> user_pref("social.whitelist", "");
> user_pref("social.remote-install.enabled", false);
> user_pref("social.share.activationPanelEnabled", false);
> user_pref("social.toast-notifications.enabled", false);

**Comment by Roman-Nopantski** [comment]
you may want to also use the master switch
https://dxr.mozilla.org/mozilla-central/search?q=social.enable&redirect=false
user_pref("social.enabled", false); // (hidden pref)

**Comment by Gitoffthelawn** [comment]
@Roman-Nopantski Does that single master switch disable the API completely, thus removing the necessity of setting the other 6 preferences individually?

**Comment by Roman-Nopantski** [comment]
@Gitoffthelawn Not sure, but I would guess yes. You know me, I like to future-proof .. hence wiping lists and URLs etc. That said, if your don't use social, then it wouldn't look up directories, or check whitelists, or have any notifications to tell you about. The name implies it's a "master switch" and I would maybe guess that without `social.enabled` set to false, there might be a lot of console errors.

**Comment by Gitoffthelawn** [comment]
@Roman-Nopantski I'm trying to follow Mozilla's code logic in https://dxr.mozilla.org/mozilla-central/source/browser/modules/SocialService.jsm

It appears that `social.enabled` was previously used, but is no longer intended to be used.  In fact, line 282 will clear that pref if there any any social providers.

I'm not clear how one enables or disables social providers... I've never used that feature.

**Comment by pyllyukko** [comment]
Sounds like we need some more info on the topic.

So the code in the above link looks like the following:

```
      // as of fx 29, we no longer rely on social.enabled. migration from prior
      // versions should disable all service addons if social.enabled=false
      if (enabled === false) {
        ActiveProviders.delete(origin);
      }
    }
    ActiveProviders.flush();
    Services.prefs.clearUserPref("social.enabled");
```

To me, it looks like (and the comment says) that in previous versions if the ```social.enabled``` was set to ```false``` it changes the effect of it to "new model" that is disabling all providers individually and then getting rid of the ```social.enabled``` switch.

Also related: #109

**Comment by Atavic** [comment]
It clears the content of `social.enabled` so it is not set to `False` anymore.

**Comment by pyllyukko** [comment]
I'm closing this for now, as the feature is completely opt-in.
