### ISSUE TITLE
[Meta] Track 2FA progress

### ISSUE THREAD

**Issue by pyllyukko** [pyllyukko/user.js#209]
* [Bug 1065729 - Implement the FIDO Alliance u2f javascript API](https://bugzilla.mozilla.org/show_bug.cgi?id=1065729)

**Comment by Atavic** [comment]
Big alliances suck IMHO. I can see where this alliance is headed if successful, as it started from:

> Ramesh Kesanupalli who was then the CTO at Validity Sensors (a fingerprint sensor manufacturer, since acquired by Synaptics).

**Comment by pyllyukko** [comment]
That might be. But as there is already several sites that support this, it would be really nice to be able to authenticate from Firefox also.

**Comment by nodiscc** [comment]
There seems to be some consensus among smart card users

> https://www.reddit.com/r/linux/comments/715o2z/w3c_rejected_appeal_on_web_drm_eff_resigns_from/dn91oyj/

> "Firefox needs to get their shit together though. The only browser that supports me using my yubikey for 2fa is Chrome. I’ve been a lifelong Firefox user but had to switch to chrome in order to use my yubikey with all of the sites that support it. Firefox doesn’t even support smart cards and it’s ridiculous at this point."

So fixing this bug would actually be an improvement

**Comment by pyllyukko** [comment]
Firefox Quantum and the following settings & we have a working U2F:

* ```security.webauth.u2f``` → ```true```
* ```security.webauth.webauthn``` → ```true```
* ```security.webauth.webauthn_enable_usbtoken``` → ```true```
