### ISSUE TITLE
Crash reporter is not disabled

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#226]
Reading through http://kb.mozillazine.org/Breakpad#Can_I_disable_Crash_Reporter.3F, http://kb.mozillazine.org/Breakpad#Can_I_disable_Crash_Reporter.3F, http://techdows.com/2010/01/disabling-mozilla-crash-reporter-in.html, https://stackoverflow.com/questions/28393544/disable-crash-reports-of-firefox-in-linux ... It appears Mozilla Crash Reporter is not disabled when the README suggests it should be.

No crash reporter main switch found in https://dxr.mozilla.org/mozilla-central/source/modules/libpref/init/all.js either.

Disabling it should be investigated (personally I don't mind leaving it enabled since reporting crashes requires user intervention).

**Comment by Atavic** [comment]
Both Crashreporter.exe and .ini can be safely deleted.

**Comment by pyllyukko** [comment]
> when the README suggests it should be.

Good catch! I'll remove it from the README. Indeed this should be looked into.

BTW. Any idea how to make Firefox crash easily (to test these), or should I just go medieval on it with gdb?

**Comment by Roman-Nopantski** [comment]
Go to about:config and turn devtools.chrome.enabled to true

Open Scratchpad with Shift+F4

Switch Environment to Browser and run the following snippet

Cu.import("resource://gre/modules/ctypes.jsm");
let zero = new ctypes.intptr_t(8);
let badptr = ctypes.cast(zero, ctypes.PointerType(ctypes.int32_t));
badptr.contents;

Crash!

**Comment by pyllyukko** [comment]
Worked like a charm! Thanks.

**Comment by pyllyukko** [comment]
We'll leave this enabled, as it's opt-in and the user doesn't have to send it.
