### ISSUE TITLE
Is network.seer.enabled deprecated?

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#228]
Here it is set to `false` but I can't find any sign of this preference on https://dxr.mozilla.org/mozilla-central/source/modules/libpref/init/all.js

Has it been entirely replaced with `network.predictor.*` prefs?

**Comment by Roman-Nopantski** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/issues/10 is your answer. This is everything you P has that G doesn't. It's almost as if we're irrelevant and not a trustworthy resource. It was dropped in FF32

This is also goes against being backward compatible which pyllyukko has said he wants. Now I suppose you'll create a deprecated section and start adding version tags for when they became legacy

**Comment by pyllyukko** [comment]
Not sure and wasn't sure when I added it as seen in 494cff6ad24e7f6eda0febca342e3fa1a187aebc.

**Comment by Roman-Nopantski** [comment]
it was deprecated in FF32
