### ISSUE TITLE
New container tab disabled

### ISSUE THREAD

**Issue by brezn1** [pyllyukko/user.js#232]
Unfortunately the new container feature in FF (52) gets disabled by your user.js 
https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers

![disabled container](https://cloud.githubusercontent.com/assets/5721488/23710954/bdde894c-041e-11e7-9e00-16a30cbb19ec.png)

1. Tried it with a clean install and your user.js: feature disabled
2. Tried it with Ghacks user.js: feature works!  (http://www.ghacks.net/2017/02/12/ghacks-net-firefox-user-js-config-0-11-is-out/)

**Comment by nodiscc** [comment]
@brezn1 does this happen when you disable private browsing?

**Comment by brezn1** [comment]
That did the trick: 
browser.privatebrowsing.autostart  :  **false**

So, there is no way to enable the containers with privatebrowsing enabled by default?

**Comment by nodiscc** [comment]
I supposed so :/ I could not find more info about this; maybe there's a design document/bugzilla ticket explaining why these features are incompatible. Else maybe this should be brought up in a new bugzilla ticket.

**Comment by pyllyukko** [comment]
I don't even have the "New Container Tab" in my Linux version?! And yes, with Firefox 52.

**Comment by brezn1** [comment]
Looks like an open issue
https://github.com/mozilla/testpilot-containers/pull/133/commits
https://github.com/mozilla/testpilot-containers/issues/123

I guess we just have to wait a little while

**Comment by brezn1** [comment]
You need to enable first: about:config -->  privacy.userContext.enabled  TRUE  
;-)

**Comment by pyllyukko** [comment]
> You need to enable first: about:config --> privacy.userContext.enabled TRUE
> ;-)

Of course :stuck_out_tongue: 

But yeah... if you launch with fresh profile (no user.js stuff) -> open "new private window" -> containers are disabled.

**Comment by nodiscc** [comment]
Possible solutions for user.js:

 * browser.privatebrowsing.autostart : false
 * privacy.userContext.enabled : true
 * add a note in private browsing section: `NOTICE: this breaks https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers functionality`

**Comment by pyllyukko** [comment]
> browser.privatebrowsing.autostart : false

Stays enabled for now.

> privacy.userContext.enabled : true

Maybe we could add this anyway, but with proper comments that clarifies this.

> add a note in private browsing section: NOTICE: Disables Containers functionality https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers

Yes. Maybe we should add it also to the "Known problems" section of the README.

**Comment by nodiscc** [comment]
I wanted to start working on this: I switched `privacy.userContext.enabled` to `true` and the `File > Containers` menu item as well as the hamburger menu > `Open container tab` are grayed out.

Firefox 53 on Debian.

Any idea why?

**Comment by pyllyukko** [comment]
And otherwise vanilla Firefox? I have tested the feature with Firefox 52 and it seems to work there.

**Comment by nodiscc** [comment]
Private container feature now seems to work as expected in Debian package firefox 53.0~b8-1
