### ISSUE TITLE
Add a changelog/periodic stable releases

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#233]
http://keepachangelog.com/en/0.3.0/
[Example](https://github.com/shaarli/Shaarli/pull/664/files)

**Comment by pyllyukko** [comment]
I don't think we need one. ```git log``` is our changelog :smiley: Also, since we don't even have any releases or versions.

**Comment by Roman-Nopantski** [comment]
FWIW, I generated a changelog between versions for ghacks, and its a PITA (I'd just type one up based on a six monthly diff). Now I'm here at github, the commit history and compares for those with forks are the changelog. Seriously, it not worth the work. Even between releases, you can do compares.

**Comment by ivan-kolmychek** [comment]
@pyllyukko @Roman-Nopantski let me chime in just to quote the stuff from keepthechangelog.com, as they've already answered that "use `git log`, Luke!" kind of reaction:

> Why can’t people just use a git log diff?
>
>Because log diffs are full of noise — by nature. They could not make a suitable change log even in a hypothetical project run by perfect humans who never make typos, never forget to commit new files, never miss any part of a refactoring. The purpose of a commit is to document one atomic step in the process by which the code evolves from one state to another. The purpose of a change log is to document the noteworthy differences between these states.
>
>As is the difference between good comments and the code itself, so is the difference between a change log and the commit log: one describes the why, the other the how.

I quote it here just for the sake of the argument, as, in my humble opinion and experience, projects do need real changelogs 'cause of reasons mentioned there.

I do agree that changelog for **this particular** repo may be an overkill, but then think we should instead focus this issue on explaining **why** exactly **this particular** repo doesn't need a changelog, like:

- it's just one file so it's easy to check up the diff as all changes are focused

- we don't do actual releases

- etc. etc.

What do you think?

**Comment by nodiscc** [comment]
We might not need a changelog for the reasons @ivan-kolmychek mentioned;

But doing actual releases from time to time with a link to the Github diff/compare page (or a short summary of differences) between new/previous release would help understanding the changes better (currently you need to track and review every commit to understand the changes).

But I agree, low priority.

**Comment by pyllyukko** [comment]
I'm closing this, as I don't think we need one.
