### ISSUE TITLE
Investigate link obfuscation/redirection/unwanted parameters/refferal links cleaning

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#234]
Investigate adding functionality similar to:

https://addons.mozilla.org/en-US/firefox/addon/skip-redirect/ (https://github.com/sblask/firefox-skip-redirect)
https://addons.mozilla.org/en-US/thunderbird/addon/clean-links/ (https://github.com/diegocr/CleanLinks)
https://openuserjs.org/scripts/aycabta/Google_Direct_Linker ...

**Comment by Atavic** [comment]
obfuscation, as spoofing? https://github.com/pyllyukko/user.js/issues/227#issuecomment-285196155
redirection is handled by https://github.com/diegocr/CleanLinks for me.

**Comment by nodiscc** [comment]
https://github.com/diegocr/CleanLinks is not e10s compatible

**Comment by Atavic** [comment]
[noredirect-clone](https://github.com/ghacksuserjs/ghacks-user.js/issues/12#issuecomment-285681177).

For obfuscation on Firefox ESR: https://github.com/dillbyrne/random-agent-spoofer

random-agent-spoofer works on PaleMoon with some workaround, too.

**Comment by Atavic** [comment]
For unwanted parameters: https://github.com/tumpio/requestcontrol/wiki/Testing-page-for-redirection-filtering

**Comment by Atavic** [comment]
[Request Control Filters](https://github.com/ghacksuserjs/ghacks-user.js/issues/149) have a lot of potential.

**Comment by nodiscc** [comment]
I'm no longer working on this.
