### ISSUE TITLE
New-tab option removed in v41, mention override addon (?)

### ISSUE THREAD

**Issue by uberspot** [pyllyukko/user.js#24]
Opening this a bit sooner than necessary, but oh well. 

http://www.ghacks.net/2015/06/28/mozilla-removes-option-to-change-new-tab-page-from-firefox/

**Comment by pyllyukko** [comment]
Thanks for the heads up.

I thought I disabled the whole new tab thingie with ```browser.newtabpage.enabled```, but apparently it wasn't enough so I added d794d47fa3c9033c607d225f31ffbb5e7b519535.

So do you mean like mentioning it in the README or something similar?

**Comment by uberspot** [comment]
Mentioning in the README that "The setting itself might not be enough from ff v.41 and on and you might need an addon like https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/ "  as mentioned in the article. You can revisit this when version 41 comes out cause it's not final yet i guess. I just wanted to note it here for the future along with the addon. :)

**Comment by nodiscc** [comment]
I think this can be closed. The current `user.js` settings effectively disable New Tab Page.
