### ISSUE TITLE
Detail causes for sec_error_ocsp_invalid_signing_cert error

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#240]
While working on #239 I came across this entry in _Known problems_:

> If you get "sec\_error\_ocsp\_invalid\_signing\_cert", it probably means that you don't have the required CA

There are no details on what causes this (probably the CA script?) or workarounds. This should be explained in the relevant user.js section.

**Comment by Atavic** [comment]
You can read `ocsp.responseStatus` with [Wireshark](https://www.wireshark.org/docs/dfref/o/ocsp.html):

```
   OCSPResponseStatus ::= ENUMERATED {
       successful            (0),  --Response has valid confirmations
       malformedRequest      (1),  --Illegal confirmation request
       internalError         (2),  --Internal error in issuer
       tryLater              (3),  --Try again later
                                   --(4) is not used
       sigRequired           (5),  --Must sign the request
       unauthorized          (6)   --Request unauthorized
   }
```

**Comment by nodiscc** [comment]
I'm no longer working on this.
