### ISSUE TITLE
README: import test suites from ghacks-user.js

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#241]
* `[TEST]` fields in https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js
 * https://github.com/ghacksuserjs/ghacks-user.js/issues/6
 * https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-C:-Test-Sites

**Comment by Thorin-Oakenpants** [comment]
We also have a sticky addon issue and wiki addon page if you want to do some sort of diff so we can recommend to each other :) Might come is handy as non-e10s items fall away, and then non WE.

**Comment by nodiscc** [comment]
I think we can wait for ghacks-user.js changes to settle a bit before working on this.

**Comment by pyllyukko** [comment]
It would be nice to have some kind of "how to verify all this works" section that maps most settings/mitigations to test sites that you can use to verify that the controls are working as expected.

**Comment by Atavic** [comment]
Some of these tests point at the IP address - DNS Address. They focus on Anonimity
and are listed under _2. Multiple Tests_ (except ZScaler that focuses on Threat Prevention | Access Control | Data Protection on enterprise).

> If you are now connected to a VPN and you see your ISP IP, then your system is leaking.

Uniqueness vs Entropy is the interest of _1. Fingerprinting_ tests. 

Some URLs under _4. Encryption_ are for specific issues, not always related to a browser, as Heartbleed (redundant?)

I think _5._ does no sense, it's an internal list of pages from Mozilla. _6._ are even more specific tests.

Maybe a short explaining about some of these URLs may be useful. It's a long list and could be cut into 2 groups, with a few essentials as https://html5sec.org/ and https://badssl.com/ followed by _2. Multiple Tests_ and _6._ (explained).

**Comment by nodiscc** [comment]
I'm no longer working on this.
