### ISSUE TITLE
Use spaces instead of tabs for spacing

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#243]
user.js and associated documentation currently uses tabs for element spacing and alignment. As tabs have different widths depending on the environment, this leads to different indentation for different users and contributors, and unneeded/not-working alignment work (eg https://github.com/pyllyukko/user.js/commit/402268af2b09592ecc910af232076895091eb6dc). Attached screenshots of random user.js and documentation sections in 2 editors I frequently use (mousepad and nano):

![cas-indent](https://cloud.githubusercontent.com/assets/3950390/23915076/4a28b080-08e8-11e7-8788-007643ed1be7.png)
![userjs-indent](https://cloud.githubusercontent.com/assets/3950390/23915077/4a2d8344-08e8-11e7-875c-31e2919c6d56.png)

The tabs-vs-spaces question has been largely debated all over the Internet, but the most commonly accepted convention is that:

 * tabs are for _tabulation_
 * spaces are for _spacing/indentation_

 https://softwareengineering.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e/66#66

We should apply this convention and use spaces to align elements.

**Comment by pyllyukko** [comment]
For me, the terminal is the reference on how it should look. This was what I was after:

![tabs](https://cloud.githubusercontent.com/assets/1058704/24081921/9e297b98-0cc5-11e7-8f97-356f811052ea.png)

And since [Vim agrees](http://vimdoc.sourceforge.net/htmldoc/options.html#%27tabstop%27), this has been the easiest and most logical way to do the alignment for me. I'm sure there will be at least as much re-alignment commits even if we would move to spaces.

The README is another story, that could use spaces for the tables as they actually work better when editing them.

**Comment by nodiscc** [comment]
The second screenshot is from my terminal (nano editor in xfce4-terminal).

> I'm sure there will be at least as much re-alignment commits even if we would move to spaces.

Nope, since our terminal emulators use monospace fonts (all characters have the same width).

Edit: for science I just change my terminal font to Comic Sans MS and it looks like xfce4-terminal even forces non-monospace fonts to monospace. Made my eyes bleed so I reverted to [Hack](https://sourcefoundry.org/hack/).

**Comment by pyllyukko** [comment]
> The second screenshot is from my terminal (nano editor in xfce4-terminal).

This is what the same combo looks for me (xfce4-terminal 0.6.3 & nano, version 2.6.0):

![nano](https://cloud.githubusercontent.com/assets/1058704/24082145/53cbb972-0cc9-11e7-95b7-f1415e8d6c81.png)

**Comment by nodiscc** [comment]
> This is what the same combo looks for me
> Looks different on my machine

That's what tabs do. Look different depending on your editor, your terminal, your font, the weather... Spaces don't suffer this problem.

Anyway I agree it's a minor problem. xfce4-terminal 0.8.3-1 and nano 2.7.4-1 here by the way.

**Comment by pyllyukko** [comment]
> I'm sure there will be at least as much re-alignment commits even if we would move to spaces.
> 
> Nope, since our terminal emulators use monospace fonts (all characters have the same width).

What I meant with this, is that it's even easier to get off-by-ones etc. and we would still need to re-adjust 'em from time to time.
