### ISSUE TITLE
Self-destructing cookies not working?

### ISSUE THREAD

**Issue by rafuse** [pyllyukko/user.js#245]
Firefox 52.0
macOS 10.12.3
Self-Destructing Cookies 0.4.11

"Grace period" for cookie deletion is set to 1 second after the tab is closed. Worked perfectly on a clean new Firefox profile. 
Some settings in user.js seem to override this, cookies are only deleted after closing Firefox.

Any ideas?

**Comment by Atavic** [comment]
`Network.cookie.lifetimePolicy` is 2, but [here](https://github.com/privacytoolsIO/privacytools.io/issues/121#issuecomment-269809320) is said 
Self-Destructing CookiesConfiguration:
Keep network.cookie.lifetimePolicy = 0

**Comment by Atavic** [comment]
`user_pref("network.cookie.thirdparty.sessionOnly", true);` try reverting this one also.

**Comment by rafuse** [comment]
Still the same.

I just noticed that the SDC Icon in the top right corner **completely disappears**, you cant even get it back via the "3 stripes" button.
Same goes for the menu entries under "Tools".

**Comment by rafuse** [comment]
> check privacy.firstparty.isolate -> false

It is set to false, yes.

> So just to clarify, the only settings changed are those done by this repo's user.js?

I made a clean new profile, only added SDC. Cookie deletion works perfectly. Closed Firefox, added user.js, opened Firefox -> doesn't work anymore + SDC icons are gone.

> Also, this js will open in PB mode. I have no idea what PB mode does to override cookie settings (i think all it does is enforce session only). Does SDC cookies work if you open>normal window from the menu?

**This seems to be the issue!** Thanks! 
When I turn off PB on autostart inside user.js (`browser.privatebrowsing.autostart -> false`) SDC works again and the icons are there again, too.

So Private Browsing Mode does seem to break Self-Destructing Cookies. 
Should I report this to the dev of the addon? Or do you think he is aware of that?

**Comment by Atavic** [comment]
Cookies aren't saved in Private Browsing, so ther are none to be destroyed.

**Comment by nodiscc** [comment]
@Atavic the second part is correct "All Session Cookies are deleted when exiting Private Browsing Mode".

The first part is not ("Cookies aren't saved in Private Browsing"). Firefox maintains a private cookie jar (first-party only as per user.js settings). As stated in SDC's [FAQ](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/) the addon is unable to access this cookie jar, hence SDC **does not work** in Private Browsing.

If you want SDC to be able to do what it's designed for (delete cookies after a set amount of time after closing a site's tabs), you *have to* disable private browsing
