### ISSUE TITLE
Drop support for older Firefox versions

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#251]
Followup to #86 

At some point when the latest ESR (52) is more widely supported, we could drop preferences that have been deprecated/are no longer present in Firefox ESR.

As noted in #86 some distros still provide older versions of Firefox, so we should wait for them to catch up first. A good indicator of expected Firefox versions seems to be the Debian package [firefox-esr](https://packages.debian.org/search?keywords=firefox-esr) which is still at v45 in Debian stable - the reasoning is that if it's in Debian stable, it's probably old/stable enough to consider dropping support for older versions.

A first step would be dropping preferences that are no longer supported in v45.

**Comment by fmarier** [comment]
https://wiki.mozilla.org/RapidRelease/Calendar shows when the last ESR 45 update will occur (2017-04-18). After that, ESR 45 won't be getting security fixes anymore and so it's not safe to run.

Another indicator is Tor. They are still on ESR 45 but are actively working on fixing up the last remaining issues so they can move to ESR 52.

**Comment by pyllyukko** [comment]
Add Slackware to the list :) Currently on [45.8](http://www.slackware.com/security/viewer.php?l=slackware-security&y=2017&m=slackware-security.398307).

**Comment by pyllyukko** [comment]
> Add Slackware to the list :) Currently on 45.8.

<ftp://ftp.osuosl.org/pub/slackware/slackware64-14.2/ChangeLog.txt>:

```
Tue Mar 28 20:30:50 UTC 2017
patches/packages/mozilla-firefox-52.0.2esr-x86_64-1_slack14.2.txz:  Upgraded.
  Upgraded to new Firefox 52.x ESR branch.
+--------------------------+
```

:tada:

**Comment by nodiscc** [comment]
Debian stable now provides [Firefox ESR 52.2](https://packages.debian.org/search?keywords=firefox-esr).

@pyllyukko time to move pre-Firefox 52 prefs to ignore.list?

**Comment by pyllyukko** [comment]
> @pyllyukko time to move pre-Firefox 52 prefs to ignore.list?

Sure.
