### ISSUE TITLE
Change GH repository description to 'Firefox configuration hardening'

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#259]
For consistence with README.md, and clarity in GH/search engine results.

**Comment by Atavic** [comment]
From `user.js -- Firefox hardening stuff` to `user.js - Firefox configuration hardening` as a search for 'user.js' gives this repo as 1st result.

**Comment by nodiscc** [comment]
On general-purpose search engines (eg searching for `user.js github` or `firefox hardening` on ddg/google/...), this project shows with `Firefox hardening stuff` as title and excerpt, which is not very descriptive. Same problem in github searches.

`Firefox configuration hardening` is what it really is (and is the description used in the README).

This issue is not about ranking better in search engines (I think it's already ranked quite high :+1: ), just improving clarity, and consistency.

**Comment by Atavic** [comment]
I was talking about searches within GH. GH seems to lack presence in common searche engines results.

**Comment by pyllyukko** [comment]
> which is not very descriptive

I agree :) It was just what I came up with when I initially put this on GitHub.

I changed it now.
