### ISSUE TITLE
RC4 bug and SSL3/RC4 fallback list in FF39

### ISSUE THREAD

**Issue by Hunter-Github** [pyllyukko/user.js#26]
Should `security.tls.unrestricted_rc4_fallback`  be set to `false` and `security.tls.insecure_fallback_hosts.use_static_list` set to `false` as well?

References:

* https://archive.is/hyK60
* https://bugzilla.mozilla.org/show_bug.cgi?id=1128227

**Comment by pyllyukko** [comment]
Thanks for the issue. I added ```security.tls.unrestricted_rc4_fallback``` now. Not sure if ```security.tls.insecure_fallback_hosts.use_static_list``` is necessary, as ```security.tls.insecure_fallback_hosts``` list is empty by default and some people might actually need to use this for some sites.

**Comment by Hunter-Github** [comment]
Okay, closing this one, then.
