### ISSUE TITLE
Travis: decrease acorn verbosity

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#268]
`acorn` outputs an unnecessary amount of info on successful builds (~8000 lines!). This adds no valuable information and makes the build log harder to read.

We could experiment with the `--silent` option (https://github.com/ternjs/acorn/) and check that `acorn` still returns useful information when failing, while not bloating the logs in normal conditions. Piping `acorn`s `STDOUT` (but not `STDERR`) to `/dev/null` is another option.

**Comment by pyllyukko** [comment]
With ```--silent```, it still prints e.g. "```Unexpected token```".
