### ISSUE TITLE
Travis: acorn does not detect missing semicolons

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#269]
See #267, https://github.com/pyllyukko/user.js/pull/267/commits/c563b802d4f5321a61c701cb4af5891c595febbd

**Comment by pyllyukko** [comment]
Well fsck!

Here are the builds:
  * [#152](https://travis-ci.org/pyllyukko/user.js/builds/225250812) (```dom.workers.enabled```)
* [#151](https://travis-ci.org/pyllyukko/user.js/builds/225245901) (```app.update.enabled```)

**Comment by nodiscc** [comment]
I'm no longer working on this.
