### ISSUE TITLE
Installation of user.js causes saved passwords to be removed

### ISSUE THREAD

**Issue by crashkopf** [pyllyukko/user.js#27]
Installation of user.js causes saved passwords to be removed from the Firefox   This wasn't explicitly listed as intended behavior in the README file, though it appears to be quite intentional.  I would suggest warning potential users about what may be, to them, an unintended consequence.  Strong language about backing up profile data before proceeding would be highly advisable.

Otherwise, great work.

**Comment by pyllyukko** [comment]
Thanks for raising the issue. Have you checked the profile directory, whether the DB file is still there? Or can you try, if the [refresh](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) feature can bring them back?

I need to add this to the README.

**Comment by crashkopf** [comment]
key3.db and signons.sqlite still exist, but appear to be devoid of any useful data.

I believe the relevant line is:
user_pref("privacy.clearOnShutdown.passwords", true);

The changes from user.js appear to get saved into prefs.js, so I can't save any passwords until I've removed the line about from prefs.js (and removed user.js).  Apparently preferences changed in user.js get saved when any changes are comitted via the preferences dialog.  See: https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences

Lucky for me I've been in the habit of making backups lately.  ;)

**Comment by pyllyukko** [comment]
Do you think the commit above is sufficient to address this issue?

**Comment by crashkopf** [comment]
Yes, I think that will help anyone who reads the instructions thoroughly.

**Comment by pyllyukko** [comment]
Cool. I'll close this issue then.
