### ISSUE TITLE
Two windows are opened due to privacy.clearOnShutdown.openWindows

### ISSUE THREAD

**Issue by EmberFade** [pyllyukko/user.js#288]
- privacy.clearOnShutdown.openWindows, true
- privacy.sanitize.sanitizeOnShutdown, true

When both of those are set it causes Firefox to open two windows upon the second time firefox is launched. It happens on Arch Linux and Ubuntu for me.

There seems to be a bug report about it: https://bugzilla.mozilla.org/show_bug.cgi?id=1334945
and ghacksuserjs/ghacks-user.js/issues/99

~~Even when I revert privacy.clearOnShutdown.openWindows I have to delete prefs.js to actually fix this problem. Otherwise it keeps on opening two windows for me.~~

**Comment by Thorin-Oakenpants** [comment]
see https://github.com/ghacksuserjs/ghacks-user.js/issues/45

These prefs actually seem to be legacy IMO

**Comment by Gitoffthelawn** [comment]
Weird you have to delete prefs.js.  That shouldn't be.

**Comment by Thorin-Oakenpants** [comment]
@Gitoffthelawn Indeed. That I never encountered. May have been a drastic over-reach

**Comment by EmberFade** [comment]
My bad, you're right I don't have to delete prefs.js. I always forget that settings in user.js are written into prefs.js and therefore *deleting* an entry in user.js doesn't undo it.

**Comment by nodiscc** [comment]
Hello, this pref was introduced in https://hg.mozilla.org/mozilla-central/rev/dbd49d378c9b; along with `privacy.cpd.openWindows`.

> These prefs actually seem to be legacy IMO

Even though there is no `Open windows` entry in the `Clear Private Data` dialog, the open windows clearing logic is [still present in the current `sanitize.js`](https://dxr.mozilla.org/mozilla-central/source/browser/base/content/sanitize.js#516), and the prefs are [still present](https://dxr.mozilla.org/mozilla-central/source/browser/app/profile/firefox.js#527) in the lastest Firefox revision.

I will send a path to add `// NOTICE: Clearing open windows on Firefox exit causes https://bugzilla.mozilla.org/show_bug.cgi?id=1334945 (2 windows are opened on Firefox start)` next to that pref until the bugzilla ticket is fixed.

Ref #231

**Comment by Thorin-Oakenpants** [comment]
@nodiscc as I said in https://github.com/ghacksuserjs/ghacks-user.js/issues/45 where I went through the code that is still present

**Comment by nodiscc** [comment]
> These prefs actually seem to be legacy IMO
> ghacksuserjs/ghacks-user.js#45 where I went through the code that is still present
> privacy.clearOnShutdown.openWindows (2803a) is not used

You seem to imply that the value of this pref is not used anywhere in Firefox, but it is seems it is: https://dxr.mozilla.org/mozilla-esr45/source/browser/base/content/sanitize.js#77

```
let openWindowsIndex = itemsToClear.indexOf("openWindows");
let cookiesIndex = itemsToClear.indexOf("cookies");
...
```

**Comment by Thorin-Oakenpants** [comment]
That's not what I said. I said it is **legacy** (IMO). I went thru that code, all of it. Of course it is still in there, that's what legacy means. The point is it does nothing AFAIK in terms of clearing anything extra - think about it for a minute, you are shutting down or clearing data via CPD - it already clears all open windows. It has been suggested this was for controlling some session store, but I cannot find any evidence of that.

The settings obviously do something because it triggers dual windows, but it does nothing to clear any additional data and to the best of my knowledge is a left-over relic -> legacy
