### ISSUE TITLE
Open Firefox two instances version 49<=53

### ISSUE THREAD

**Issue by truefriend-cz** [pyllyukko/user.js#292]
If copy user.js to profile folder and run firefox then run two instances browser.
Any solution?

**Comment by nodiscc** [comment]
https://github.com/pyllyukko/user.js#known-problems-and-limitations: 

> Clearing open windows on Firefox exit causes 2 windows to open when Firefox starts https://bugzilla.mozilla.org/show_bug.cgi?id=1334945

Set `privacy.clearOnShutdown.openWindows, false`

**Comment by Anyon3** [comment]
Got the same problem, I applied the solution of nodiscc, it fixed it.

Thanks

**Comment by pyllyukko** [comment]
I think this issue is covered from our side with #289. Hopefully Mozilla will fix this soon.
