### ISSUE TITLE
[Q] Allowing more protocol handlers/

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#295]
Followup to #285 

> // If you want to enable a protocol, delete all three preferences for the protocol (external.protocolname, warn-external.protocolname, expose.protocolname).

@pyllyukko Can you explain how I would whitelist protocols such as `magnet: irc: mailto: sftp:` for convenience? We could add those prefs commented out for easier tweaking for individual user needs. 

Currently i have set firefox to open magnet links with transmission-gtk and would like to keep this setting without diverging too much from your user.js

**Comment by Atavic** [comment]
Tools > Options > Applications

**Comment by pyllyukko** [comment]
It should be a matter of:

- Setting ```network.protocol-handler.external.(protocol)``` to ```true``` (in your case, since you want to use external program to handle these)
- Setting ```network.protocol-handler.expose.(protocol)``` to ```true```

> // If you want to enable a protocol, delete all three preferences for the protocol (external.protocolname, warn-external.protocolname, expose.protocolname).

I need to fix this part.

**Comment by pyllyukko** [comment]
BTW. Should we have this section as it is now:

```
user_pref("network.protocol-handler.warn-external-default",	true);
user_pref("network.protocol-handler.external.http",		false);
user_pref("network.protocol-handler.external.https",		false);
user_pref("network.protocol-handler.external.javascript",	false);
user_pref("network.protocol-handler.external.moz-extension",	false);
user_pref("network.protocol-handler.external.ftp",		false);
user_pref("network.protocol-handler.external.file",		false);
user_pref("network.protocol-handler.expose-all",		false);
user_pref("network.protocol-handler.expose.http",		true);
user_pref("network.protocol-handler.expose.https",		true);
user_pref("network.protocol-handler.expose.javascript",		true);
user_pref("network.protocol-handler.expose.moz-extension",	true);
user_pref("network.protocol-handler.expose.ftp",		true);
user_pref("network.protocol-handler.expose.file",		true);
```

Or by protocol, e.g.:

```
user_pref("network.protocol-handler.warn-external-default",	true);
user_pref("network.protocol-handler.expose-all",		false);
user_pref("network.protocol-handler.external.http",		false);
user_pref("network.protocol-handler.expose.http",		true);
user_pref("network.protocol-handler.external.https",		false);
user_pref("network.protocol-handler.expose.https",		true);
user_pref("network.protocol-handler.external.javascript",	false);
user_pref("network.protocol-handler.expose.javascript",		true);
user_pref("network.protocol-handler.external.moz-extension",	false);
user_pref("network.protocol-handler.expose.moz-extension",	true);
user_pref("network.protocol-handler.external.ftp",		false);
user_pref("network.protocol-handler.expose.ftp",		true);
user_pref("network.protocol-handler.external.file",		false);
user_pref("network.protocol-handler.expose.file",		true);
```

❓

**Comment by Atavic** [comment]
As it is is simpler to understand.

**Comment by pyllyukko** [comment]
> As it is is simpler to understand.

?

**Comment by nodiscc** [comment]
I think what @Atavic meant is (I'll try) AS IT IS NOW IT IS SIMPLER TO UNDERSTAND and I agree :D

**Comment by pyllyukko** [comment]
> I think what @Atavic meant is (I'll try) AS IT IS NOW IT IS SIMPLER TO UNDERSTAND and I agree :D

Ah, of course 😛 My bad!

**Comment by Atavic** [comment]
I accidentally left out part of the comment!
