### ISSUE TITLE
[Idea] For A Partial Fix For The Known Problems And Limitations

### ISSUE THREAD

**Issue by zero77** [pyllyukko/user.js#297]
Can you please add a GUI menu that allows you to manually enable or disable what is being blocked for each domain, for example like uMatrix  in the below image, although this is only an example.

But instead of css, image, etc. can you add things like WebRTC, DOM storage, SVG etc.

Because, this will help improve security as you would then be able to block everything and only enable it on domains that are broken as a result, whilst still blocking everything on domains that are not broken.

Additionally, this would work better than the web console as it would be quicker to enable disable what is being blocked and specifically for one domain.

Thanks

![untitled](https://cloud.githubusercontent.com/assets/16563034/26108184/a7e04ab2-3a43-11e7-8189-04d6f235b8e5.png)

**Comment by Atavic** [comment]
So are you using uMatrix? 

WebRTC: uMatrix prevents WebRTC from leaking local IP addresses
DOM Storage: https://github.com/gorhill/uMatrix/issues/298#issuecomment-123138622
SVG: uMatrix lists them under images.

This repo modifies browser's settings. You can completely disable DOM Storage by uncommenting [this](https://github.com/pyllyukko/user.js/blob/master/user.js#L63).

**Comment by zero77** [comment]
Thanks, but that's not what I meant, I am suggesting implementing a UI similar to uMatrix.
Because, I think it will help with the issues mentioned in the "Known Problems And Limitations" section.

**Comment by nodiscc** [comment]
@zero77 An addon such as https://github.com/schomery/privacy-settings would have been nice (#25) but with upcoming changes in Firefox it's unlikely it will remain possible to change prefs from an addon.

I will send a draft soon for a simple install/customization dialog for user.js, related to this and #231

**Comment by zero77** [comment]
Yes, #25 would be really good, and #231 would be useful although I was meaning something more dynamic. That allows you to see and change what is being blocked or allowed under each domain on each page like uMatrix although in relation to user.js.

**Comment by pyllyukko** [comment]
Such a GUI would indeed be really sweet, but probably outside the scope of this project. As @Atavic said, we're modifying prefs/settings (e.g. Firefox's behaviour) instead of filtering content and I'm not sure if it's even possible to do these kind of changes on a site-to-site basis.

**Comment by zero77** [comment]
I don't know if this would be possible or feasible but could you do it like this. 

For example, by default every domain visited would use whatever settings were set in user.js as normal, whilst showing what was actually being blocked on that domain.

If the user didn't want something to be blocked under that domain like WebRTC, this would be noted in user.js or another file, either temporary or permanently dependent on what the user selected.

Additionally, each time a domain is visited before applying the default settings in user.js it should check to see if anything is different to the default settings for that domain.

**Comment by pyllyukko** [comment]
> I don't know if this would be possible or feasible but could you do it like this.

I'm afraid the answer (for now at least) is no, we can't do it. We would first have to have a generic extension to tweak the settings, and as @nodiscc has [pointed out](https://github.com/pyllyukko/user.js/issues/25#issuecomment-301950286), even that might not be possible after FF moves to WebExtensions.
