### ISSUE TITLE
Fix descriptions/clarify behavior of AwesomeBar/rich results/autocompletion prefs

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#301]
https://github.com/pyllyukko/user.js/commit/116d9863de4b4b946d699368bebd7e7dff0b7903

**Comment by Thorin-Oakenpants** [comment]
If your hardened user.js is to stop shoulder surfers, then all you need is 
* user_pref("browser.urlbar.autocomplete.enabled", false);

maxRich is redundant. This then leaves end users with a single pref to flip if they want it back (and they can use the options UI to choose the three *suggest options). No need to confuse them with the mess that all that bonus/frequency causes

We're doing much the same (keeping the prefs and updated info) but inactive except for the three *suggest prefs - same as the options interface
