### ISSUE TITLE
svg.disabled= true cripple uBlock origin "Block this element" feature

### ISSUE THREAD

**Issue by MikeZeDev** [pyllyukko/user.js#305]
Tested on a fresh FF profile with a fresh uBO install.

When i right click on a webpage and click on "Block this element" this setting prevent the pink overlay used for selection to be displayed.

I know many settings may break some websites or addons features and i am not complaining, nor requesting a "fix". I just let people know by filling this issue

Should i contact gorhill?

**Comment by Atavic** [comment]
If you turn it to true, does the Element picker work?

**Comment by MikeZeDev** [comment]
Yes. I found the culprit was this setting by using dichotomy (the only setting in user.js)

http://imgur.com/fOP2bRL

svg.enabled = false there is no pink overlay (the other window still work as intended)
svg.enabled = true, no problems

**Comment by Atavic** [comment]
The [highlight](https://github.com/gorhill/uBlock/blob/582edd5e62253738d68ac9f092e0ed6571774b89/src/js/scriptlets/element-picker.js#L228) is javascript and not SVG.

**Comment by MikeZeDev** [comment]
Ikr. But still : disabling "svg" cause the mentioned problem.

And btw i was wrong. the actual setting is 

svg.**disabled** not *enabled*.

Set it to true caused the problem, false is ok.

**Comment by pyllyukko** [comment]
Thanks for letting us know!

> Should i contact gorhill?

It's not their problem IMO :smiley: 

Cross-reference to the SVG PR: #276

**Comment by Atavic** [comment]
@MikeZeDev Can you change the title?

>Should i contact gorhill?

I'd do it.

**Comment by MikeZeDev** [comment]
@Atavic I think its not his problem too. Anyway, changed title :)

**Comment by pyllyukko** [comment]
Fixed in 6ee951ece7c4b8ca2acd1cabd86499c621b21433.
