### ISSUE TITLE
Expose the "chrome" protocol to allow uMatrix and uBlock Origin settings to work

### ISSUE THREAD

**Issue by savyajha** [pyllyukko/user.js#307]
I haven't tried this with other extensions, but when I set the protocol-handler stuff from this user.js, then the settings screens of uBlock Origin and uMatrix stop working. You can open them, but then you cannot click on the tabs up top because the protocol they call is the `chrome` protocol.

I'd suggest the following additions:
```
user_pref("network.protocol-handler.external.chrome",        false);
user_pref("network.protocol-handler.expose.chrome",        true);
```

This makes uMatrix and uBlock Origin usable again on my machine. I'm testing on FF 54.0b12

**Comment by pyllyukko** [comment]
So you mean the "Settings", "3rd-party filters", "My filters", "My rules", "Whitelist" & "About" tabs in the dashboard? I can't reproduce the problem with uBlock, even though I don't have the ```network.protocol-handler.*.chrome``` settings either. Tried it with ESR 52 & 53.0.3.

**Comment by savyajha** [comment]
I'm on 54.0b12 on OSX. Maybe it's only happening on beta on OSX? Anyway, it's with those tabs on uBlock Origin as well as on uMatrix.

**Comment by MikeZeDev** [comment]
I can confirm the problem with uMatrix.
I am on Windows with FF 53.0.3 .
Fresh profile with uMatrix and only 

user_pref("network.protocol-handler.expose-all",		false);

When you click on a tab in uMatrix dashboard FF ask you how to handle this protocol

**Comment by pyllyukko** [comment]
I was able to reproduce it also with uMatrix. uBlock still works, which is a bit weird.
