### ISSUE TITLE
User.js causing firefox to open two windows

### ISSUE THREAD

**Issue by g4jc** [pyllyukko/user.js#308]
Using the user.js from latest git, I am getting two firefox windows each time I start firefox. Removing the user.js solves the situation.

I've tested this on two separate computers with a clean install of Firefox.

**Comment by nodiscc** [comment]
https://github.com/pyllyukko/user.js/issues/288
https://github.com/pyllyukko/user.js/issues/292

https://github.com/pyllyukko/user.js#known-problems-and-limitations:

> Clearing open windows on Firefox exit causes 2 windows to open when Firefox starts
> https://bugzilla.mozilla.org/show_bug.cgi?id=1334945

Set privacy.clearOnShutdown.openWindows to false

**Comment by pyllyukko** [comment]
Yep. Firefox bug ☹️
