### ISSUE TITLE
Consider the following settings

### ISSUE THREAD

**Issue by Genbox** [pyllyukko/user.js#31]
The following settings are "true" by default (Firefox 39.0.3), and should perhaps not be in a hardened config:

gfx.downloadable_fonts.enabled
network.dns.disableIPv6
media.autoplay.enabled
media.wave.enabled
media.webm.enabled
media.webvtt.enabled
media.opus.enabled
media.ogg.enabled
media.eme.enabled
media.directshow.enabled
media.windows-media-foundation.enabled
media.raw.enabled
browser.safebrowsing.downloads.remote.enabled
network.negotiate-auth.allow-proxies
dom.broadcastChannel.enabled
browser.urlbar.suggest.bookmark
browser.urlbar.suggest.history
security.ssl.errorReporting.enabled
media.eme.enabled
browser.taskbar.lists.enabled
browser.uitour.enabled
camera.control.face_detection.enabled
dom.ipc.plugins.enabled
dom.server-events.enabled
dom.vibrator.enabled
experiments.enabled
extensions.getAddons.cache.enabled
social.remote-install.enabled
social.toast-notifications.enabled

**Comment by Genbox** [comment]
I mistakenly put "intl.locale.matchOS" in the first list. It is not enabled by default, at least not in the latest version of firefox.

**Comment by CHEF-KOCH** [comment]
Agreed but the original author does not want to remove obsolete entries for compatibility reasons.

**Comment by Genbox** [comment]
Sorry about that. I would have made a pull request if I knew beforehand that I would find several changes/bugs. However, I started work on the configuration website as mentioned in #25 and found the issues as development progressed.

**Comment by pyllyukko** [comment]
> The following settings are "true" by default (Firefox 39.0.3), and should perhaps not be in a hardened config:

It is intended, that even the settings that are "true" by default are still set. This is to verify, that they are always at those values when Firefox is started. Also, because defaults might change over time. See the "Some of the settings in this user.js file might seem redundant" paragraph on the README.
