### ISSUE TITLE
This project and Tor Browser without Tor

### ISSUE THREAD

**Issue by fjorgyn** [pyllyukko/user.js#316]
This project shares many goals with [Tor Browser development](https://www.torproject.org/projects/torbrowser/design/). Tor Browser can easily be set to [not use Tor](https://www.whonix.org/wiki/Tor_Browser_without_Tor) by setting a few preferences in `user.js`:

```
// Disable proxying
user_pref("network.proxy.socks_remote_dns", false);
user_pref("network.proxy.type", 0);
// Disable TorLauncher extension
user_pref("extensions.torlauncher.prompt_at_startup", false);
user_pref("extensions.torlauncher.start_tor", false);
```

Wouldn't it be a good idea to combine the efforts in some way? Are the projects really that different?

**Comment by Atavic** [comment]
Tor Browser includes some extensions, see [here](https://gitweb.torproject.org/builders/tor-browser-bundle.git/tree/Bundle-Data/linux/Data/Browser/profile.default/preferences/extension-overrides.js).

This project suggests some [here](https://github.com/pyllyukko/user.js#add-ons).

**Comment by pyllyukko** [comment]
At least the following two examples didn't seem to gain any traction:

* [[tor-talk] Firefox hardening](https://lists.torproject.org/pipermail/tor-talk/2014-December/036096.html)
* [#17718 (About:config values need changing) – Tor Bug Tracker & Wiki](https://trac.torproject.org/projects/tor/ticket/17718)

It would be good to at least have an easy way to compare the settings between this and Tor Browser's settings.

**Comment by pyllyukko** [comment]
Hopefully some day.
