### ISSUE TITLE
Block Firefox Shield Recipe Client

### ISSUE THREAD

**Issue by bitpixl** [pyllyukko/user.js#319]
Just witnessed automatic installation/removal of Firefox Shield Addon when I was checking my installed Addons. Turns out it's a user satisfaction/data collecting tool from Firefox.
more info: https://wiki.mozilla.org/Firefox/Shield and https://wiki.mozilla.org/Firefox/Shield/Heartbeat

Please block this by adding following lines
user_pref("extensions.shield-recipe-client.enabled",false);	// Disable FF Customer satisfaction addon
user_pref("extensions.shield-recipe-client.api_url",""); // Remove FF Customer satisfaction addon url

**Comment by pyllyukko** [comment]
> user_pref("extensions.shield-recipe-client.enabled",false); // Disable FF Customer satisfaction

Is this setting documented somewhere?

**Comment by bitpixl** [comment]
Except for the provided link I haven't been able to find much about it.
Because it installs as an Addon and the names of the userprefs are pretty much self-explainatory, I decided to post my findings here.

Hopefully someone (or me) does find proper documentation on this matter in the near future.

**Comment by pyllyukko** [comment]
Where did you find the ```extensions.shield-recipe-client.enabled``` pref? I'm not seeing it in my Firefox 54.0 or Firefox ESR 52.2.0. It also wasn't amongst the settings gathered via ```make downloadffprefs```.

**Comment by bitpixl** [comment]
Hey Pyllyokko, like I said in the TS, I was just viewing the installed addons on my FF 54.0 when the Shield Addon just automatically installed itself and then 10 seconds later uninstalled itself. After that I had the Shield extension entries in about:config. It's clear it in fact is an addon from Mozilla themselves reading the links I provided.

I also don't think everyone is targeted, but just a percentage of people. I would love to hear who else do have these extensions.shield entries in about:config.

(tbh, this automatic temporary addon install/removal by Mozilla to collect user data is pretty disturbing)

**Comment by nodiscc** [comment]
@pyllyukko @bitpixl this pref is handled at https://dxr.mozilla.org/mozilla-central/source/browser/extensions/shield-recipe-client/lib/ShieldRecipeClient.jsm#34

```js
const PREF_BRANCH = "extensions.shield-recipe-client.";
const DEFAULT_PREFS = {
  api_url: "https://normandy.cdn.mozilla.net/api/v1",
  dev_mode: false,
  enabled: true,
  startup_delay_seconds: 300,
  "logging.level": Log.Level.Warn,
  user_id: "",
  run_interval_seconds: 86400, // 24 hours
};
```

That explains why `make downloadffprefs` doesn't gather it

**Comment by bitpixl** [comment]
With the latest 56.0 update, can you re-check if the "extensions.shield-recipe" are now there by default? I'm thinking the new "Firefox data collection and use" options have something to do with this.

**Comment by pyllyukko** [comment]
> With the latest 56.0 update, can you re-check if the "extensions.shield-recipe" entries in about:config are now there by default?

Now they're there.

**Comment by pyllyukko** [comment]
Should be fixed now. Thanks for bringing this up and bumping the issue.

**Comment by Atavic** [comment]
Looking Glass Webextension – part of Mozilla Shield Studies – is on Firefox Quantum:

See [*point 3* of this](https://github.com/CHEF-KOCH/BetterFirefox/issues/19#issuecomment-352039012) discussion.

**Comment by pyllyukko** [comment]
> Looking Glass Webextension – part of Mozilla Shield Studies – is on Firefox Quantum:

If I understood correctly, this is also covered by disabling Shield.

**Comment by Atavic** [comment]
See: https://support.mozilla.org/en-US/questions/1194583

or just set `extensions.pug.lookingglass` to *False*

**Comment by Atavic** [comment]
Official answer is [here](https://support.mozilla.org/en-US/questions/1194583)

**Comment by lckyme420** [comment]
att: bitpixl! earlier in this string you had said you would be interested to know how many people had this add on in their about config, well im one of them. take a look 

app.shield.optoutstudies.enabled;true
extensions.shield-recipe-client.api_url;https://normandy.cdn.mozilla.net/api/v1
extensions.shield-recipe-client.dev_mode;false
extensions.shield-recipe-client.enabled;true
extensions.shield-recipe-client.first_run;false
extensions.shield-recipe-client.logging.level;50
extensions.shield-recipe-client.run_interval_seconds;86400
extensions.shield-recipe-client.shieldLearnMoreUrl;https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/shield
extensions.shield-recipe-client.startupExperimentMigrated;true
extensions.shield-recipe-client.startup_delay_seconds;300
extensions.shield-recipe-client.user_id;88cd4736-ec76-xxxx-xxxxx-xxxxxxxxxxx ( if you need this info bitpixl email me i just am not sure what kinda damage can be done with my personal identifier. so im Hesitant to post it in an open forum . hope i help a little                            -Myke

**Comment by bitpixl** [comment]
@lckyme420 Hi Myke, well yes, I wanted to know back in June 2017 ;) At this point in time Firefox telemetry services are well documented/known and handled accordingly.

**Comment by lckyme420** [comment]
Yes REI I have a tendency to get carried away with whatever it is I'm
researching and I didn't look at the dates on the post until after I'd
already posted but yeah again sorry for bothering you
