### ISSUE TITLE
Duplicated settings

### ISSUE THREAD

**Issue by Genbox** [pyllyukko/user.js#32]
The following settings are duplicated in the config file:
security.ssl3.dhe_dss_des_ede3_sha
security.ssl3.ecdh_ecdsa_des_ede3_sha
security.ssl3.ecdh_rsa_des_ede3_sha
security.ssl3.rsa_aes_128_sha
security.ssl3.rsa_aes_256_sha

The first 3 seem to be duplicated because they fulfill multiple criteria to be disabled. The fourth cipher on the list is commented out, but then enabled again later on. The last cipher is first disabled, then enabled again.

Consider removing duplicates to simplify the configuration file and remove conflicting settings.

**Comment by CHEF-KOCH** [comment]
Thanks for reporting this, but instead of opening several threads it would be easier to make a pull request. I will grep all your issues now and make a pull.

**Comment by ian-csis** [comment]
Sorry about that. I would have made a pull request if I knew beforehand that I would find several changes/bugs. However, I started work on the configuration website as mentioned in #25 and found the issues as development progressed.

**Comment by Genbox** [comment]
Sorry about that. I would have made a pull request if I knew beforehand that I would find several changes/bugs. However, I started work on the configuration website as mentioned in #25 and found the issues as development progressed.

**Comment by pyllyukko** [comment]
Merged
