### ISSUE TITLE
DNS LEAK with USER.js

### ISSUE THREAD

**Issue by j0k3r86** [pyllyukko/user.js#320]
Hey there, 

if i use the User.js profile i have a DNS Leak about my VPN.
With my Standard Profile not. 
I just checked every Addons. Also all lines in User.js for DNS ... but nothing changes

Thanks for your help!

greetz

**Comment by pyllyukko** [comment]
Can you elaborate a bit more? What DNS (request) is leaking and how?

**Comment by Atavic** [comment]
@j0k3r86 Which VPN? The only DNS related entries are:

https://github.com/pyllyukko/user.js/blob/master/user.js#L244
https://github.com/pyllyukko/user.js/blob/master/user.js#L572
https://github.com/pyllyukko/user.js/blob/master/user.js#L582

**Comment by Atavic** [comment]
I have become a skeleton while waiting here.

**Comment by pyllyukko** [comment]
> I have become a skeleton while waiting here.

How about becoming Skeletor?

![skeletor-spoo](https://user-images.githubusercontent.com/1058704/34482200-308f9184-efbf-11e7-9142-cd2366743ec7.jpg)

**Comment by pyllyukko** [comment]
Ping @j0k3r86. I'm closing this now, as we don't have sufficient info. Re-open if needed.
