### ISSUE TITLE
[suggestion] telemetry and resource timing

### ISSUE THREAD

**Issue by bryce-lynch** [pyllyukko/user.js#322]
Your user.js includes almost all of my current settings, except for the following. Shouldn't these be disabled or is it overkill?

toolkit.telemetry.server = ''
toolkit.telemetry.archive.enabled = false

dom.enable_resource_timing = false
dom.performance.enable_user_timing_logging = false

as for the 2 above see http://www.w3.org/TR/resource-timing/
"Statistical fingerprinting is a privacy concern where a malicious web site may determine whether a user has visited a third-party web site by measuring the timing of cache hits and misses of resources in the third-party web site."

**Comment by Atavic** [comment]
Some repositories follow the idea that, by modifying a parent entry as
`user_pref("toolkit.telemetry.enabled", false);`
makes the child entries, as `toolkit.telemetry.server`, inactive and so are left unmodified.
I do the same as you and change the child entries, just in case the parent entry gets rectivated.

**Comment by pyllyukko** [comment]
Our approach is indeed to disable only the "master switches".

```toolkit.telemetry.archive.enabled``` should still be looked into, as there are some reports on the internet about few directories still being created under your Firefox profile even though telemetry should be disabled.

I'll also look into resource timing.

Thanks!

**Comment by Thorin-Oakenpants** [comment]
`dom.performance.enable_user_timing_logging` is default false

FYI: `dom.enable_resource_timing` and `toolkit.telemetry.archive.enabled` are in the monster diff
