### ISSUE TITLE
YouTube progress bar glitched

### ISSUE THREAD

**Issue by firefoxguy** [pyllyukko/user.js#323]
Hi, 

After reconfiguring my browser I'm having issues with the user.js making my YouTube progress look like this. https://i.imgur.com/pLethNg.png

Does anyone know how to fix this? Thank you

**Comment by Forsaked** [comment]
Set line 301 `user_pref("svg.disabled", true);` to `user_pref("svg.disabled", false);` and try again.

**Comment by nodiscc** [comment]
https://github.com/pyllyukko/user.js/issues/291

**Comment by Phidelux** [comment]
The change  suggested by @Forsaked worked perfectly. Thanks.
