### ISSUE TITLE
user.js + NoScript: opening a new tab via cli 'firefox url' does not work

### ISSUE THREAD

**Issue by coffee2code404** [pyllyukko/user.js#324]
When using the user.js in combination with NoScript it is not possible to use 'firefox url' on the commandline to open a url in a new tab within an existing firefox window. The command exits without an error code (status 0) but firefox does not open the url in a new tab.

Tried with: 
clean firefox (54.0.1) profile
relaxed user.js (commit 52719b3aca1e0c19db0c64d03f4c5d79f1888297, current HEAD)
NoScript 5.0.6

**Comment by nodiscc** [comment]
@coffee2code404 Does it work correctly with NoScript disabled? If yes, this should probably be reported to NoScript developers instead...

**Comment by coffee2code404** [comment]
It's kinda strange, it works when I use either NoScript (with a clean prefs.js) or user.js, but as soon as I use both it doesn't work anymore.

I can get it working with the following steps:
* Enable both
* Start Firefox
* Close Firefox
* Move user.js to user.js_back (or something different)

When I start Firefox after these steps, opening urls does work.
Unfortunately there is a new problem: Firefox does not open links when I click on them. I can open links when I right click on them and choose 'Open in new tab'.

If you think user.js is not the main part of the problem I can try to contact the developers of NoScript.

**Comment by pyllyukko** [comment]
> When I start Firefox after these steps, opening urls does work.

It does sound like it's some setting, that NoScript resets after user.js has been removed.

**Comment by pyllyukko** [comment]
I was able to reproduce this. Didn't immediately find the cause, so we'll need to look into this a bit more.

**Comment by dkasak** [comment]
I also got bitten by this, but it took a while to realize the combination of user.js and NoScript was causing it.

**Comment by dkasak** [comment]
I bisected user.js and found that commenting out the following two preferences makes it work again on a clean profile:

    user_pref("network.protocol-handler.expose.http",		true);
    user_pref("network.protocol-handler.expose.https",		true);

However, commenting out those same settings on my regular profile had no effect, even after resetting all of the `network.protocol-handler.*` settings. So it appears there is more to it.

**Comment by pyllyukko** [comment]
> I bisected user.js and found that commenting out the following two preferences makes it work again on a clean profile:

Thanks for this info.

> However, commenting out those same settings on my regular profile had no effect, even after resetting all of the network.protocol-handler.* settings. So it appears there is more to it.

For me, commenting them out, starting Firefox with the old (default) profile makes the link opening work again, but of course we do need these two settings, as otherwise http(s) links stop working.

Indeed there seems to be more to it and apparently there's a difference whether you start FF with these settings present or not. Needs more testing & info on what's happening.

**Comment by pyllyukko** [comment]
@coffee2code404: Is this still happening for you or did Firefox Quantum fix it?
