### ISSUE TITLE
Tim Berners-Lee (W3C), Digital Restrictions Management (DRM) and Encrypted Media Extensions (EME).

### ISSUE THREAD

**Issue by Atavic** [pyllyukko/user.js#325]
While looking at [FF releases](http://ftp.mozilla.org/pub/firefox/releases/55.0b8/) I stumbled upon the following directories:

**mac-EME-free
Win32-EME-free
Win64-EME-free**

Google, Microsoft and a number of content providers as Netflix proposed a built-in DRM 
extension for the Web: the W3C Encrypted Media Extensions (EME).

Recently Tim Berners-Lee, director of World Wide Web Consortium, [approved it](https://www.w3.org/blog/2017/02/on-eme-in-html5/), while 
FSF was vocal for those who opposed to EME since its inception because it breaks
Web users' control of their own devices and weakens both their security and privacy.

### What is DRM?
A basic explanation of DRM is [here](http://www.defectivebydesign.org/what_is_drm_digital_restrictions_management), below a Berners-Lee Quote:

>Having a DRM blob in one’s computer is a security threat, in that it could attack the machine 

### What is EME?
A basic explanation of DRM is [here](https://en.wikipedia.org/wiki/Encrypted_Media_Extensions), below link to W3C EME Concerns:

https://w3c.github.io/encrypted-media/#user-tracking

_What's your stance on this implementation?_

**Comment by fmarier** [comment]
> While looking at FF releases I stumbled upon the following directories:
>
> mac-EME-free
> Win32-EME-free
> Win64-EME-free

See https://bugzilla.mozilla.org/show_bug.cgi?id=1144903.

**Comment by nodiscc** [comment]
Note that Firefox does not ship non-free Content Decryption Modules (CDMs), only the EME implementation that allows loading CDMs. Free Software CDMs exist (https://github.com/fraunhoferfokus/open-content-decryption-module) but are unlikely to be used by publishers. For that reason EME support was [kept in Debian main](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837091). I think it is a reasonable approach, similar to what the situation used to be with non-free NPAPI plugins.

**Comment by Atavic** [comment]
There are multiple ways to make a CDM available to a web app:

-   Bundle a CDM with the browser.
-   Distribute a CDM separately.
-   Build a CDM into the operating system.
-   Include a CDM in firmware.
-   Embed a CDM in hardware.

[An introduction to Encrypted Media Extensions](https://www.html5rocks.com/en/tutorials/eme/basics/)
