### ISSUE TITLE
Bookmark Toolbar not supported?

### ISSUE THREAD

**Issue by collinbarrett** [pyllyukko/user.js#327]
Thanks for the great project! I just discovered it.

I am having a difficult time getting my Bookmarks Toolbar to actually show its bookmarks. I can view all of the bookmarks in my bookmarks toolbar by navigating through the "Show your bookmarks" icon, but when I show the Bookmarks Toolbar itself, it is blank (doesn't show any bookmarks that appear in the Bookmarks Toolbar directory in my Bookmark Manager).

Is this a known issue? Any way to fix it? Any further debugging information I can provide to describe the issue further?

Thanks!

**Comment by Atavic** [comment]
Browser? Version?

Maybe the [relaxed branch](https://github.com/pyllyukko/user.js/tree/relaxed) is useful?

**Comment by collinbarrett** [comment]
Thanks, @Atavic . I will take a look at the relaxed branch. I hadn't discovered that yet.

I am on:

- Windows 7
- Firefox 54.0.1 (64-bit)
- User.js master https://github.com/pyllyukko/user.js/commit/7f0b82aa1f78f5d61fe5fa522d89be48abc1c9fe

**Comment by collinbarrett** [comment]
I just tested the relaxed branch, and it did not resolve this issue.

**Comment by Atavic** [comment]
[user.js](https://github.com/pyllyukko/user.js/blob/master/user.js) has a few entries related to bookmarks.

**Comment by collinbarrett** [comment]
Yes, I should have mentioned that. I did try disabling, with no success, both bookmark-related preferences by commenting out the lines containing:

- browser.bookmarks.max_backups
- browser.urlbar.autocomplete.enabled

**Comment by Atavic** [comment]
Sometimes inported bookmarks have issues.
Another related issue can be the favicons used in the bookmarks.

**Comment by collinbarrett** [comment]
Ah, they were certainly all imported... But, I tried manually creating a new bookmark in the bookmarks toolbar, and it still didn't show up.

**Comment by Atavic** [comment]
So it seems an import "feature". Try deleting them all and create a new one.

**Comment by collinbarrett** [comment]
Gah. Idiot. I just noticed that the "Bookmark Toolbar items" was missing from the bookmark toolbar. Resolved, and not at all related to user.js. My bad.
