### ISSUE TITLE
Recommendation to support CSRF check in Atlassian products?

### ISSUE THREAD

**Issue by collinbarrett** [pyllyukko/user.js#329]
Likely related to #328 , but different enough that maybe opening a new issue is better. I currently use the below referer settings in user.js. However, Atlassian products (specifically JIRA and Confluence) show "XSRF check failed" in the Firefox console when the application makes some REST API POST calls. I was exploring some docs like [here](https://confluence.atlassian.com/kb/cross-site-request-forgery-csrf-protection-changes-in-atlassian-rest-779294918.html), but I am not super familiar with how CSRF works. Can anyone recommend how to try tweaking my user.js settings to support these applications? Maybe, @fmarier ?

Note that these apps are self-hosted and the API calls are made to the same domain and port on which the web application runs.

My Current Referer Config:
- network.http.referer.spoofSource=false
- network.http.referer.XOriginPolicy=1

Screenshots of the API Call:
![ss1](https://user-images.githubusercontent.com/6483057/28575969-1b2fd4b4-7118-11e7-917b-d2657d28d9d3.png)
![ss2](https://user-images.githubusercontent.com/6483057/28575976-1e4aecf6-7118-11e7-9e27-0e07a804f854.png)
![ss3](https://user-images.githubusercontent.com/6483057/28575978-20103e92-7118-11e7-9adf-e2ba09c7e86d.png)

Thanks!

**Comment by fmarier** [comment]
How about this?

- network.http.referer.spoofSource=false (Firefox default)
- network.http.referer.XOriginPolicy=0 (Firefox default)
- network.http.referer.XOriginTrimmingPolicy=2

**Comment by collinbarrett** [comment]
That config works! Thanks, @fmarier . Am I sacrificing substantial privacy guards by loosening these policies up this much?

**Comment by fmarier** [comment]
> Am I sacrificing substantial privacy guards by loosening these policies up this much?

With this config, you're essentially telling unrelated sites the hostname you came from. That's worst then telling unrelated sites nothing, but it's better than the default of telling them everything.

With this config for example, ads on a news site can't use the `Referer` header to tell which article you're reading but they can tell which news site you're on.

**Comment by fmarier** [comment]
@collinbarrett Does JIRA/Confluence work with this config?

- network.http.referer.spoofSource=true
- network.http.referer.XOriginPolicy=0 (Firefox default)
- network.http.referer.XOriginTrimmingPolicy=0 (Firefox default)

**Comment by collinbarrett** [comment]
Hi @fmarier ,

That config does work for Atlassian products. But, I cannot personally use it because Hangouts does not work with that config. (#328)

**Comment by fmarier** [comment]
Thanks @collinbarrett. I was asking so I could update my [blog post](https://feeding.cloud.geek.nz/posts/tweaking-referrer-for-privacy-in-firefox/#Breakage) with these new examples of broken websites that you have discovered.
