### ISSUE TITLE
Recommendation to support uBlock Origin "Back up to file"?

### ISSUE THREAD

**Issue by collinbarrett** [pyllyukko/user.js#330]
Since installing the master branch of user.js, I have noticed that [uBlock Origin](https://github.com/gorhill/uBlock)'s "Back up to file" button fails to actually download a file. I have tried tweaking `browser.download.folderList` and `browser.download.useDownloadDir` with no success. The Firefox console does not log anything. When I click the "Back up to file" button, the "Last Backup:" indicator does update as if the backup was created, but there is no file created in my Downloads, Desktop, or anywhere else that I can see. Does anybody have any suggestions on this?

Thanks.

**Comment by Atavic** [comment]
Backups are stored as `ublock-custom-filters_2017-06-21_15.51.28.txt`
Search for something like:

ublock-custom-filters

**Comment by collinbarrett** [comment]
Right, @Atavic , thanks. I ran a search on my entire computer and did not see any files matching that pattern. I think some setting of user.js is blocking the download? When I visit another download on a public website, like, for example, downloading Firefox. I get a pop-up asking where I would like to save the file. The uBlock Origin button, however, does not generate this pop-up. It must be something to do with it being located on a `chrome://` extension page vs. a typicall http page.

**Comment by Atavic** [comment]
>I think some setting of user.js is blocking the download?
I don't think so.

**Comment by pyllyukko** [comment]
It looks like it stores it in ```~/.mozilla/firefox/XXXXXXXX.your_profile_name/extension-data/ublock0.sqlite```.

**Comment by collinbarrett** [comment]
Thanks, @pyllyukko . Hmm, I'm on Windows. So, I tried running the export. Then, I am looking around in `C:\Users\your_username\AppData\Local\Mozilla\Firefox\Profiles\XXXXXXXX.your_profile_name\' and not seeing anything extension related. Still looking, though.

Thanks.

**Comment by Thorin-Oakenpants** [comment]
browser.download.folderList = 2 (desktop is rather visible, but this does not DISABLE saving to your desktop, you can still do so. The values mean 0=desktop 1=downloads 2=last used )

browser.download.useDownloadDir = false (means you are always ASKED where to save it = means user intervention = security)

When you go to your uBlock Origin dashboard
- My Filters>Export -> my-ublock-static-filters_date_time.txt
- My Rules>Export to file -> my-ublock-dynamic-rules_date_time.txt
- Whitelist>Export -> my-ublock-whitelist_date_time.txt

Each time you Export, you will get a dialog: eg
   *  You have chosen to open my-ublock-static-filters_date_time.txt
      Would you like to save this file [Save File] [Cancel]
^^ NOTE the file is not created - you have to SAVE it first

If you click Save File, you are now presented with the Windows Save Dialog which lets you rename and save the file anywhere you want. By default it should open in the previous save directory.

**Comment by collinbarrett** [comment]
Hi @Thorin-Oakenpants ,

Thanks for the detailed explanation. That's exactly what I would expect. I have the user.js defaults currently of:

```
// PREF: Disable Downloading on Desktop
// CIS 2.3.2
lockPref("browser.download.folderList",			2);

// PREF: Always ask the user where to download
// https://developer.mozilla.org/en/Download_Manager_preferences (obsolete)
lockPref("browser.download.useDownloadDir",			false);
```

As I said [here](https://github.com/pyllyukko/user.js/issues/330#issuecomment-317853626), when I download a file from an actual website, I get the pop-up asking me where I want to save the file as I would expect. But, the uBlock Origin extension doesn't generate any kind of pop-up dialog. If I click "Back up to File" on the Settings tab, it seems to go ahead and save the file automatically (since "Last Backup" gets updated to the current timestamp) in some mystery location on Windows that I can't seem to locate.

Thanks.

**Comment by Thorin-Oakenpants** [comment]
The backup date is a red herring. It also updates on mine, but I have not saved the file. This is a "cosmetic" bug that maybe gorhill might be interested in - I'll file an issue for you - done, see above. I personally doubt that uBo can know if you saved or cancelled because it is outside the extension/FF scope, and more in the realm of OS (i am not a developer!).

OK, I missed this bit "The uBlock Origin button, however, does not generate this pop-up" in your second post. It's called the "Save dialog". That's an entirely different problem.

**Comment by Atavic** [comment]
Have you tried with a new FF profile?

**Comment by pyllyukko** [comment]
The download uses data URL. Should work now.

**Comment by collinbarrett** [comment]
That indeed resolved the issue. Thanks, @pyllyukko !

**Comment by garrygosafe** [comment]
Hello, do you know where my-ublock-backup_ is stored for Chrome on Mac? I wanted to create a bash script to pull this file please. Thanks

**Comment by garrygosafe** [comment]
Hello, I am looking to locate the backup file on Chrome on a Mac, to create a bash script to pull the file.
Would you be able to help with the location of the file please? I recently came across https://github.com/pyllyukko/user.js/issues/330 which discussed this with Firefox but I wasn't able to locate these files on a Mac.
Many Thanks
