### ISSUE TITLE
weird font issue (font-awesome woff2)

### ISSUE THREAD

**Issue by ghost** [pyllyukko/user.js#331]
I use a lightly modified user.js, which allows the use of icon fonts, like the ones provided by font-awesome.

Everything seems to work at first glance, the external fonts load ok and I can see the icons. Except, **some** icons fail to display for some unknown reason.

For example, these icons fail to display:
http://fontawesome.io/icon/download/
http://fontawesome.io/icon/search/

What causes this "selective" behaviour of icons? I'd expect that once a woff/woff2 is loaded all its icons to display or none at all, if font loading is disabled.

The only way I found to make the above icons to display, is to remove the following setting from user.js: browser.display.use_document_fonts

I'd appreciate your suggestions.

Thank you.

**Comment by pyllyukko** [comment]
For me the "download" font seems to work right out of the box and the "search" font starts working when I set ```browser.display.use_document_fonts``` to ```1```. What add-ons are you running?

**Comment by jsmad** [comment]
Why would the "search" font not work by default? While other font icons by font-awesome work ok without making changes?
 
I am using uBlock Origin and Cookie AutoDelete. I'll go do some tests with plugins disabled.

**Comment by pyllyukko** [comment]
> Why would the "search" font not work by default? While other font icons by font-awesome work ok without making changes?

I'm not entirely sure.

**Comment by Atavic** [comment]
Similar issue: https://github.com/pyllyukko/user.js/issues/189
