### ISSUE TITLE
Youtube restyling issue?

### ISSUE THREAD

**Issue by anthologist** [pyllyukko/user.js#335]
Since the latest Youtube restyling, I can't get the homepage to load, it stays white with only the top search bar section visible because of the shadow.
I'm on Firefox ESR 52.3.0 on Linux.
-disabled all my addons: YT still doesn't work.
-tried a new FF profile: YT works.

So that must be the changes to about:config that break something. Is anyone experiencing the same? Do you know where's the problem?

**EDIT:** it succeeds loading after like 30-50 page refresh...

**Comment by savyajha** [comment]
Can you list the changes you've made to your own `user.js` from upstream? I assume you're not using all these settings?

**Comment by anthologist** [comment]
I was posting the list but then I found the problem... I use the general.useragent.override preference to mask the setup as a Chrome on Windows.
If I delete this preference then YT loads istantly, that means it tries to load a UI setup for the wrong browser.
That's not good, I need to find a workaround :'(

**Comment by licaon-kter** [comment]
Does that even work proper?

Eg. Did you do the test in #193 ? Do both javascript and iframe options say "Chrome on Windows" ?

**Comment by anthologist** [comment]
Yes it works properly, it says Chrome on Windows.

**Comment by savyajha** [comment]
While I can't give you a source here, I do remember reading that overriding the user agent manually does more to identify you than not. Easier to simply use `privacy.resistFingerprinting` if you want a spoofed UA.

**Comment by anthologist** [comment]
@savyajha I can hardly believe it since the spread of Windows against the rarity of Linux... that would be interesting to read it if you can find the source.

**Comment by savyajha** [comment]
@anthologist Sorry I'm being lazy (I still haven't got a source for you, it's a Saturday!), but logically, if you spoof your UA manually everything else, for example your fonts, your GL renderer etc. are still Linux while your UA is Windows. That would make you pretty unique. The preference `privacy.resistFingerprinting` aims to be more complete than merely spoofing UA by spoofing everything else as well.

**Comment by anthologist** [comment]
@savyajha True that, but I also use Noscript so many info like fonts are not detectable. Only the websites I whitelist will be able to get all those info. I have privacy.resistFingerprinting  enabled too, I wonder how much it does.
I'll keep an eye on your valid argument, fingerprinting is a beast...

**Comment by bitpixl** [comment]
Have you tried setting user_pref("svg.disabled",true); ?
As said in the user.js file "Disabling SVG support breaks many UI elements on many sites"

**Comment by anthologist** [comment]
@bitpixl Doesn't change anything, I didn't add it as it's Firefox >= 53 compatible.

**Comment by pyllyukko** [comment]
> I was posting the list but then I found the problem... I use the general.useragent.override preference to mask the setup as a Chrome on Windows.
