### ISSUE TITLE
Youtube, skipping in video causes error or loading takes a long time

### ISSUE THREAD

**Issue by bitpixl** [pyllyukko/user.js#336]
When using a fresh profile with only your user.js and viewing (as an example) "https://www.youtube.com/watch?v=tJTbUO_mQFA" (Wan Show - Linus Tech Tips), I've noticed when skipping ahead of the file and or randomly to certain points or close to the end and then select a point close to the beginning, the loading takes alot longer or an error is generated. This happens almost with all youtube videos I skip ahead or go back on the timeline.

I'm guessing it's an caching issue, just don't know which one. I'm using Win10 with latest Firefox 55.0.3 (64-bit)

**Comment by bitpixl** [comment]
Well I've narrowed it down to the "user_pref("privacy.resistFingerprinting",true);" setting.
When I create a fresh Firefox profile with just this setting enabled, youtube videos start acting up when quickly jumping to points in time in the video (jump from start to near the end, then jump back to somewhere at start. If that still works jump to other time segments and it will start loading/crashing).

**Comment by Atavic** [comment]
`media.video_stats.enabled` could be responsible, as explained [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1369309).

**Comment by 0xlne** [comment]
I've noticed a similar behaviour with other media streaming services.
A fresh Firefox install renders the video correctly, but after applying user.js/prefs.js, the video lags considerably.

test device: FulHD Android 7.1.2 device on Snapdragon 821

**Comment by pyllyukko** [comment]
@0xlne: Does changing the ”resist fingerprinting” setting make any difference?

**Comment by 0xlne** [comment]
@pyllyukko I've implemented the latest (vanilla, with resist fingerprinting set as "true") user/prefs.js (as of today) including today's Firefox nightly build (60.0a1) & have yet to experience lags or stuttering.

**Comment by pyllyukko** [comment]
Closing this for now. If this still happens, please re-open the issue.
