### ISSUE TITLE
Suggesting an another approach 

### ISSUE THREAD

**Issue by tunguyen6** [pyllyukko/user.js#338]
The problem is the user.js file causes many compatibility issues, so it cannot be deployed in mass (casual users, organizations). Therefore we would leave Firefox user.js alone or worse is that the users would use Chrome! That defeats the purpose. At personal level it also causes a lot of inconveniences. If I wanted a really high level of privacy I'd use Tor Browser instead, which leads to point number 2.
As mentioned in issue #316, with respect, I think it's a waste of time, I doubt the hardened Firefox is better than Tor Browser (with or without Tor), the more this projects progresses, the more it becomes like Tor Browser. It's not worth it.

Let's build a user.js file and other presets (such as add-ons) that balance between privacy and compatibility, and lean more to compatibility and user experience, that can be deployed in mass. This project still holds values, so what I'm suggesting is another project with that approach.
What are your thoughts?

**Comment by pyllyukko** [comment]
> Let's build a user.js file and other presets (such as add-ons) that balance between privacy and compatibility, and lean more to compatibility and user experience, that can be deployed in mass. This project still holds values, so what I'm suggesting is another project with that approach.
> What are your thoughts?

The [relaxed](https://github.com/pyllyukko/user.js/tree/relaxed) branch aims to be pretty much what you described. Compatible and less breakage that is.

**Comment by tunguyen6** [comment]
I didn't see that, thanks. But the download link is the same with the original version? Please update it.

**Comment by tunguyen6** [comment]
I didn't go through the main page before trying it on my own Firefox profile, I lost all of my browsing history. Luckily I have a backup a few weeks ago. The relaxed version isn't that "relaxed". There is still a lot of work before I can deploy Firefox with a custom user.js.

**Comment by nodiscc** [comment]
> The problem is the user.js file causes many compatibility issues

It is built as a boilerplate with every hardening option enabled, so yes. The issues should all be listed in https://github.com/pyllyukko/user.js#known-problems-and-limitations though, so it should be easy to change corresponding settings. If you find an issue not listed, please report it.

> I lost all of my browsing history

 - [ ] History is disabled as per https://github.com/pyllyukko/user.js/tree/relaxed#caching, but yes, it should also be listed in _Known problems and limitations_
 - [ ] If I remember correctly @pyllyukko would not re-enable history/caching in the relaxed branch. Surely it would help to clearly define the goals of the relaxed variant (get _Known problems and limitations_ to zero? Disabling cumbersome fingerprinting/caching hardening? Discussion is there -> #231).

@tunguyen6 The relaxed branch is also too strict for me, so I [changed a few things in my own variant](https://github.com/pyllyukko/user.js/compare/master...nodiscc:dbu). The goal is to enforce as many hardening options as possible without bothering the user with unusual browser behavior. I've started porting some of these changes here, but it takes time. 

> There is still a lot of work before I can deploy Firefox with a custom user.js.

To save you time you could either pick what you like in https://github.com/pyllyukko/user.js/compare/master...nodiscc:dbu (`dbu` branch) and start your own fork/branch as well, and/or send pull requests to the relaxed branch here if you think something really needs to be changed. But I agree, it takes work.

> Luckily I have a backup a few weeks ago

- [ ] Backups are good to have, it's highly recommended to make one in https://github.com/pyllyukko/user.js/tree/relaxed#single-profile-installation. Probably the paragraph should be moved to a new **Backups**  section at the top of the installation procedure to make it more clear.

 > the download link is the same with the original version? Please update it.

Sent a patch https://github.com/pyllyukko/user.js/pull/339

**Comment by Atavic** [comment]
Either use relaxed pyllyukko's user.js on a fresh profile or stay conservative with a webextention like:
https://addons.mozilla.org/firefox/addon/privacy-settings-webextension/

**Comment by Atavic** [comment]
Either use relaxed pyllyukko's user.js on a fresh profile or stay conservative with a webextention like https://addons.mozilla.org/firefox/addon/privacy-settings-webextension/

**Comment by gitbugged** [comment]
I'm personally quite happy with the strict settings, many of these are not even implemented in Tor Browser. Keep up the great work! Recommend closing the ticket as it was already answered. :yes:

**Comment by pyllyukko** [comment]
> I'm personally quite happy with the strict settings, many of these are not even implemented in Tor Browser. Keep up the great work!

Thanks! 😊 

> Recommend closing the ticket as it was already answered.

True that.
