### ISSUE TITLE
Great stuff you have! Some additional suggestions from my side...

### ISSUE THREAD

**Issue by ghost** [pyllyukko/user.js#344]
Dear all!

Great stuff you have! Some additional suggestions from my side...

Please, have a look at https://github.com/gunnersson and, to be more precise, at https://github.com/gunnersson/my_Mozilla_settings !

That's my repo and project. There's no intention of _bad_ **rivalry**, but just _good_ **competition** by me. In fact, there are many users and repos at GitHub of similar idea and content.

But it would be my intention to bring them all a bit together for sharing and collecting.

Maybe, in this way Mozilla Firefox and Mozilla Thunderbird could be a real joy for many people...

Thank you and kind regards,

Gunner

**Comment by pyllyukko** [comment]
Thanks! Will have a look at your project.

> In fact, there are many users and repos at GitHub of similar idea and content.

Yes there is ☺️ 

> Maybe, in this way Mozilla Firefox and Mozilla Thunderbird could be a real joy for many people...

For those of us who demand more, yes.

**Comment by macandchief** [comment]
I'm wondering: Do you have the service Detect captive portal disabled?

It should be disabled, otherwise it makes all the time connections to www.detectportal.firefox.com

**Comment by nodiscc** [comment]
@macandchief, @Thorin-Oakenpants is right, Captive Portal is disabled in https://github.com/ghacksuserjs/ghacks-user.js, but not here. I think improving the automatic diff tools (https://github.com/pyllyukko/user.js/issues/256) will help everyone notice interesting prefs in other people's work.

We could list https://github.com/gunnersson/my_Mozilla_settings and others (I think we listed them somewhere...) in a separate section in https://github.com/pyllyukko/user.js#other-documentation (ghacks-user.js is already listed there) - edit: already on the TODO list at https://github.com/pyllyukko/user.js/issues/256#issuecomment-352540788.

Then we could also add diff targets in the Makefile for those variants. There are already partially-working diff targets for Firefox upstream and TBB preferences.

**Comment by pyllyukko** [comment]
> I'm wondering: Do you have the service Detect captive portal disabled?
> 
> It should be disabled, otherwise it makes all the time connections to www.detectportal.firefox.com

Fixed in 456a2b7063bbb21197769217e7ddabe31fe808d6.

**Comment by pyllyukko** [comment]
The links now return 404 - "This is not the web page you are looking for.".
