### ISSUE TITLE
"Clear All Data" broken under FF 57 using relaxed variant

### ISSUE THREAD

**Issue by SpotComms** [pyllyukko/user.js#347]
Under about:preferences#privacy the Site Data section it just always says "Calculating side data size..." and "Settings" and "Clear All Data" is greyed out. No errors are printed out to console.

Using the latest relaxed version with Firefox 57.0-2 on Arch Linux

**Comment by pyllyukko** [comment]
Can you check whether changing ```browser.cache.offline.enable``` affects this?

**Comment by SpotComms** [comment]
@pyllyukko that was indeed it!
