### ISSUE TITLE
Different profiles still necessary?

### ISSUE THREAD

**Issue by Ratator** [pyllyukko/user.js#350]
In the past, before I knew this, I sometimes used a new private window for my own session while browsing, so Facebook, for example, could not have guessed that I was shopping clothes in the normal window. At least I thought so.

In "Further hardening - This is not enough!" you recommend using different profiles for different purposes.
**But is that still necessary with this user.js-master?**

I tried to find an answer with Add-on Lightbeam, but without success. He showed me trackers for different tabs in the same window with user.js-master, but I do not know how representative that is.

**Comment by pyllyukko** [comment]
> In "Further hardening - This is not enough!" you recommend using different profiles for different purposes.

With the relaxed branch, you can also use Firefox's containers for this.

> But is that still necessary with this user.js-master?

It is. So even though the master branch enforces private browsing mode, it still shares the cookies (and whatnots) throughout all the tabs. So if you're logged in to Facebook, and browse a site that has Facebook's trackers... they will know.

Even though private browsing (and all the other features enabled by this user.js) helps, it doesn't make you non-trackable. Think of it as a session. Every time you open the browser, it starts from scratch, but starts building up data regarding the trackers. Once they have the data, they just need the link to your identity, which they will get when you login to services. It would be good practice to close the browser often, to "clear" the session.

> I tried to find an answer with Add-on Lightbeam, but without success. He showed me trackers for different tabs in the same window with user.js-master, but I do not know how representative that is.

Lightbeam doesn't work properly with this user.js, see the [Known problems and limitations](https://github.com/pyllyukko/user.js#known-problems-and-limitations) section.

Did this answer your question?

**Comment by Ratator** [comment]
Thank you for your answer.

> Did this answer your question?

Of course.

It just seems to be a never-ending lovestory until you find the golden mean. For example, I did not know that uBlock Origin in advanced mode could be so complicated.

It takes a training until everything becomes useful in everyday life. Add-on to add-on in comparison browsing-speed, etc.

But I have to get through.
