### ISSUE TITLE
Startup issue with user.js relaxed branch

### ISSUE THREAD

**Issue by bryce-lynch** [pyllyukko/user.js#352]
I've been using the relaxed branch of your user.js for a while and while it's very good, I have a small "cosmetic" issue: when I start firefox, its window appears, quickly closes itself and then reappears.

This behaviour (which disappears if I remove user.js and prefs.js) has the side-effect of making it impossible to use parameters from command line (e.g. firefox http://mywebsite.com just starts firefox without loading the specified url). This is with the latest firefox on arch linux.

Any idea which configuration setting(s) could be the culprit?

**Comment by pyllyukko** [comment]
> Any idea which configuration setting(s) could be the culprit?

Not yet, but this sounds similar than #324. I was not aware that there was one "ghost" window opening and closing.

**Comment by bryce-lynch** [comment]
I'm not using NoScript, and I have also tried disabling all extensions. The problem only goes away if I remove user.js and prefs.js. If you haven't experienced this maybe it has something to do with my settings. Thanks anyway.

**Comment by pyllyukko** [comment]
It still might be the same issue. I would recommend to experiment with the ```network.protocol-handler.expose*``` settings and see if you get it working.

**Comment by bryce-lynch** [comment]
Yep, already tried restoring the whole network.protocol-handler.* to default and didn't work.

**Comment by bryce-lynch** [comment]
Ok, key found: it's privacy.clearOnShutdown.openWindows
I didn't see the big NOTICE you put in user.js which states: "Clearing open windows on Firefox exit causes 2 windows to open when Firefox starts".
