### ISSUE TITLE
Whitelist view-source protocol

### ISSUE THREAD

**Issue by MikeZeDev** [pyllyukko/user.js#353]
When i wanted to view the source code of a webpage there was an alert .

Same story than with other non whitelisted protocols and 

> user_pref("network.protocol-handler.warn-external-default",	true); 

Solution : add

> user_pref("network.protocol-handler.external.view-source",		false);
> user_pref("network.protocol-handler.expose.view-source",		true);

I think view-source whitelisting is safe.

**Comment by pyllyukko** [comment]
> When i wanted to view the source code of a webpage there was an alert .

How can this be reproduced? For me right click -> "View Page Source" works without setting ```view-source``` protocol handler.

**Comment by Atavic** [comment]
I think he has set a specific editor in "view_source.editor.path" 
For completeness, this option needs "view_source.editor.external" set to true.

**Comment by pyllyukko** [comment]
> I think he has set a specific editor in "view_source.editor.path"
> For completeness, this option needs "view_source.editor.external" set to true.

Still can't reproduce. Opened nicely with external editor without protocol whitelisting.

**Comment by Atavic** [comment]
>For me right click -> "View Page Source" works without setting view-source protocol handler.

Like me.

**Comment by pyllyukko** [comment]
@MikeZeDev: Which OS are you using?

**Comment by MikeZeDev** [comment]
Sorry for the delay.
Windows 10, and FF 58.0.1.

I am happy to say i am now also unable to reproduce it, too.
It was happenning even on a fresh profile before (no ext). Now, even without the proposed lines, its working as intended.

I think this issue can be closed.
