### ISSUE TITLE
UI glitch: tab close button

### ISSUE THREAD

**Issue by wickedsp1d3r** [pyllyukko/user.js#354]
Hello,

I get an interesting UI glitch: a black box instead of tab close button.

![tabs](https://user-images.githubusercontent.com/1852854/34116062-4ca39a3e-e40f-11e7-9451-db5fc9011dbe.jpg)

I have not experienced this issue with earlier Firefox version(s).
I have tried to create a freshly new profile. Every time user.js is applied, the problem arises.
It does not affect the functionality of the button. Just a bit irritating.

Firefox 57.0.2
macOS 10.13.2

**Comment by pyllyukko** [comment]
I was unable to reproduce this (I'm on Linux). Can you try switching ```svg.disabled```?

**Comment by Thorin-Oakenpants** [comment]
set `browser.tabs.remote.autostart`-> true

**Comment by wickedsp1d3r** [comment]
Thanks for the suggestion. Unfortunately it did not solve the problem.
In addition to tabs, I see these black boxes also in the search bar.

![searchbar](https://user-images.githubusercontent.com/1852854/34165884-6661c6a0-e4d5-11e7-9ab4-7e4577511b76.jpg)

`svg.disabled` is set to `false`.

**Comment by Thorin-Oakenpants** [comment]
@wickedsp1d3r Just double checking

- what version of FF are you using?
- do you have e10s enabled/working
- do you have the e10s rollout system addon (open about:support and scroll down to `Firefox Features`)

It was the fact that in my new profile tests, I was using e10s and the missing e10s rollout xpi didn't fix things as I bulk changed prefs (both adding all the tweaks in a user.js, and bulk clearing the lot in scratchpad). I am almost certain this is to do with e10s.

Weird idea: try `accessibility.force_disabled`->1

**Comment by Thorin-Oakenpants** [comment]
FWIW .. on FF57.0.2 on windows
- brand new profile + added the user.js (and all system addons present) - cannot reproduce
- brand new profile + added the user.js (**and all system addons removed**) - cannot reproduce

Maybe its mac specific

**Comment by pyllyukko** [comment]
> Maybe its mac specific

Starts to seem like it.

**Comment by wickedsp1d3r** [comment]
I have `browser.tabs.remote.autostart` set to `true`.

But it was not enough.
There's a setting `extensions.e10sBlocksEnabling`, which had to be set `false`.
Maybe because add-ons disable Multiprocess Windows (?)

Now the close buttons are normalized.

**Comment by Thorin-Oakenpants** [comment]
> I am almost certain this is to do with e10s.

Well, there we go. Good to know its sorted. Weird tho, the e10s system addon should have prevented this sort of thing. And.. FYI .. `extensions.e10sBlocksEnabling` is deprecated in 58, so it would have solved itself in 4 weeks time :)
