### ISSUE TITLE
[Suggestion] 3 scripts to add in Greasemonkey / Tampermonkey

### ISSUE THREAD

**Issue by BananaMangoFestival** [pyllyukko/user.js#356]
https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts

That might be interesting to add these scripts in order to hardening privacy in Firefox, isn't it?

**Comment by Atavic** [comment]
You need greasemonkey or similar extension (currently not listed under addons section)
Greasemonkey needs JS enabled.

**Comment by pyllyukko** [comment]
Seems interesting, yes. But as @Atavic says, that's already multiple "steps" away from our recommendations. Thanks for the suggestion, but I'm not adding it at least at this point.
