### ISSUE TITLE
macOS only: copy/paste to Google Docs

### ISSUE THREAD

**Issue by collinbarrett** [pyllyukko/user.js#360]
I have loosened a few of the user.js rules to suit my usage. I use Google Docs a fair bit, so I have enabled the js-based copy/paste settings. I can now copy/paste in Firefox with user.js on Windows, however pasting via cmd+v on macOS into a Google Doc does not work (enters a literal "v" rather than the copied text). See the modified settings I am using at the link below. Any suggestions? Maybe it's just a macOS-Firefox bug/issue of some kind.

https://github.com/pyllyukko/user.js/compare/master...collinbarrett:master

**Comment by Thorin-Oakenpants** [comment]
`privacy.resistFingerprinting` & the cmd key on OSX as per ticket - https://bugzilla.mozilla.org/show_bug.cgi?id=1405810 .. doesn't have to be Google Docs, it can happen anywhere

The idea is that the UA spoofing should not try to spoof the OS, but instead limit it to four options (windows, Mac, android, and linux for the everything else) - and this will then fix all sorts  of issues such as android being served desktop websites, etc. There really are a ton of quirks when the OS is spoofed and differs from the real OS.

**Comment by collinbarrett** [comment]
Yep, that was it! Thanks so much!

**Comment by Thorin-Oakenpants** [comment]
testing ..

**Comment by Thorin-Oakenpants** [comment]
@pyllyukko - I am trying to post a reply to #14 and for some reason my posted comments never happen - almost as if I have been banned from that issue? I am allowed to type comments and preview, but when I click the comment button to post it, the comment field just clears and nothing happens. Yup, I refreshed etc. Here is what I was trying to post

> @TerkiKerel used remote debugging from desktop FF to run a script which applies your user.js (just copypasta it in to the script) prefs - see https://github.com/ghacksuserjs/ghacks-user.js/issues/318
> 
> I have not tested this myself (yet)

**Comment by Thorin-Oakenpants** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1404608 (do not lie about OS) - patches being written now, 5 minutes ago :) so I would expect 59 to resolve this problem. Would be nice if they backport to 58 since it's a pretty simple patch IMO (its just the UA spoof)

**Comment by collinbarrett** [comment]
Awesome! Thanks for the update.

**Comment by Thorin-Oakenpants** [comment]
```js
const SPOOFED_UA_OS = {
  linux: "X11; Linux x86_64",
  win: "Windows NT 6.1; Win64; x64",
  macosx: "Macintosh; Intel Mac OS X 10.13",
  android: "Android 6.0; Mobile",
  other: "Windows NT 6.1; Win64; x64",
};
```

@collinbarrett - if you set `privacy.resistFingerprinting` to false, and are not using a UA spoofer (eg in uMatrix or some extension) - what do you get for your UA bits on this test page - https://browserleaks.com/javascript <- just copy paste the stuff from user_agent to oscpu (it's 11 lines)

**Comment by pyllyukko** [comment]
> @pyllyukko - I am trying to post a reply to #14 and for some reason my posted comments never happen - almost as if I have been banned from that issue? I am allowed to type comments and preview, but when I click the comment button to post it, the comment field just clears and nothing happens. Yup, I refreshed etc. Here is what I was trying to post

That's weird! I don't see anything on the issue, that would explain this. Could be a case of [blocking a user](https://help.github.com/articles/blocking-a-user-from-your-personal-account/)?

**Comment by collinbarrett** [comment]
@Thorin-Oakenpants will do [that test](https://github.com/pyllyukko/user.js/issues/360#issuecomment-356288164) when i get home to my mac tonight and let you know.

**Comment by Thorin-Oakenpants** [comment]
sorry for the OT, but that's weird @pyllyukko - I see nothing about being blocked in that list, you own the repo :puzzled-face: ...  could yu edit the post or mention that the method doesn't require **root access**, which is why I mentioned it

**Comment by collinbarrett** [comment]
@Thorin-Oakenpants with resistFingerprinting = false : 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0`

**Comment by Thorin-Oakenpants** [comment]
^^thanks - I guess they'll have to remember to keep updating the OSX version number (I don't have a mac, but this interests me). Not that it really matters if all RFP+Mac users are the same

**Comment by pyllyukko** [comment]
> sorry for the OT, but that's weird @pyllyukko - I see nothing about being blocked in that list, you own the repo :puzzled-face: ... could yu edit the post or mention that the method doesn't require root access, which is why I mentioned it

Not in that list, but by CK, as he is the author of the issue? Not sure, but that is the only explanation I can come up with.

**Comment by pyllyukko** [comment]
Apparently this got resolved by Mozilla. Closing this now.
