### ISSUE TITLE
What does CIS mean?

### ISSUE THREAD

**Issue by TSleepingCat** [pyllyukko/user.js#361]
user.js file has prefs like

```javascript
// PREF: Enable Auto Notification of Outdated Plugins (Firefox < 50)
// https://wiki.mozilla.org/Firefox3.6/Plugin_Update_Awareness_Security_Review
// CIS Version 1.2.0 October 21st, 2011 2.1.2
// https://hg.mozilla.org/mozilla-central/rev/304560
user_pref("plugins.update.notifyUser",          true);
```
What does CIS mean?

**Comment by pyllyukko** [comment]
> What does CIS mean?

It stands for [Center for Internet Security](https://www.cisecurity.org/). They provide benchmarks (guides) for hardening various platforms, including Firefox. I used the The Center for Internet Security - Security Configuration Benchmark For Mozilla Firefox Version1.2.0 October 21st,  2011 as a reference in the initial user.js. The "2.1.2" refers to a certain section in the guide.
