### ISSUE TITLE
user.js breaks Github.com and Youtube.com

### ISSUE THREAD

**Issue by stablestud** [pyllyukko/user.js#362]
Hey there!

 First of all thanks for this awesome project, I do feel safe now.

However I encountered some issues I don't know how to fix myself:
* Youtube videos do load but after 3 seconds they are stopping and the screen goes black
* Github is missing some icons, also most things inside the Insights tab are not working (Traffic etc.) 

With or without add-ons it  doesn't want to work for me.

My add-ons:
* NoScript
* AutoDeleteCookies
* PrivacyBadger
* HTTPSEverywhere

Firefox (57.0.4) on Linux

**Comment by stablestud** [comment]
For the missing icons on Github I found the solution: `svg.disabled` must be set to `false`

**Comment by pyllyukko** [comment]
Can you see errors in the [console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console)? It does the same for me, when running FF 57.0.4 and there are some nasty looking errors in my console. Needs more investigation though.

**Comment by pyllyukko** [comment]
Are you sure ```svg.disabled``` doesn't fix the YouTube issue? See #323.

For me, it did stop the video, but toggling the SVG option made it work again.

**Comment by stablestud** [comment]
Refreshed my Firefox profile, this fixed it. Thanks
