### ISSUE TITLE
Verify certificate fingerprints

### ISSUE THREAD

**Issue by ghost** [pyllyukko/user.js#364]
From what little I understand, it is very easy to perform a man in the middle attack, if you are in the position to control trusted root certificates. In the past, I've seen several sites being monitored like that, by unknown persons, and there are reports that others have seen similar attacks.

Probably, most attacks are done by governments and large organizations who have the ability to generate trusted certificates for such monitoring to occur. But you never really know.

The only defence that I am aware of, is to check the certificate fingerprint and compare it to a previously stored fingerprint. This is similar to what ssh does with `~/.ssh/known_hosts` which stores public keys the first time you connect to a remote host via ssh. Any subsequent connections require a good match.

Is it possible to enable this functionality/feature in firefox, via user.js? (if it even exists...)

Thank you.

**Comment by nodiscc** [comment]
This is known as [Trust On First Use](https://en.wikipedia.org/wiki/Trust_on_first_use). It can be done ("pinning" known certificates manually) by using the [Certificate Patrol](https://addons.mozilla.org/en-US/firefox/addon/certificate-patrol/) addon, but in reality it really isn't practical, because many websites will use CDNs that will present different certificates on each session, short-lived certificates...

But it's worth trying it out for a few weeks, just to get an impression of what the Web would be without the current semi-broken PKI.

**Comment by jsmad** [comment]
the addon Certificate Patrol you mention above is not usable in the current version of firefox.

any other alternatives please?

**Comment by Atavic** [comment]
>Please note: This add-on for Firefox is not compatible with Firefox 57+, due to missing APIs from Mozilla.

https://github.com/sibiantony/ssleuth/ same with Calomel SSL Validation.

**Comment by Atavic** [comment]
>Please note: This add-on for Firefox is not compatible with Firefox 57+, due to missing APIs from Mozilla.

See: https://github.com/sibiantony/ssleuth/

Same with Calomel SSL Validation.

**Comment by pyllyukko** [comment]
Certificate Patrol is the only tool I have used for this task, but it is indeed getting a bit obsolete with no updates in a while.

Our project also has some [info/tools to limit the trusted CAs](https://github.com/pyllyukko/user.js/blob/master/CAs.md) to narrow down the possibility against these kind of attacks.

**Comment by Atavic** [comment]
So you'll either:

- stick with a working addon on a working browser version

- use an external tool, as Nmap script ssl-cert that retrieves a server's SSL certificate info.

**Comment by pyllyukko** [comment]
Not much we can do about this. If somebody knows a working plugin for this purpose, please let us know.
