### ISSUE TITLE
Values not copied from user.js to prefs.js

### ISSUE THREAD

**Issue by anchev** [pyllyukko/user.js#368]
I added 2 lines at the end of `user.js`:
```
user_perf("browser.startup.page", 0);
user_pref("general.warnOnAboutConfig", false);
```
However Firefox does not copy them to `prefs.js` and it seems the only way to set those is through `prefs.js`.

Any idea why this is happening? Should we report a bug to Mozilla or are there specific variables for which `user.js` setting doesn't work?

**Comment by pyllyukko** [comment]
At least this one has a typo:

> user_perf("browser.startup.page", 0);

**Comment by anchev** [comment]
Damn! Thanks :)
