### ISSUE TITLE
Search via address bar broken

### ISSUE THREAD

**Issue by hahanein** [pyllyukko/user.js#369]
For some time now default user.js is breaking search via address bar completely for me.

I type in "test" and hit enter and after a while the address in the address bar is changed to http://test/ and FF complains about having trouble finding that site.

I tried disabling `user_pref("keyword.enabled", false);` but that didn't do anything for me.

I'm on ubuntu 17.10 using FF 58.0

**Comment by Atavic** [comment]
Have you set that pref to true?

**Comment by hahanein** [comment]
I am and idiot.
