### ISSUE TITLE
CAs binary download for Desktop and Mobile version on releases page

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#37]
Is it possible to upload the trimmed binaries here on GitHub on the release page in order to download it from here? 

That would be very nice because I could write an script to catch always the latest version, the only stuff what I need is the SHA1. It would also help to implement this in an addon.

If that is somehow not possible it would be helpful to merge this within the project itself or add an separate folder for it. 

Edit:
If the format is the same one file should work for all platforms (confirmation needed). 

Thanks! :+1:

**Comment by pyllyukko** [comment]
> Is it possible to upload the trimmed binaries here on GitHub on the release page in order to download it from here?

You mean the ```cert8.db``` file? It might be possible, I'll need to look into that. It is true, that it would be easier to just use a ready made file in some circumstances.

**Comment by CHEF-KOCH** [comment]
Yupp and don't worry the script has still his place, in case someone want to made his own his own or mod things as per needs.

**Comment by CHEF-KOCH** [comment]
Seems on Android it's renamed to cert9.db, key4.db, I'm using the beta versions there, I not yet tested if it's generally renamed with FF 41/42 releases or if it's an Android only related feature. But the file format is still the same, I tried to remove them and use the ones from the project here and it works (except that the file names must be changed).

**Comment by nodiscc** [comment]
I think this can be closed for the following reasons:

 * Git is not adapted for storage and versioning of binary files (the repo will grow huge)
 * Binary files are not easily diffable or reviewable (whereas the script is transparent). I would not install someone else's binary cert db on my machine.
 * Most users are not interested in trimming their CA lists, following the [CA trimming guide](https://github.com/pyllyukko/user.js/blob/master/CAs.md) is more instructive, effectively puts the user in control (which is the point).
 * Trimming CA lists is a workaround, a well engineered system would not install untrusted certificates in the first place (eg. don't install the `ca-certificate` package on Linux systems, provide your own cert of certificates).

All in all I think it is an interesting idea but should be worked on in a separate project/repository.
