### ISSUE TITLE
FF new prefs "network.http.referer.defaultPolicy"

### ISSUE THREAD

**Issue by TriMoon** [pyllyukko/user.js#370]
See https://twitter.com/JonasWitmer/status/955101167037616129 😉 

In short 2 prefs:
  1. `network.http.referer.defaultPolicy`
  1. `network.http.referer.defaultPolicy.pbmode`

See also [Referrer-Policy@MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#Browser_compatibility), and [Bug 587523 - rename referer.userControlPolicy to referer.defaultPolicy](https://reviewboard.mozilla.org/r/213290/diff/1#index_header)

**Comment by fmarier** [comment]
`network.http.referer.XOriginTrimmingPolicy` and `network.http.referer.XOriginPolicy` (and `network.http.referer.spoofSource`) take precedence over these new prefs.

So for the purposes of this user.js, the new prefs aren't very useful.
