### ISSUE TITLE
[question] Why command line URL calling doesn't work?

### ISSUE THREAD

**Issue by ghost** [pyllyukko/user.js#371]
After applying the `user.js` the command
```
firefox -P "factory" --no-remote http://<something>
```
simply starts the browser with an empty tab and nothing loads. On a factory profile everything works as expected.

Which preference from this `user.js` is responsible for this behavior? I.e. what do I have to reset so that Firefox can open command line URL while still keeping the rest of the `user.js` settings?

**Comment by anchev** [comment]
*factory is the name of the profile I use because I reset it to factory settings and then put the `user.js` in the profile folder (a script does that).

**Comment by anchev** [comment]
I think I found it:
```
user_pref("privacy.clearOnShutdown.openWindows", true);
```
If I comment it or set it to `false` the URL opens as expected.
Is that supposed to be like that? The name of the setting doesn't quite say anything about it.

**Comment by Atavic** [comment]
That preference means: *Clearing open windows on Firefox exit*.

Previously known bugs: https://github.com/pyllyukko/user.js/issues/288 
https://github.com/ghacksuserjs/ghacks-user.js/issues/99

**Comment by anchev** [comment]
Thanks for the extra info.

The problem which I describe here does not cause opening of 2 windows on startup in FF 58 (it does that only in TBB). Still - what has clearing of windows on exit to do with not opening the specified URL in command line? Am I missing something?

**Comment by Thorin-Oakenpants** [comment]
@anchev - the 2 prefs `*.openWindows` relate to session restore data. Session restore is linked/a-part-of FF starts. That's the connection AFAIK

**Comment by anchev** [comment]
Sounds like whole lotta mess.

**Comment by pyllyukko** [comment]
Related issue: #324

**Comment by pyllyukko** [comment]
Is this still happening with Firefox Quantum? (See https://github.com/pyllyukko/user.js/issues/324#issuecomment-429022445)

**Comment by pyllyukko** [comment]
Should be working now with recent versions of Firefox.
