### ISSUE TITLE
Double Firefox windows on Linux

### ISSUE THREAD

**Issue by sfroberg** [pyllyukko/user.js#375]
Hi.

The"user_pref("privacy.clearOnShutdown.openWindows", true);" caused double firefox processes to be
started on Gentoo 64-bit Linux and Firefox version 52.4.0

Commenting it out fixed things

**Comment by pyllyukko** [comment]
Yes it does. See:

* #292 
* #288 
* #308 
* <https://bugzilla.mozilla.org/show_bug.cgi?id=1334945>

**Comment by berrythesoftwarecodeprogrammar** [comment]
affects me too
- Windows 10
- Firefox ESR 52.8.0

thanks OP. I had to do this to fix it:
1. exit firefox
2. set `privacy.clearOnShutdown.openWindows` to false in user.js
3. run firefox (it will open 2 windows still)
4. exit firefox
5. comment out `privacy.clearOnShutdown.openWindows` in user.js
6. run firefox (it will be fine now)
