### ISSUE TITLE
Addons/Extensions not visible in FF 58.0.1

### ISSUE THREAD

**Issue by baxax** [pyllyukko/user.js#378]
After applying user.js in FF profile, all extensions become invisible in toolbar. When I move with cursor over the place where it should be -it's there, and name of extension pop-up, but there are no preferences and anything else from it...

**Comment by pyllyukko** [comment]
Which OS & FF version? Can you check whether changing ```svg.disabled``` makes any difference?

**Comment by baxax** [comment]
I think I have solution. The problem was "privacy.resistFingerprinting=true". Disabling this feature FF allows me to install updates and after I set it to TRUE again...Is it ok to do this way? It is 58.0.1 version and OS is Parrot OS (based on Debian)

**Comment by pyllyukko** [comment]
> Is it ok to do this way?

If it works, then of course. So after updating the plugins you haven't experienced this anymore?

**Comment by baxax** [comment]
No. After plugins were updated I'm not having these problems anymore...
