### ISSUE TITLE
[Talk] Canvas fingerprinting

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#38]
This thread is designed to talk about and find possible workarounds to handle the [canvas problem](https://en.wikipedia.org/wiki/Canvas_fingerprinting) (see also Readme.md  todo).

The sad news are that there is nothing much we can do without any bigger modifications. Canvas are more or less hard-coded into the Browser/HTML5/Headers to provide certain detection ability's. 

Research:
- [Font enumeration](http://www.lalit.org/lab/javascript-css-font-detect/)
- [akademie.dw.de](http://akademie.dw.de/digitalsafety/your-browsers-fingerprints-and-how-to-reduce-them/)
- [About canvas fingerprinting](http://www.propublica.org/article/meet-the-online-tracking-device-that-is-virtually-impossible-to-block)
- [Wikipedia article about canvas fingerprinting](https://en.wikipedia.org/wiki/Canvas_fingerprinting)
- [Tor patches](https://gitweb.torproject.org/torbrowser.git/tree/src/current-patches/firefox)
- [Tracking using ETags](https://en.wikipedia.org/wiki/HTTP_ETag#Tracking_using_ETags)
- [Evercookies](https://github.com/samyk/evercookie#browser-storage-mechanisms)
- [Academic research paper describing canvas fingerprinting (.pdf)](https://securehomes.esat.kuleuven.be/~gacar/persistent/the_web_never_forgets.pdf)
- [Partial database of websites that have used canvas fingerprinting](https://securehomes.esat.kuleuven.be/~gacar/sticky/index.html)
- [Browser test page](https://www.browserleaks.com/canvas)
- [PanOptiClick test page](https://panopticlick.eff.org/)
- [X-Forwarded-For](http://en.wikipedia.org/wiki/X-Forwarded-For)
- [HTTP header fields overview](http://en.wikipedia.org/wiki/List_of_HTTP_header_fields)
- [Fingerprinting can be performed against the NoScript whitelist](http://cseweb.ucsd.edu/~hovav/papers/mbys11.html)
- ISP/NSA use deep packages analyzers to identification the traffic (can also be done in almost real-time) [see WikiLeaks documents], encryption is the only solution but coasts more power and bandwidth, of course it's not always possible due lack of standard encryption protocols on the www and apps.  
- [Circuit Fingerprinting Attacks: Passive Deanonymization of Tor Hidden Services (.pdf)](http://people.csail.mit.edu/devadas/pubs/circuit_finger.pdf)
- [Critique Website traffic fingerprinting attacks](https://blog.torproject.org/blog/critique-website-traffic-fingerprinting-attacks)

Firefox (canvas.\* via about:config) (last checked on FF 41.0 B3):
- canvas.customfocusring.enabled;false
- canvas.filters.enabled;true (default false)
- canvas.focusring.enabled;true
- canvas.hitregions.enabled;false
- canvas.image.cache.limit;0
- canvas.path.enabled;true
- devtools.canvasdebugger.enabled;false
- gfx.canvas.azure.backends;direct2d1.1,direct2d,skia,cairo
- canvas.capturestream.enabled;false (since 41.0 B2)

What I've found that might work, well I can't say that it still works, but it should be:
- [Canvas blocker](https://github.com/kkapsner/CanvasBlocker) ([addon](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/)), has the ability to exclude pages
- Random Agent Spoofer which injects via scripts the canvas option, you can enable/disable or whitelist xyz site/browser profile, e.g. YouTube needs Canvas 
- AdBlock Plus / uBlock already may block certain aspects, e.g uBlock can block fonts 
- NoScript seems the strongest, it can block page fonts, ....
- VPN/I2P/Proxy
- Randomize the User Agent via RAS/uMatrix every xyz minutes
- Privacy Badger 1.0 disables third party domains that do this, similar to uBlock/uMatrix
- ....

**Comment by CHEF-KOCH** [comment]
CanvasBlocker recently got an update to v1.7.0. Imho still the best method since it's provides a whitelist function + other gimmicks that no other addon can handle.

**Comment by CHEF-KOCH** [comment]
Still no process, eat or die ... Not really understand why Mozilla not directly add an option in the privacy preferences. It's not against the addon but ... *sigh* ...  why make things more complicated as they really are.... ?

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH You may appreciate AntiCanvasFingerprinting.  See https://addons.mozilla.org/firefox/addon/anticanvasfingerprinting/

***"Instead of blocking JS-API, which is a fingerprint in itself, AntiCanvasFingerprinting creates a unique and persistent noise that hides your real canvas fingerprint."***

**Comment by licaon-kter** [comment]
CanvasBlocker can't be installed in Android Firefox 38 (say Orfox) but can be on Firefox 45.

**Comment by CHEF-KOCH** [comment]
Orfox is not maintained by Mozilla, it's from [guardian](https://github.com/guardianproject/Orfox). Tor or it's browser not need such things, it's [by design not allowed](https://www.torproject.org/projects/torbrowser/design/).

**Comment by licaon-kter** [comment]
Since I did not see any prompt ever (on Android), I thought it was not implemented.

**Comment by CHEF-KOCH** [comment]
You not see something on Android/w FF because [Canvas](https://developer.android.com/reference/android/graphics/Canvas.html) support is limited. Most pages detects your client version and then use a optimized mobile view, even if you switch to 'Desktop' you will not see it due the limitations. So the attack surface is general lower. That doesn't mean it not get's more stuff soon in newer Android versions but Mozilla will not adopt stuff which is may critical, and from my experience there are only 4 pages which hides stuff in Canvas, and this is blockable via uMatrix/uBlock/NoScript.

**Comment by Atavic** [comment]
@Gitoffthelawn anticanvasfingerprinting addon page is gone.

**Comment by Gitoffthelawn** [comment]
@Atavic Thanks for pointing that out.  That's really too bad.

**Comment by pyllyukko** [comment]
[967895 - Prompt (w/ Site Permission) before allowing content to extract canvas data (Tor 6253)](https://bugzilla.mozilla.org/show_bug.cgi?id=967895) 🎉
