### ISSUE TITLE
'Cipher suites' section prevents uBO from updating 3rd party filters in 32-bit IceCat

### ISSUE THREAD

**Issue by ghost** [pyllyukko/user.js#383]
STR:

1. Download and unpack:

https://ftp.gnu.org/gnu/gnuzilla/52.6.0/icecat-52.6.0.en-US.gnulinux-i686.tar.bz2

2. In profile dir: Delete prefs.js and copy pyllyukko's user.js
3. Start IceCat
4. Go to uBO's settings: 3rd party filters tab
5. Try to update (or simply click one list, e.g. 'uBlock filters - Annoyances')

####Expected
Filters should update.

####Actual
Waiting forever (and clicking on a list link shows an empty frame)

#### Workaround
Close browser, comment the lines in cipher suites section, delete prefs.js and run IceCat again.

I don't know why but when testing on openSUSE Leap 42.3 (64-bit IceCat) there is no issue. The problem appears only on a laptop with openSUSE Tumbleweed (32-bit OS and 32-bit IceCat).

Any idea what might be causing this weirdness?

**Comment by pyllyukko** [comment]
I seem to be unable to run the 32-bit version, as I don't have GTK+3 multilib version available. Could you capture TLS traffic originating from IceCat and provide that (as pcap)? The TLS handshake client hello & server response messages might provide more clues to what is happening.

**Comment by Atavic** [comment]
Most probably the update server uses TLS 1.3 while Firefox has: 

`security.tls.version.max = 3` (TLS 1.2) 

Try changing it to: `4` (TLS 1.3)

**Comment by pyllyukko** [comment]
Is this still happening?

**Comment by pyllyukko** [comment]
Closing this now.
