### ISSUE TITLE
intl.accept_languages - value capital letters

### ISSUE THREAD

**Issue by anchev** [pyllyukko/user.js#385]
I think that the value of this variable should be `"en-US, en"` ("US" in caps). Currently it is `"en-us, en"` (all lowercase).

I am not quite sure if and how much this is important but it should be detectable in web server logs.

**Comment by pyllyukko** [comment]
Related issues:

* #252 
* #253 
* #355

**Comment by Atavic** [comment]
I always install and use the Firefox english american version, where: 
The preference value is: `en-US, en`
while the HTTP header HTTP_ACCEPT_LANGUAGE is `en-us, en`(all lowercase).

**Comment by anchev** [comment]
I had a look at the related issues as well as at the standard:

https://tools.ietf.org/html/rfc7231#section-5.3.5

which in its turn relates to:

https://tools.ietf.org/html/rfc4647#section-2

which says:

> Language tags and thus language ranges are to be treated as case-insensitive: there exist conventions for the capitalization of some of the subtags, but these MUST NOT be taken to carry meaning. Matching of language tags to language ranges MUST be done in a case-insensitive manner.

IOW: in case the capitalized `US` provides better non-fingerprint-ability we should use that instead of `us`, i.e. if the default in FF is `US` then it makes sense to use that.

**Comment by pyllyukko** [comment]
> IOW: in case the capitalized US provides better non-fingerprint-ability we should use that instead of us, i.e. if the default in FF is US then it makes sense to use that.

I agree.
