### ISSUE TITLE
Removing libnssckbi.so no longer works

### ISSUE THREAD

**Issue by szepeviktor** [pyllyukko/user.js#390]
In FF 60 removing nssckb.dll (on Windows) fails: `SEC_ERROR_LIBRARY_FAILURE`
https://github.com/pyllyukko/user.js/blob/master/CAs.md

Please advise.
I use a separate instance of FF for banking.

**Comment by pyllyukko** [comment]
Seems to apply also to Linux version. Seems like something has changed regarding NSS. No advice to offer right away :frowning_face:

**Comment by szepeviktor** [comment]
Maybe the manufacturer can help: https://bugzilla.mozilla.org/show_bug.cgi?id=1464125

**Comment by nodiscc** [comment]
There is no mention of `nssckb.dll` in this project anymore. It may have been part of the "certificate authority cleanup" procedure which was dropped in https://github.com/pyllyukko/user.js/pull/514/files (but I cannot find any mention of it in this PR anyway).

I suggest closing this issue.

**Comment by pyllyukko** [comment]
> I suggest closing this issue.

Yep. The CA stuff was removed a while ago.

**Comment by szepeviktor** [comment]
Now I am forced to use Palemoon browser for banking as all CA-s could be removed be deleting `nssckbi.dll`

**Comment by pyllyukko** [comment]
Well good you found some solution. Maybe some day we'll revisit this "functionality", as I would like to have it also, but not in the near future.
