### ISSUE TITLE
twitch.tv videos

### ISSUE THREAD

**Issue by jlskdfjlas** [pyllyukko/user.js#391]
Hi, can anyone tell me what specifically I need to change so that twitch.tv works?  Thanks

**Comment by nodiscc** [comment]
Are there errors in your console (`Ctrl+Shift+K`) while loading the page?

**Comment by pyllyukko** [comment]
Started working for me with Firefox 60.2.1esr.

**Comment by pyllyukko** [comment]
@jlskdfjlas: Is this still happening?

**Comment by pyllyukko** [comment]
Taking that as a no.
