### ISSUE TITLE
Modular user.js instead of a monolith

### ISSUE THREAD

**Issue by szepeviktor** [pyllyukko/user.js#394]
Please consider storing setting in files corresponding to [What does it do](https://github.com/pyllyukko/user.js#what-does-it-do) sections, maybe [prefixed by numbers](https://github.com/pyllyukko/user.js/issues/103#issuecomment-172392112)

There may be a redundant monolithic user.js for convenience.

**Comment by nodiscc** [comment]
I personally prefer a single file, even for editing.

You raised https://github.com/pyllyukko/user.js/issues/103 about this and @pyllyukko replied

> Somehow I feel it's easier to keep them all in one. At least when it's still reasonable sized. When it exceeds some 1000+ lines or something like that, it might be better to split it, but at this point I think it's better all in one.

It has grown beyond 1000 lines but most of them are comments. Actually `curl https://raw.githubusercontent.com/pyllyukko/user.js/master/user.js | grep "^user_pref" | wc -l` reports `284` prefs. Comments in `user.js` are used to build https://github.com/pyllyukko/user.js/blob/master/README.md (`make whatdoesitdo`) which gives us the benefit of having all information in a single place (`user.js`)

> Since no one or only few people reading documents/comments it would help to get an cleaner overview

I prefer commented files. There is no point in reading the file without the comments. You can filter out comments with `grep -v "^//"`.

> A lot of stuff is obsolete/deprecated I highly suggest (as mentioned in other threads) to remove this first instead of 'split' it.

Obsolete entries (before Firefox 52 ESR) can be moved to `ignore.list`.

**Comment by szepeviktor** [comment]
OK.

I was bringing it up as many CSS (for example Bootstrap), JS , PHP, Python etc. project use small files and a build system to produce the big file in /dist.

**Comment by szepeviktor** [comment]
And it already has "sections".
