### ISSUE TITLE
Extensions missing images in their menus

### ISSUE THREAD

**Issue by pi99y** [pyllyukko/user.js#395]
Hi,
after installing the hardened profile I noticed **some extensions missing images in their menus** (see attached images below).

I tried disabling some preferences within user.js like the SVG and resist fingerprinting (since one of the open issues reports this as a solution to a similar problem) but to no avail.

I used a clean profile, tried reinstalling extensions... but I can't get it to work.
Removing user.js does not fix the problem, but reinstalling the browser & extensions does = so those extensions work with a fresh firefox without the user.js.

Problematic extensions: uBlock Origin 1.16.8, uMatrix 1.0.0
Other installed (but no problem): Privacy Badger version 2018.5.10, HTTPS Everywhere Version: 2018.4.11

Any suggestions? Thanks!

OS: Lubuntu 16.04.4 LTS
Firefox version: 52.8.0, ESR, 64bit from http://ppa.launchpad.net/mozillateam/ppa/ubuntu

![2018-06-01-112544_1280x1024_scrot](https://user-images.githubusercontent.com/10639257/40834758-f7dc453c-6591-11e8-8c6f-4d7be6eb3f31.png)
![2018-06-01-112522_1280x1024_scrot](https://user-images.githubusercontent.com/10639257/40834759-f8078238-6591-11e8-8304-909d53a3471d.png)

**Comment by Thorin-Oakenpants** [comment]
Limiting FF to your fonts `browser.display.use_document_fonts`=`0`, this means that when you need to display glyphs (also known as tofu - eg icon fonts), then FF must fallback to your set of limited fonts - when the PUA of the font ends up actually existing in your font, then you get a visual breakdown (normally you would see a hexadecimal symbol).

You solution (other than to allow all fonts) is to change the default font used. In ESR52.x this is Options>Content>Fonts & Colors>Advanced>Serif|Sans-serif|Monospace

I think the one you need to change is san serif to something like deja vu - I am not on linux - maybe @nodiscc can help, he had this issue and he's a nux user

**Comment by pi99y** [comment]
Ah great @Thorin-Oakenpants, thank you!

Changing the "Default Font" in about:preferences#content to "DejaVu Sans" fixed the problem!

Is the default font preference exposed to websites, does this make my browser fingerprint  slightly more unique? Thanks!

**Comment by Thorin-Oakenpants** [comment]
Your fonts can be detected, so yes: this would *probably* make you more unique - I have no idea what all the various linux packages for FF have as the font defaults

The good news: when they land [1336208](https://bugzilla.mozilla.org/show_bug.cgi?id=1336208) for use with privacy.resistFingerprinting, then you won't need to limit fonts (and the web will be a little prettier (or hideous depending on your view))

The bad news: its taking ages to land that Tor Uplift FP patch, and it won't apply to ESR60.x

**Comment by pi99y** [comment]
I see... Thanks for all the help! Meanwhile I can live with the workaround. :)

**Comment by Atavic** [comment]
Solved... Closed?
