### ISSUE TITLE
New IndexedDB each time?

### ISSUE THREAD

**Issue by Ratator** [pyllyukko/user.js#397]
Hello everybody

I would like to ask carefully:

Is there a way for Firefox to create a new profile each time I launch it? So there is no need to delete IndexedDB, I assume, since it will be recreated anyway.
If so, is this user.js more or less obsolete?

The goal is that I create a new Firefox profile for each website. Bookmarks can be synced with your own Firefox Sync server.

I already know that Firefox has developed an add-on "Firefox Multi-Account Containers". ~~You can not trust the Mozilla community.~~ For example, "Firefox Focus" is suspected of collecting data.

Thank you very much!

Best regards

**Comment by pyllyukko** [comment]
> Is there a way for Firefox to create a new profile each time I launch it? So there is no need to delete IndexedDB, I assume, since it will be recreated anyway.
> If so, is this user.js more or less obsolete?

I guess you could create a launcher script that does something like that. Or at least remove the profile dir afterwards, so a new one will be created the next time.

No, it wouldn't make this project obsolete, as a new profile will launch with all the not-good default settings, which is the whole idea of this project to tweak those settings.

**Comment by beerisgood** [comment]
@Ratator 
The Container addon works
and because Firefox Focus exist, the addon isnt crap.
Also why use Firefox if you dont trust them?

**Comment by Ratator** [comment]
Actually, I am concerned with IndexedDB. That was the reason for my question.
I have already read through and have not found a conclusion yet.
Should I now manually delete IndexedDB? Or. in Windows 10 confidently delete this folder?

C:\Users\<username>\AppData\Roaming\Mozilla\Firefox\Profiles\<profilename>\storage

Thank you very much for your feedback.

@beerisgood 
That was not no disrespect intended. And I like to take my statement back.
