### ISSUE TITLE
Facebook messenger not working

### ISSUE THREAD

**Issue by atollkuci** [pyllyukko/user.js#399]
With user.js installed (both hardened and relaxed versions), Facebook messenger does not work. I get an error:

ErrorUtils caught an error: "c is undefined". Subsequent errors won't be logged; see https://fburl.com/debugjs.
Hi3FxrIZRtp.js:60:6239

**Comment by pyllyukko** [comment]
That's weird. I use FB with the relaxed version and haven't experienced any issues. Are you using some add-ons that might cause problems?

How does it not work exactly?

**Comment by atollkuci** [comment]
When I click on the name of a person nothing happens. The first time it seems that the message window is displayed for a fraction of a second and then disappears. 

When I click on messenger, the page remains blank, as shown
![here](https://user-images.githubusercontent.com/21968769/41845015-8a0d4ec4-7861-11e8-9868-b472f93ae746.JPG)

I did disable all plugins, and the behavior is the same. Firefox version is 60.0.2 (64 bit)

**Comment by savyajha** [comment]
Try going to `about:serviceworkers` and deleting all serviceworkers. It corrected something similar on another site for me.

**Comment by atollkuci** [comment]
I get a message:

`Service Workers are not enabled.`

**Comment by savyajha** [comment]
Well, maybe try enabling them, then? Maybe messenger doesn't work without them.

`user_pref("dom.serviceWorkers.enabled", true);` ought to do it.

**Comment by atollkuci** [comment]
I enabled them, but still the same behavior. Now in "about:serviceworkers" I get:

![fb sw](https://user-images.githubusercontent.com/21968769/41923940-1551fdec-7969-11e8-876e-5f2225f7397a.JPG)

**Comment by savyajha** [comment]
Can you report the same with a fresh profile? Go to `about:profiles`, make a fresh profile and add the `user.js` (both strict and relaxed) and see if the behaviour persists?

**Comment by atollkuci** [comment]
Yes, it's the same with a fresh profile with both versions

**Comment by pyllyukko** [comment]
So I was able to reproduce this (with non-ESR Firefox). Didn't find any quick fixes for this and need to investigate more.

**Comment by pyllyukko** [comment]
It's ```svg.disabled```.
