### ISSUE TITLE
datareporting.* preferences to document

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#400]
From https://github.com/MrAlex94/Waterfox/blob/master/toolkit/components/telemetry/datareporting-prefs.js

```js
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// pref("datareporting.policy.dataSubmissionEnabled", false);
pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "0");
pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 0);
pref("datareporting.policy.dataSubmissionPolicyBypassNotification", false);
pref("datareporting.policy.currentPolicyVersion", 2);
pref("datareporting.policy.minimumPolicyVersion", 1);
pref("datareporting.policy.minimumPolicyVersion.channel-beta", 2);
pref("datareporting.policy.firstRunURL", "https://www.mozilla.org/privacy/firefox/");
```

**Comment by Atavic** [comment]
Do you mean official docs? By searching for *datareporting.policy* on https://github.com/mdn
I get no results. Otherwise I have disabled it with no issues.

**Comment by Atavic** [comment]
From the bottom up of the list, on 1st run you may see the Privacy Notice:

> Firefox by default shares data to...

Mozilla may change that page, so they track which version you have seen.

Also see: https://bugzilla.mozilla.org/show_bug.cgi?id=1195552#c4

**Comment by nodiscc** [comment]
https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/internals/preferences.html

`datareporting.policy.dataSubmissionEnabled`

>This is the data submission master kill switch. If disabled, no policy is shown or upload takes place, ever.

https://github.com/pyllyukko/user.js/blob/master/user.js#L545
