### ISSUE TITLE
security.tls.version.max = 4 is undocumented

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#401]
Ref https://github.com/pyllyukko/user.js/pull/206

https://github.com/pyllyukko/user.js/blob/master/user.js#L996 Values of 1 and 2 are documented, but not 3 and 4.

https://kb.mozillazine.org/security.tls.version only lists values of 0-3 as valid, https://www.bleepingcomputer.com/news/security/mozilla-has-started-gradually-enabling-tls-13-in-firefox/ from April 12, 2018 states that a value of 4 allows for TLS 1.3.

It would also be good to find official Mozilla documentation about this setting.

**Comment by Atavic** [comment]
mozillazine mainpage was last modified 10:54, 22 October 2014

https://bugzilla.mozilla.org/show_bug.cgi?id=1442042#c64
https://support.mozilla.org/en-US/questions/1198543

**Comment by pyllyukko** [comment]
BTW. ```4``` [seems to be the default](https://searchfox.org/mozilla-central/source/security/manager/ssl/security-prefs.js#6) for ```max``` nowadays.
