### ISSUE TITLE
More Waterfox preferences to review/document

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#403]
https://github.com/MrAlex94/Waterfox/blob/master/modules/libpref/init/all.js might have some preferences not listed here, either in user.js or ignore.list

**Comment by pyllyukko** [comment]
That's a lot of settings! :open_mouth:

**Comment by nodiscc** [comment]
It's not necessary to add everything here, but an comparison target in the Makefile [[1](https://github.com/pyllyukko/user.js/issues/256#issuecomment-297441375)] would be a great tool to refine user.js and find undocumented prefs that may be have a security impact. Something like

```make
$ cat Makefile
# Arbitrary URL to compare your user.js against
COMPARE_TARGET='https://github.com/MrAlex94/Waterfox/blob/master/modules/libpref/init/all.js'

compare:
[...]
```

```sh
$ make compare
[info] local 'user.js' will be compared against https://github.com/MrAlex94/Waterfox/blob/master/modules/libpref/init/all.js
[info] found 71 ignored preferences
[info] found 15 preferences with common values
[info] found 21 preferences with different values
[info] found 25 unknown preferences (not listed in 'user.js' or 'ignore.list'):
pref("browser.autofocus", true);
pref("browser.send_pings.max_per_link", 1);
pref("browser.helperApps.alwaysAsk.force", false);
...
```

So yes this actually should be in https://github.com/pyllyukko/user.js/issues/256

**Comment by Atavic** [comment]
> [info] found 15 preferences with common values
[info] found 21 preferences with different values

That's flawed, as MrAlex94 did some double entries, like:

```
// Enable Performance Observer API
#ifdef NIGHTLY_BUILD
pref("dom.enable_performance_observer", true);
#else
pref("dom.enable_performance_observer", false);
#endif
```

**Comment by nodiscc** [comment]
I'm no longer working on this.
