### ISSUE TITLE
Lesspass, "We are sorry the copy only works on modern browsers"

### ISSUE THREAD

**Issue by brakenow** [pyllyukko/user.js#405]
How to fix that?

**Comment by pyllyukko** [comment]
Do you mean [this add-on](https://addons.mozilla.org/en-US/firefox/addon/lesspass/)?

**Comment by pyllyukko** [comment]
Which Firefox version are you using? I did a quick test with my ESR & Quantum 61.0.1and it seems to install & run correctly.

**Comment by brakenow** [comment]
Thank you! I'm using Firefox 61.0 too. It's clicking the copy icon for the generated password that doesn't work.

**Comment by pyllyukko** [comment]
Try setting ```dom.allow_cut_copy``` -> ```true```.

**Comment by brakenow** [comment]
Thank you, but I decided to stay with KeepassXC.
