### ISSUE TITLE
how is this benchmark able to run with config entries set to block them?

### ISSUE THREAD

**Issue by jawz101** [pyllyukko/user.js#406]
https://pspdfkit.com/blog/2018/a-real-world-webassembly-benchmark/
direct link https://pspdfkit.com/webassembly-benchmark/

This benchmark is supposed to test webassembly rendering of a pdf.

If I set `javascript.options.wasm = false` it falls back to asm.js and if I set `javascript.options.asmjs = false` it still runs.

Developer Tools > Web Console shows that webassembly does respond to the wasm preference however the asmjs pref doesn't disable the test.

I try to block both because nothing on the web uses these technologies yet except for crypto miners.

**Comment by Atavic** [comment]
You seem to fall back to a baseline, like [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1433425).

**Comment by pyllyukko** [comment]
Thanks, @Atavic. That indeed seems to be the case. Closing this issue.

**Comment by jawz101** [comment]
That's very interesting.  You have an eagle eye @Atavic
