### ISSUE TITLE
2-step verification Gmail not working

### ISSUE THREAD

**Issue by brakenow** [pyllyukko/user.js#407]
Hi!

Getting "Your sign-in attempt timed out. Resend the notification to try again." when trying to log in using my phone. Also happens with the relaxed branch. Works fine with Chromium.

**Comment by pyllyukko** [comment]
> trying to log in using my phone

So this is Firefox in Android?

**Comment by pyllyukko** [comment]
Can you describe the issue in more detail? As in steps you take and at which point it fails. I try to avoid using Google services, so I don't have the possibility to reproduce this.

**Comment by brakenow** [comment]
I avoid Google too, as of now.

**Comment by Atavic** [comment]
You surely need javascript. Entries like:
*dom.workers.enabled* 
*dom.netinfo.enabled* 
*dom.event.clipboardevents.enabled*
Should be set as true, 2nd one is for the login attemps monitoring feature.

Can't say if it's enough.
