### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by mrtargaryen** [pyllyukko/user.js#409]
Does this work with Firefox Quantum 62.0b12 ?

I tried to verifying as per the instructions:

"Verifying

Verify that the settings are effective from about:support (check the "Important Modified Preferences" and "user.js Preferences" sections)."

However, those search terms do not appear. I also searched for certain settings that appear not to be in this version of Firefox. 

Thanks.

**Comment by Atavic** [comment]
An old and safe option is to type: *about:config*

and look at the entries in **bold text**, that means that the entries have been modified from their default value.
Scroll down and the first entry in bold should be: *app.shield.optoutstudies.enabled*

If this entry (or ant other that's listed in the user.js) is not in its default state, then the modifications have been applied.

**Comment by mrtargaryen** [comment]
@Atavic Ok, I will check, thank you.

**Comment by mrtargaryen** [comment]
@Atavic It works, but in quantum it doesn't have all the options that other versions have.
