### ISSUE TITLE
New OCSP timeout preferences

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#413]
https://hg.mozilla.org/mozilla-central/rev/d0e27739f475 introduces preferences to control the timeouts of OCSP soft/hard fails:

```
+pref("security.OCSP.timeoutMilliseconds.soft", 2000);
+pref("security.OCSP.timeoutMilliseconds.hard", 10000);
```

**Comment by beerisgood** [comment]
Why would you change something like that?

**Comment by Atavic** [comment]
There have been past issues when servers were slow on response.

**Comment by Atavic** [comment]
See: https://github.com/pyllyukko/user.js/issues/321#issuecomment-310722532

**Comment by pyllyukko** [comment]
I don't think we want to touch these.
