### ISSUE TITLE
GRC DNS Spoofability Test broken

### ISSUE THREAD

**Issue by theltalpha** [pyllyukko/user.js#417]
Hallo!

I am trying to run Gibson Research Corporation's DNS Spoofability Test (https://www.grc.com/dns/dns.htm, hit the button "Initiate Standard DNS Spoofability Test" at the bottom of the page). It fails and says it doesn't find any DNS servers. Well, this seems logical to me, because it uses a zero-size gif (webbug) to find the DNS servers used by your system. But which settings in user.js do I have to temporarily edit in order to be able to run the test?

**Comment by beerisgood** [comment]
Must be a new change. Works always in past without problems

**Comment by pyllyukko** [comment]
Looking at the test and the GIF URLs, they don't seem to work at all. Doesn't resolve. So the test is broken.

Links to the broken URLs:

* gznwdz3oodksl.dns.grc.com/gznwdz3oodksl.gif
* 0rt5aaltbkfaf.dns.grc.com/0rt5aaltbkfaf.gif
* 1f1gjfjidiueg.dns.grc.com/1f1gjfjidiueg.gif
* 0b3enxvibecwf.dns.grc.com/0b3enxvibecwf.gif

Case closed.
