### ISSUE TITLE
privacy.resistFingerprinting breaks WhatsApp Web

### ISSUE THREAD

**Issue by pyllyukko** [pyllyukko/user.js#420]
At least with Firefox 60.2.0esr, WhatsApp Web displays an empty 264x264 image in the place where the QR code should be when ```privacy.resistFingerprinting``` is enabled.

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1446472

**Comment by Thorin-Oakenpants** [comment]
^^ I assume you should be able to just apply a canvas exception to that domain
