### ISSUE TITLE
Why disable Webassembly?

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#421]
https://github.com/pyllyukko/user.js/commit/5b9aac0b46c47a52fad4310fd465a48592d647d0 has no details on what Webassembly is/does and its security implications. I could find these links but it would be good to detail a bit more the reason why it was disabled, and what it could break

 - http://fossforce.com/2017/03/webassembly-comes-firefox/
 - https://www.infoworld.com/article/3291780/web-development/what-is-webassembly-the-next-generation-web-platform-explained.html
- https://en.wikipedia.org/wiki/WebAssembly

**Comment by Atavic** [comment]
What is disabled are optimizations only, used by a few tools, like cryptominers.

See the bugzilla linked here: https://github.com/pyllyukko/user.js/issues/406#issuecomment-404980086

**Comment by nodiscc** [comment]
https://github.com/pyllyukko/user.js/commit/30bebdc89a0bfa6880cbb949c014fe67a82055dd

**Comment by ScottRFrost** [comment]
+2 years.

This may need another look, especially on the relaxed build in light of new technologies like Blazor that are making it very simple for people to create WebAssembly sites.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/issues/1037#issuecomment-708092814

subsequent user.js edit
```js
/* 2422: disable WebAssembly [FF52+]
 * Vulnerabilities have increasingly been found, including those known and fixed
 * in native programs years ago [2]. WASM has powerful low-level access, making
 * certain attacks (brute-force) and vulnerabilities more possible
 * [STATS] ~0.2% of websites, about half of which are for crytopmining / malvertising [2][3]
 * [1] https://developer.mozilla.org/docs/WebAssembly
 * [2] https://spectrum.ieee.org/tech-talk/telecom/security/more-worries-over-the-security-of-web-assembly
 * [3] https://www.zdnet.com/article/half-of-the-websites-using-webassembly-use-it-for-malicious-purposes ***/
user_pref("javascript.options.wasm", false);
```

**Comment by pyllyukko** [comment]
<https://twitter.com/SkelSec/status/1346517626026123268>
