### ISSUE TITLE
OpenVAS

### ISSUE THREAD

**Issue by g0rbe** [pyllyukko/user.js#422]
The config make OpenVAS unusable.
Screenshot:

![screenshot at 2018-09-30 01-52-14](https://user-images.githubusercontent.com/36860942/46251601-86048c80-c446-11e8-9281-a18b72acf528.png)

**Comment by nodiscc** [comment]
Any warnings in the browser console when opening this page?

**Comment by g0rbe** [comment]
This was errors:
![screenshot at 2018-09-30 20-09-54](https://user-images.githubusercontent.com/36860942/46260924-0d500f80-c4dc-11e8-852d-5fcee4bdb4a3.png)
I forget to check this, but it gave the solution.
Set back the svg related options:

`gfx.font_rendering.opentype_svg.enabled true`
`svg.disabled false`

Now work like a charm, thanks 😃

**Comment by pyllyukko** [comment]
Disabled SVG and website breakage starts to be so common, that I'm slowly considering commenting out the setting.

**Comment by Atavic** [comment]
^ OK for trusted sites or tools like OpenVAS, but maybe not for an hardened user.js version.
