### ISSUE TITLE
http basic auth credentials prompted every new tab.

### ISSUE THREAD

**Issue by nidhhoggr** [pyllyukko/user.js#425]
I am using a proxy connection that requires http basic auth credentials to connect to via the firefox manual http proxy connection.
Every different domain name that I haven't yet previously provided http basic auth credentials for, I am prompted for the credentials. The default behavior is to automatically connect using the basic auth credentials initially provided for every subsequent domain requested. 
I have tried toggling the following settings to false yet am still prompted to provide credentials:
```js
user_pref("browser.fixup.hide_user_pass", false)
```
```js
user_pref("browser.privatebrowsing.autostart", false)
```

Which other settings would I need to configure in order to restore this default behavior?

**Comment by nidhhoggr** [comment]
The answer is to disable isolation of fir party domain:
https://bugzilla.mozilla.org/show_bug.cgi?id=1301523
```js
user_pref("privacy.firstparty.isolate", false)
```

**Comment by nodiscc** [comment]
@nidhhoggr Please reopen this so that a NOTICE can be added for `privacy.firstparty.isolate`

```
// NOTICE: First-party isolation causes HTTP basic auth to ask for credentials for every new tab```

**Comment by pyllyukko** [comment]
@nodiscc: Good catch! Fixed now. Thanks!
