### ISSUE TITLE
[FYI] Mozilla is going to remove support for RSS feeds

### ISSUE THREAD

**Issue by Atavic** [pyllyukko/user.js#426]
From Firefox 64 onwards, RSS and Atom feed support will be handled via webextensions.

> We’ve concluded that it is no longer sustainable to keep feed support in the core of the product.

[Source](https://www.gijsk.com/blog/2018/10/firefox-removes-core-product-support-for-rss-atom-feeds/)

**Comment by nodiscc** [comment]
I use an external reader ([tt-rss](https://tt-rss.org/)) and this addon: https://addons.mozilla.org/en-US/firefox/addon/awesome-rss/

**Comment by Atavic** [comment]
Yes, I still use Seamonkey for RSS, but I see it as another bad choice by mozilla.

Closed for avoiding an over-encumbered issues list.
