### ISSUE TITLE
Favicons fetching icons only when there is internet connection, never from cache.

### ISSUE THREAD

**Issue by user9321w** [pyllyukko/user.js#427]
Basically for someone that has a hundred tabs open, every time firefox is opened without an internet connection, favicons on those hundreds of tabs are not loaded. They are only loaded when having an internet connection and then start up firefox.

Why is this? and is this calling home to each and every site every time firefox is opened?
Shouldnt this work from favicons cache if there is one?
Is there a setting in user.js that i can configure to stop calling home everytime?  i have not seen one.

**Comment by pyllyukko** [comment]
Try ```browser.shell.shortcutFavicons```. I guess it's indeed a caching issue, as we try to avoid storing stuff on disk.

**Comment by pyllyukko** [comment]
Can you describe the situation more precisely? With user.js you shouldn't have any tabs open when you start Firefox, so I'm not sure I understand the scenario.

**Comment by user9321w** [comment]
@pyllyukko Im not using the full user.js file, just a few options from it.

Im saying that If i have many tabs, like 100 or so. and when I close firefox and then open it again, i get the tabs that i was working on. all those tabs, get their favicons from the internet only if you are connected. it will lag a bit at first but then all icons on the tabs will appear.

However, if you cut the connection and you start up firefox with those many tabs you had, those favicons wont show.  ive been noticing this for quite a while now so i just wanted to know if there is an option to disable favicons from getting their icons from the internet every single time the browser starts, since it doesnt seem like they get their icons from any cache.

If i open a fresh installed firefox and open 10 tabs with different sites, this time it won't need an internet connection to get the icons. So either my cache where the favicons are stored are corrupt since i have kept the 100 tabs throughout many releases and never refreshed firefox. Or somehow they call home when you have over 50 tabs.

**Comment by Atavic** [comment]
> ...a hundred tabs open

You have waived goodbye to any minimal possibility of privacy there. Clearing browsing history also clears Favicons. Even if you don't clear history, favicons aren't stored in cache. The site's servers should create  a specific rule for ico files, like adding a rule in .htacces for Apache webserver. This rule does not exist by default. There's a related discussion [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/48).

**Comment by user9321w** [comment]
@Atavic Ok can you explain why ive waived goodbye to any privacy while having so many tabs open?  Is it because of what i assumed in my first post? the fact that firefox is sending a request to every site tab when firefox is opened?

**Comment by pyllyukko** [comment]
Ok. Sounds like some caching issue probably. Can't tell straight away which setting could affect this. Also, we can't help you unless we can reproduce the issue, so can you post your user.js somewhere (e.g. as a gist or pastebin)?

**Comment by Atavic** [comment]
@user9321w While you have many tabs opened and you accept only 1st party cookies, [cookie-synching](https://robertheaton.com/2017/11/21/cookie-syncing-how-online-trackers-talk-about-you-behind-your-back/) happens. [Here](https://freedom-to-tinker.com/2014/08/07/the-hidden-perils-of-cookie-syncing/).
the 2nd image is a graph that shows what happens when *a user visits several hundred of the top Alexa sites*.

**Comment by Atavic** [comment]
Well, I assume you have actual pages loaded into the tabs... otherwise do you keep all those tabs as bookmarks?

BTW Favicons requests also send/receive cookies.

**Comment by Atavic** [comment]
Also Favicons are present in the [GUI](https://github.com/ghacksuserjs/ghacks-user.js/issues/88).

**Comment by user9321w** [comment]
So after cleaning up a few tabs and the latest version of Firefox 63.0, it seems as if the cache is working now and doesn't even lag when first opening Firefox anymore. The favicons display even when there is no internet connection.
For some reason i think it was the Firefox update that fixed this.

**Comment by pyllyukko** [comment]
Good to head that it's working now. Closing this issue.
