### ISSUE TITLE
[FYI] Mozilla is going to have a partnership with a VPN provider

### ISSUE THREAD

**Issue by Atavic** [pyllyukko/user.js#429]
Mozilla meet up with a Swiss VPN provider named ProtonVPN to offer a premium VPN service.
Seems like a follow-up to what Opera did before. To me a VPN is useful for trespassing censorship, like the China Great Firewall. I'll never pay to such premium service inside a browser.
To me it's a loss of privacy, you have to blindly trust this VPN service: there are various cases about the lies of such services.

**Comment by Atavic** [comment]
Technically Opera uses a simple proxy. Another kind of in-browser locking feature is used by Yandex Browser and Comodo Icedragon (DNS Server). Although interesting, such features can be used locally and at system level, avoiding leaks and using audited open source tools.

**Comment by pyllyukko** [comment]
<https://blog.mozilla.org/futurereleases/2018/10/22/testing-new-ways-to-keep-you-safe-online/>

**Comment by Atavic** [comment]
OK, so it's an experiment for US based users.
