### ISSUE TITLE
twitch.tv is broken

### ISSUE THREAD

**Issue by steamp0rt** [pyllyukko/user.js#430]
Using `relaxed` user.js. Firefox 63.0 64-bit. Windows 10 LTSC 2019, version 17763.55. No errors in console. Audio works, but the player is just all black.

![capture](https://user-images.githubusercontent.com/25724666/47688942-8926a000-dbdf-11e8-9046-b2f785f460fa.PNG)

Addons: 
![capture](https://user-images.githubusercontent.com/25724666/47688857-21705500-dbdf-11e8-96a5-752ce35dd8cf.PNG)

Youtube works fine.

**Comment by pyllyukko** [comment]
Related issue: #391

**Comment by bogachenko** [comment]
why are you sure this is because of the `user.js` file but not because of the expansion or subscription for the ad blocker? did you check the `user.js` file on the new firefox profile (no extensions)?

**Comment by pyllyukko** [comment]
@steamp0rt: Can you confirm it's user.js and not some addon? @bogachenko said in another issue (https://github.com/pyllyukko/user.js/pull/431#issuecomment-438423668) that it works for him and it works on my Firefox 60.3.0esr (although I'm using Linux).

**Comment by steamp0rt** [comment]
Works now for some reason. Dunno why.

**Comment by pyllyukko** [comment]
Good to hear that. I'll close this then.
