### ISSUE TITLE
Check Librefox Firefox, this or that option could interest this project... 

### ISSUE THREAD

**Issue by intika** [pyllyukko/user.js#433]
Hi, 

First of all thank you a lot for your amazing work ! 
I just published my personal gathered tuned settings for firefox... 

https://github.com/intika/privafox-firefox

**Privafox-Firefox :** Tuning firefox settings (about:config) for a better security, privacy and performances. Firefox does not need to be rebuilt to be cleaned from privacy/security issues; as all settings can be changed in the about:config This project aim to fix security/privacy issues related to firefox and also tune it to gain some speed performances.
It uses mozilla.cfg and policies.json to have the changes applied to firefox... 

This could be useful to may be pick-up some stuff from it. for user.js project :)

;)

**Comment by intika** [comment]
I will let you know for important changes if there is, as i did with ghacks ;)

**Comment by pyllyukko** [comment]
Thanks! Much appreciated :relaxed:
