### ISSUE TITLE
Google reCAPTCHA issue

### ISSUE THREAD

**Issue by brakenow** [pyllyukko/user.js#437]
Hi!

Without relaxed user.js it only takes one recaptcha, but with I have to do many to succeed, but still not OK, so I have to do one more, and one more, and...

**Comment by Atavic** [comment]
Maybe recaptcha can use beacons and asks the browser to send pings:

> beacon.enabled
browser.send_pings

**Comment by brakenow** [comment]
Thanks! Will try.

**Comment by Atavic** [comment]
Same as the previous 2 messages for me.

**Comment by ganego** [comment]
> Why don't you have a Google cookie, citizen

Google cookie won't help you.
I'm logged in with my google account, but after one or two captchas - oftentimes for the first one - I get several captchas, sometimes up to 10 or so.

**Comment by Atavic** [comment]
@brakenow See: https://github.com/dessant/buster

**Comment by nicoulaj** [comment]
I found that I had to disable this one on the relaxed profile, or I am sent to "captcha infinite loop" on several french sites like <https://www.fnac.com>:
```
// Set Accept-Language HTTP header to en-US regardless of Firefox localization
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
pref("intl.accept_languages", "en-US, en");
```
Obviously Google detects a language mismatch somehow (which is weird because all my locale variables are set to en_US and Firefox is in english).

**Comment by pyllyukko** [comment]
I'm closing this, as the CAPTCHA is technically working and it's only Google bullying us.
