### ISSUE TITLE
Some features are only available as GPOs/Policies

### ISSUE THREAD

**Issue by szepeviktor** [pyllyukko/user.js#438]
Some setting moved to [policies,](https://github.com/mozilla/policy-templates) e.g. disabling updates

```json
{
  "policies": {
    "DisableAppUpdate": true
  }
}
```

**Comment by Atavic** [comment]
Related to https://github.com/pyllyukko/user.js/issues/389

**Comment by pyllyukko** [comment]
Indeed. We will consider these settings if/when we'll expand to hardening policies.
