### ISSUE TITLE
Cloudflare's Trusted Recursive Resolver

### ISSUE THREAD

**Issue by billux** [pyllyukko/user.js#439]
Hi,

Firefox 60 now provides DNS over HTTPS resolver mechanism, but this feature uses Cloudflare's resolvers by default and thus all DNS request are sent to Cloudflare. This is obviously more secure because domain names aren't sent in plain text over the network but in the other hand Cloudflare now has access to all your visited domain names.

For now this feature is disabled by default but it can be set in a way that it won't be enabled in future release:

```
    user_pref("network.trr.mode", 5);
```

I think it is worst at least mentioning it in the user.js file (commented out), so users will be aware about that feature and turning it on or off depending on their choice.

https://wiki.mozilla.org/Trusted_Recursive_Resolver

Thanks!

**Comment by pyllyukko** [comment]
Thanks! I'll add it to user.js
