### ISSUE TITLE
Disable "recommend extensions as you browser" feature

### ISSUE THREAD

**Issue by jackTaw88** [pyllyukko/user.js#446]
Hi,

On firefox 65 (linux) I saw a feature:

Preferences > general > Browsing > recommend extensions as you browse

Details:
https://support.mozilla.org/en-US/kb/extension-recommendations?as=u&utm_source=inproduct

I there any option on user.js to disable that? I don't know how it works but I think firefox should show extensions by asking the server every time we visit a web site...

Thank you

**Comment by Thorin-Oakenpants** [comment]
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr", false);

**Comment by Thorin-Oakenpants** [comment]
PPS: don't confuse that with another one in 65+

[NOTE] This pref has no effect when Health Reports (0340) are disabled
[SETTING] Privacy & Security>Firefox Data Collection & Use>...>Allow Firefox to make personalized extension rec.
[1] https://support.mozilla.org/kb/personalized-extension-recommendations ***/
user_pref("browser.discovery.enabled", false);

**Comment by jackTaw88** [comment]
@Thorin-Oakenpants you mean both:

user_pref("browser.discovery.enabled", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr", false);

are local ? and not use mozilla servers. And that is the reason to do not include them in user.js? Am I right?

**Comment by Thorin-Oakenpants** [comment]
> CFR is all local

I'm not sure on extension "discovery"

**Comment by pyllyukko** [comment]
> user_pref("browser.discovery.enabled", false);

At least the GUI button "Recommend extensions as you browse" doesn't disable that.

**Comment by polyzen** [comment]
> user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr", false);
> 
> edit: CFR is all local. This was added in FF64+
> PS: here's a link: [support.mozilla.org/en-US/kb/extension-recommendations](https://support.mozilla.org/en-US/kb/extension-recommendations)

What a convoluted pref name.. and now I am rather confused about `browser.newtabpage.` prefs as I had thought they only applied to `about:newtab`..

**Comment by Thorin-Oakenpants** [comment]
> 
> 
> > user_pref("browser.discovery.enabled", false);
> 
> At least the GUI button "Recommend extensions as you browse" doesn't disable that.

OK, lets make this a little clearer then

```js
/* disable CFR [FF64+]
 * [SETTING] General>Browsing>Recommend extensions as you browse ***/
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr", false);

/* disable Extension Recommendations [FF65+]
 * [NOTE] This pref has no effect when Health Reports (0340) are disabled
 * [SETTING] Privacy & Security>Firefox Data Collection & Use>...>Allow Firefox to make personalized extension rec.
 * [1] https://support.mozilla.org/kb/personalized-extension-recommendations ***/
user_pref("browser.discovery.enabled", false);
```

**Comment by pyllyukko** [comment]
I understood that it's the other way around.

* "Recommend extensions as you browse" -> `browser.newtabpage.activity-stream.asrouter.userprefs.cfr` ("[Beginning in Firefox version 65](https://support.mozilla.org/en-US/kb/extension-recommendations)")
* "Allow Firefox to make personalized extension recommendations" -> `browser.discovery.enabled`

**Comment by Thorin-Oakenpants** [comment]
see my 1st and 2nd posts which say exactly what I just posted, which is in our user.js, derived from our diffs per release.

1st post
> user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr", false);
> 
> edit: CFR is all local. This was added in FF64+
> PS: here's a link: https://support.mozilla.org/en-US/kb/extension-recommendations

The preference was ADDED in 64. The reference page is LYING!! heh. It *might* be correct in that the backend didn't get flipped on or something until 65, IDK. The link, if you scroll down says that the UI setting is "In the General panel, go down to the Browsing section".

In FF64, that UI setting is present. As is the pref. I can't provide an actual bugzilla because we couldn't find it
![cfr](https://user-images.githubusercontent.com/16656956/52398311-8249dc00-2ab0-11e9-9e3f-b2999adfd8bd.png)

2nd post
> PPS: don't confuse that with another one in 65+
> 
> [NOTE] This pref has no effect when Health Reports (0340) are disabled
> [SETTING] Privacy & Security>Firefox Data Collection & Use>...>Allow Firefox to make personalized extension rec.
> [1] https://support.mozilla.org/kb/personalized-extension-recommendations ***/
> user_pref("browser.discovery.enabled", false);

You don't need worry about this one because it's covered under the telemetry pref `datareporting.healthreport.uploadEnabled` which I **assume** you already set (can't be bothered looking, that's your job :) )

Hope that clears it up

**Comment by Thorin-Oakenpants** [comment]
bump: reminder: @pyllyukko since this has been closed or you've missed it, or forgotten about it - https://github.com/pyllyukko/user.js/commit/1b5dcc43faabefa9c20a8c0da0c649160df077c1 is FF64+, **not** FF65+

**Comment by pyllyukko** [comment]
> bump: reminder: @pyllyukko since this has been closed or you've missed it, or forgotten about it - [1b5dcc4](https://github.com/pyllyukko/user.js/commit/1b5dcc43faabefa9c20a8c0da0c649160df077c1) is FF64+, **not** FF65+

Haven't missed it. I think I'll still leave the "official" version of the story. Also, it's really a minor detail and doesn't matter that much. Thanks for the input still 😊

**Comment by Thorin-Oakenpants** [comment]
no worries. entirely up to you. The "official" version is wrong. I just thought at the very least by having the correct version would help distinguish it from the one added in FF65

FYI: the difference is
- The 64 pref makes suggestions as you browse websites
- The 65 pref makes suggestion when you're in about:addons or on AMO

Up to you. I'm outta here. Time for some :beers:

**Comment by pyllyukko** [comment]
Enjoy your 🍺
