### ISSUE TITLE
Disqus doesn't work

### ISSUE THREAD

**Issue by brakenow** [pyllyukko/user.js#448]
What should I enable?

**Comment by Atavic** [comment]
See: https://github.com/ghacksuserjs/ghacks-user.js/issues/395#issuecomment-453567960

Disqus is a 3rd party frame and to use it, it has not to be limited. Warn about it: You'll have to whitelist it on the [extensions](https://github.com/privacytoolsIO/privacytools.io/issues/121#issuecomment-271665366) you use, if any.

**Comment by brakenow** [comment]
> See: [ghacksuserjs/ghacks-user.js#395 (comment)](https://github.com/ghacksuserjs/ghacks-user.js/issues/395#issuecomment-453567960)
> 
> Disqus is a 3rd party frame and to use it, it has not to be limited. Warn about it: You'll have to whitelist it on the [extensions](https://github.com/privacytoolsIO/privacytools.io/issues/121#issuecomment-271665366) you use, if any.

Thank you! That worked.

**Comment by Atavic** [comment]
Good, you can close the issue.
