### ISSUE TITLE
Adjust FF default permissions for all sites 

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#45]
My idea is to (by default) adjust the internal permission system to harden some things for every page. Of course in some situations this is not easy e.g. in case you want to allow Push Notif. and such gimmicks that aren't often used (yet). 

To get into the permission just type <code>about:permissions</code>.

We will see the following in FF40+

Name | Value
------------ | -------------
Store Passwords  |  Allow/Block
Share Location  | Always ask / Block
Use the Camera  | Always ask
Use the Microphone   |  Block
Set cookies Allow  |  Allow for session / Block
Open Pop-up Windows  |  Allow/Block
Maintain Offline Storage  | Always ask / Block
Fullscreen  |  Always ask / Block
Receive Push Notifications  |  Always ask / Block

![permissions - copy](https://cloud.githubusercontent.com/assets/727123/9433711/a510aede-4a36-11e5-966a-edba444dca16.png)
![permmanager](https://cloud.githubusercontent.com/assets/727123/9488097/b0a5ee7e-4bd7-11e5-8875-dbece43ab09a.png)

So I suggest to set the options to high, means  _Block_. 

**What's the problem?**

Currently we clean page settings after FF is shutting down. This includes also the site specific settings a user made. 

This will affect the following settings:

Pref. | Value
------------ | -------------
permissions.default.image  |  1 (no GUI for this, for several reasons)
permissions.manager.defaultsUrl  |  (default)
network.cookie.cookieBehavior  |   (we use 1)
privacy.sanitize.sanitizeOnShutdown  |  true
privacy.clearOnShutdown.cache |  true
privacy.clearOnShutdown.cookies |  true
privacy.clearOnShutdown.downloads |  true
privacy.clearOnShutdown.formdata |  true
privacy.clearOnShutdown.history |  true
privacy.clearOnShutdown.offlineApps |  true
privacy.clearOnShutdown.passwords |  true
privacy.clearOnShutdown.sessions |  true
privacy.clearOnShutdown.siteSettings |  true

The <code>privacy.clearOnShutdown.siteSettings</code> needs to changed to <code>false</code> to not break user specific site preferences.

And some options simply don't have an option to control this by an about:config entry (e.g. the push thing), this means we need to mention this into our readme.md. Correct me if I'm wrong but this wouldn't break any security aspect since the local data folder can't be read-out by external apps and I don't know if an attacker really would have an benefit to grab such settings.

**Comment by pyllyukko** [comment]
That might be a good idea. Any idea which one takes preference... the one in site specific preferences or the global settings? Because it would be important, that any data wouldn't still be cached by the browser, after it's being closed.

**Comment by CHEF-KOCH** [comment]
Jupp, I know which can be controlled via about:config and which are really site specific. I will add this here later as a separate post. 

> Also other stuff like geolocation should be completely disabled, even though the user would set it in site preferences.

Jupp, the Geo stuff isn't the same as the site specific stuff that want to access your location. The about:config will not be overridden (in this case) because the one from about is for the url (the geo service) and the toggle within the site specific menu is only to allow it or not (but that never chance the geo url or if that is entirely disabled).

Give me some more time and I will find all the information on this to integrate this in the project.

**Comment by pyllyukko** [comment]
It seems like in most cases the GUI doesn't even offer the possibility to remember the setting. The only feature that I've seen it available is with the fullscreen feature.

**Comment by CHEF-KOCH** [comment]
Sorry, I'm staying on the cable. You're talking about the about:permission or site specific GUI?

**Comment by pyllyukko** [comment]
> You're talking about the about:permission page or site specific GUI?

I mean when I browse some sites and they ask for permissions, the GUI doesn't usually offer the possibility to make that setting permanent, so it would go into ```about:permissions```.

**Comment by CHEF-KOCH** [comment]
If the page ask for something than there is something wrong with your configuration. About:permission is the tab for default site specific settings (normally handled BEFORE the page load anything which requires permissions [except images]). Set everything to block and there will be never a popup or dialog, well except DNT but that is controlled by the FF settings or about:config (the same). The changes are permanent, as I said in the initial post one thing needs to be changed (this is for the second screenshot - the site specific thing) and the about:permission tab doesn't have any about:config switch to wipe the settings.

**Comment by CHEF-KOCH** [comment]
That value only enables to not wipe the settings BUT this isn't my intent - my intent was to pre-set some settings. That can't be done by about:config, I guess that's stored in 41.x in a database but I still need some research.

**Comment by pyllyukko** [comment]
> That value only enables to not wipe the settings BUT this isn't my intent

I think it still improves usability, if people need to make some tweaks. There is still the issue about it storing information about your browsing, which we might need to just document on the README.
