### ISSUE TITLE
netdata gauges rendered with white instead of transparent background

### ISSUE THREAD

**Issue by nicoulaj** [pyllyukko/user.js#450]
Using the relaxed branch, you can see it at netdata's demo site: https://london.my-netdata.io
![screenshot_19-02-26_20 40 18](https://user-images.githubusercontent.com/3162/53441299-6cb83a00-39fe-11e9-90c4-5fbf56ca1ebb.png)

I think it uses the [easy-pie-chart](https://github.com/rendro/easy-pie-chart) library based on [excanvas](https://github.com/arv/explorercanvas).

**Comment by pyllyukko** [comment]
`privacy.resistFingerprinting` makes this happen.

**Comment by Thorin-Oakenpants** [comment]
> `privacy.resistFingerprinting` makes this happen.

If it's the canvas protection in RFP (sorry, I don't have time to check it), then it's as simple as allowing a site exception for canvas.

When RFP=true, under site exceptions
- click on the `info icon` in the urlbar, click the `>` arrow at the top to the right of "Connection", click `More Information`, click on the `Permissions` tab, untick "use default" on `Extract Canvas Data` and instead select `Allow`
- or right click somewhere on the page and select `View Page Info`, then `Permissions` tab, etc

If it is canvas that causes this, then there's the solution and you can close this
