### ISSUE TITLE
enable flash detection

### ISSUE THREAD

**Issue by gourya** [pyllyukko/user.js#452]
I am trying to enable flash in Firefox 52 like I changed the "plugin.scan.plid.all" to true and "plugin.state.flash" to 2 but flash in not detected in net.

I see the flash plugin in firefox addon page and is always activated. I am using the latest flash version.

It's there anything else, which I have to make so I can have enabled flash in firefox?

**Comment by Atavic** [comment]
Solved [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/666)
