### ISSUE TITLE
Reddit two factor login

### ISSUE THREAD

**Issue by brakenow** [pyllyukko/user.js#456]
JSON: details	"TWO_FA_REQUIRED"

What to enable?

**Comment by Atavic** [comment]
*network.http.referer.spoofSource*

...and maybe more? Not a redditor, sorry.

**Comment by Atavic** [comment]
*browser.privatebrowsing.autostart* also must be set to false, as above.

**Comment by brakenow** [comment]
Thank you! Somehow it worked now without doing that.
