### ISSUE TITLE
Cannot play videos in reddit even though I enable all in umatrix

### ISSUE THREAD

**Issue by brakenow** [pyllyukko/user.js#461]
Videos wont play! Thank you Pyllyukko! Git clone -b relaxed is the first thing I do after installing a distro. :)

**Comment by pyllyukko** [comment]
```
The video on this page can’t be played. Your system may not have the required video codecs for: video/mp4;codecs="avc1.4d400a", audio/mp4;codecs="mp4a.40.2"
HTTP “Content-Type” of “video/mp4” is not supported. Load of media resource https://v.redd.it/... failed.
```

<https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#MP4_H.264_%28AAC_or_MP3%29>: "Firefox/Firefox for Android/Firefox OS supports the format in some cases, but only when a third-party decoder is available"

It's not playing videos for me either, even with a fresh profile without user.js.

**Comment by brakenow** [comment]
Thank you pyllyukko! Works fine now. Had to be the distro I used fault.
