### ISSUE TITLE
Favicon from GitLab doesn't display

### ISSUE THREAD

**Issue by antmak** [pyllyukko/user.js#464]
When I have a favicon like this

```
<link rel="shortcut icon" 
type="image/png" 
href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAKUlEQVRYhe3OIQEAAAACIP+f1hkWWEB6FgEBAQEBAQEBAQEBAQEBgXdgl/rw4n36B+EAAAAASUVORK5CYII=" 
id="favicon" 
data-original-href="/assets/favicon-7901bd695fb93edb07975966062049829afb56cf11511236e61bcf425070e36e.png">
```
i dont see it when using 'relaxed' user.js.

Regular favicons like
```
<link rel="shortcut icon" 
type="image/png" 
href="/assets/favicon-7901bd695fb93edb07975966062049829afb56cf11511236e61bcf425070e36e.png" 
id="favicon" 
data-original-href="/assets/favicon-7901bd695fb93edb07975966062049829afb56cf11511236e61bcf425070e36e.png">
```

seem OK

What can I do to see one properly?

**Comment by Atavic** [comment]
Try [security.csp.experimentalEnabled](https://github.com/pyllyukko/user.js/blob/a2d2205901b9693aea4a3802ff02633a7486368c/user.js#L686) set to false.

Related: https://github.com/ghacksuserjs/ghacks-user.js/issues/223

**Comment by antmak** [comment]
> Try security.csp.experimentalEnabled set to false.

Unfortunately this doesn't work to me. The specified above favicon still looks like a white square.

**Comment by pyllyukko** [comment]
It's because your icon actually is a white square. I decoded it into a file and even with a regular image viewer it was a white square.

Try:

```
<link rel="shortcut icon" 
type="image/png" 
href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAM1BMVEUAAAAAAAAAAKoAqgAAqqqqAACqAKqqVSKqqqp9fX0AAP8A/wAA////fX3/AP///wD///8rA+CKAAAAAXRSTlMAQObYZgAAAAFiS0dEAIgFHUgAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAHdElNRQfUAxwRHSYokUbIAAAALklEQVR4nGNgAAFOMGBAAGoLgJkcYAQR5YQBDrwCyFrAACKAZgsHaQIYZiAJAACGigS6y5CZQgAAAABJRU5ErkJggg==" 
id="favicon">
```

**Comment by antmak** [comment]
:man_facepalming:  Thanks for your attention. We've updated the gitlab, it works now
