### ISSUE TITLE
Additional configuration to disable recommended extensions

### ISSUE THREAD

**Issue by duracellcell** [pyllyukko/user.js#465]
Firefox Dev 68.0b3 and Stable 67.0 with `user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr", false);` still shows the UI checkbox to recommend extensions as checked.

I had to add `user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);` and now it's properly unchecked.

**Comment by Thorin-Oakenpants** [comment]
removed in 67
- `browser.newtabpage.activity-stream.asrouter.userprefs.cfr`

replaced by
```
   // user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false); // disable CFR [FF67+]
      // [SETTING] General>Browsing>Recommend extensions as you browse
   // user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false); // disable CFR [FF67+]
      // [SETTING] General>Browsing>Recommend features as you browse
```

all done in [1528953](https://bugzilla.mozilla.org/show_bug.cgi?id=1528953)
