### ISSUE TITLE
Ghostery sneaks in new promotional messaging system

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#47]
Ghostery [now includes](https://www.ghostery.com/en/articles/ghostery-546-new-for-you/) (by default) yet another feature that is under [critism](https://en.wikipedia.org/wiki/Ghostery#Criticism), it includes an option under advance tab to <code>"Allow Ghostery to show messages in my browser related to product features, updates, and promotions</code>. 

This option must be disabled to improve the security since it ask for location, status, age, gender, ip, ....

This is not an issue, but we may need to find a way (if we recommend addons) to harden also these kind of settings or warn about it (as I now did).

**Comment by pyllyukko** [comment]
Yeah. This kind of stuff needs to be on the README.

**Comment by berrythesoftwarecodeprogrammar** [comment]
i stopped using ghostery a long time ago. i was about to talk about how things like ublock are better but i just noticed you already have a thread going on about that

**Comment by nodiscc** [comment]
@CHEF-KOCH @pyllyukko Do you actually want to track setting changes for addons you explicitely don't recommend? (https://github.com/pyllyukko/user.js#tracking-protection) I feel like this might be a waste of time and will clutter the prefs. I think discouraging users from installing ghostery is enough.

**Comment by pyllyukko** [comment]
I agree with @nodiscc. Maybe we should still add these warnings to the README, so that users can make better educated guesses on what addons to use.

**Comment by nodiscc** [comment]
I think this can be closed since this is now linked from the README

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH  The *criticism* section you linked to in the first post no longer exists in Wikipedia.

**Comment by CHEF-KOCH** [comment]
https://en.wikipedia.org/w/index.php?title=Ghostery&type=revision&diff=717683798&oldid=717683717

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH I'm not seeing it in that link either.  Who deleted it?  Was information hidden from Wikipedia readers, or was it just a reorganization of data?

I do notice that the Wikipedia entry currently states *"Ghostery’s privacy team creates profiles of page elements and companies for educational purposes."*  Whose education?  Is this this the only use of this data?  Is anyone paying for this "education"?

**Comment by CHEF-KOCH** [comment]
https://github.com/pyllyukko/user.js/pull/151#issuecomment-221494756

**Comment by CHEF-KOCH** [comment]
[Burda is now the new owner of Ghostery](http://www.turi2.de/aktuell/burda-browser-cliqz-kauft-ghostery/) (source is in german).

**Comment by pyllyukko** [comment]
[Wikipedia says](https://en.wikipedia.org/wiki/Ghostery): "In February 2017 Ghostery was aquired by Cliqz, a German company owned by **Mozilla** and Hubert Burda Media that builds browser technologies which emphasize privacy."

**Comment by nodiscc** [comment]
Here is the translation of cliqz.com "About us" page:

> Cliqz has begun to merge the browser and search, thus redesigning the user interface of the Internet. More than 100 experts from about 30 countries are developing innovative software in Munich with the aim of bringing the users as directly as possible to their goal while maintaining their privacy. Cliqz GmbH was founded under the name 10betterpages GmbH in April 2008 by Jean-Paul Schmetz. Since May 2013, Cliqz GmbH has been a majority shareholder of Hubert Burda Media. Cliqz operates independently of other Burda units, does not exchange any data with them, and treats Burda's own websites differently than others (for example, in search ranking or anti-tracking). In August 2016, Mozilla acquired a strategic minority stake in Cliqz. In June 2014 Cliqz for Firefox started. The "Quick search directly in the browser" concept implemented in the browser extension won over a million monthly active users in a few months. Since the end of 2015, Cliqz has been a stand-alone browser. The version 1.0 of Cliqz for Windows and Mac with integrated anti-tracking was released in March 2016. In addition, there is the Cliqz browser with built-in fast search engine also for Android and iOS. In June 2016, Cliqz released the software code of its browser versions and the Firefox extension - open source for maximum transparency.

 * Mozilla has a minority share (Cliqz is not "Mozila-owned")
 * Cliqz distributes a low-marketshare, custom browser (does not contribute to major OSS projects)
 * _"Ghostery and Cliqz will continue to work closely with our previous parent company, Evidon"_. [Evidon](https://en.wikipedia.org/wiki/Evidon,_Inc.) is an analytics company.
 * Ghostery's only worthwhile addition is providing (non-public? maintained?) ad blocking lists, whereas other recommended addons (uBlock) do the same thing with publicly-sourced, well maintained blocklists.

For me this would warrant removing Ghostery from the list of recommended addons; but here is how we could proceed:

 * Close this issue (it's unclear what this is about)
 * Reorganize the recommended addons/tracking protection section (open another issue)
  * If Ghostery recommendation is maintained, just add a note that it is controlled by an advertising/analytics company
 * Remove Ghostery from the list of recommended addons (open another issue)

So let's close this issue?

**Comment by pyllyukko** [comment]
> Close this issue (it's unclear what this is about)

Agreed.

>     Reorganize the recommended addons/tracking protection section (open another issue)
>     If Ghostery recommendation is maintained, just add a note that it is controlled by an advertising/analytics company

There are already fair warnings about this fact. Of course we can always rephrase it.

>     Remove Ghostery from the list of recommended addons (open another issue)

I think it's still a fair alternative for the "normal users". I think uBlock might be a bit confusing for the average joe.

**Comment by nodiscc** [comment]
In the default configuration, uBlock is very usable for non-technical users (it's just an ad blocker and the only setting "normal users" may _ever_ need to touch if needed is the blocklist selection settings) - the only UI they will ever be presented with is the 2 leftmost screenshots at https://addons.mozilla.org/fr/firefox/addon/ublock-origin/.

Or are you confusing with uMatrix? (fairly avanced)

This can be brought up in another issue.

Thanks for clearing up the bug tracker :)

**Comment by pyllyukko** [comment]
> Or are you confusing with uMatrix? (fairly avanced)

No, I ment uBlock.

> Thanks for clearing up the bug tracker :)

Thanks for flagging these! I have left many of them pending / open for no proper reason, and it's good to have 'em cleaned up a bit so we can have better focus.
