### ISSUE TITLE
user agent - platform

### ISSUE THREAD

**Issue by ubone** [pyllyukko/user.js#472]
`privacy.resistFingerprinting` changes the user agent to windows

but the platform is still Linux

`general.platform.override` does not work on 68

**Comment by Atavic** [comment]
resist fingerprinting, when active, overrides all these:

general.useragent.override
general.buildID.override
general.appname.override
general.appversion.override
general.platform.override
general.oscpu.override
general.useragent.locale

**Comment by fwanky** [comment]
@Atavic Is it a good practice to turn resist fingerprinting off when using linux as the platform and UA contradict eachother? 
It feels silly, really.

**Comment by fwanky** [comment]
@Atavic Is it a good practice to turn resist fingerprinting off when using linux as the platform and UA contradict eachother? 
It feels silly, really.

**Comment by ubone** [comment]
platform isn't recorded by default at least for nginx afaik

**Comment by Atavic** [comment]
Javascript can look at your browser's contradictions and take it out of the bunker.
I'd keep resistefingerprinting on.

**Comment by pyllyukko** [comment]
> Is it a good practice to turn resist fingerprinting off when using linux

Not in my opinion. I would recommend leaving it on.
