### ISSUE TITLE
Fingerprinting

### ISSUE THREAD

**Issue by ghost** [pyllyukko/user.js#473]
I love this user.js, really useful for portability and such.
One issue i'm having is my result here on panoptoclick; https://0x0.st/zJZD.png
My friend, using the same user.js file as me did the same test and got a tick mark on the fingerprinting, could this have anything to do with the UA? 
https://0x0.st/zJZd.png, i'm on linux so my best bet is that it could be something to do with the UA?
I know that there are obviously tons of factors that play into this, I would just like minimize my virtual footprint as much as physically possible.

**Comment by fwanky** [comment]
I had just turned off 
user_pref("privacy.resistFingerprinting",			true);.
this had seemed to make it worse than before for me..

**Comment by Atavic** [comment]
Panopticlick looks at your browser's values against a database hosted by panopticlick servers. This means that newer browsers versions will have quite unique results for a period of time. That test has been heavily used some years ago, so the best results can still be obtained with older firefox versions. I'd keep "privacy.resistFingerprinting" as true.

See: https://github.com/ghacksuserjs/ghacks-user.js/issues/620#issue-403016669

You should take that test with some grains of salt, as long as you're not unique, that's a plus.

**Comment by pyllyukko** [comment]
> I love this user.js, really useful for portability and such.

Thank you :blush: 

For me it says "✓ yes".

> i'm on linux so my best bet is that it could be something to do with the UA?

`privacy.resistFingerprinting` does alter your UA and claims you're using Windows.
