### ISSUE TITLE
Cannot login to Reddit: details "TWO_FA_REQUIRED"

### ISSUE THREAD

**Issue by brakenow** [pyllyukko/user.js#477]
Cannot login to reddit. Got two factor login.

**Comment by pyllyukko** [comment]
Can you be a bit more specific?

**Comment by brakenow** [comment]
https://postimg.cc/q67RqNN9

**Comment by rusty-snake** [comment]
@brakenow 
```
[![reddit.png](https://i.postimg.cc/PJW86ZTr/reddit.png)](https://postimg.cc/q67RqNN9)
```
[![reddit.png](https://i.postimg.cc/PJW86ZTr/reddit.png)](https://postimg.cc/q67RqNN9)

**Comment by brakenow** [comment]
Refreshed FF, and installed the addon 'Privacy Settings'. For the time being. I love your script, so I hope it will be solved!

**Comment by pyllyukko** [comment]
So have you enabled 2FA in Reddit? I tried to reproduce this but couldn't. After entering my creds it asks for the 2FA code and then I'm in.

**Comment by Thorin-Oakenpants** [comment]
You can close this: brakenow [reported](https://github.com/ghacksuserjs/ghacks-user.js/issues/823#issuecomment-565219991) it was his uMatrix configuration

**Comment by pyllyukko** [comment]
> You can close this: brakenow [reported](https://github.com/ghacksuserjs/ghacks-user.js/issues/823#issuecomment-565219991) it was his uMatrix configuration

Thanks.
