### ISSUE TITLE
Snippets from Mozilla on Wayland (Linux)

### ISSUE THREAD

**Issue by travankor** [pyllyukko/user.js#478]
On Firefox 70 Wayland (Linux), I get [snippets from Mozilla](https://files.catbox.moe/yrlzsm.png) unless I set `browser.newtabpage.activity-stream.feeds.snippets` to false.

Can you guys add this in the default user.js? I see that you set `browser.newtabpage.activity-stream.enabled` to false, but this doesn't work on FF70 Wayland. This is honestly the 3rd or 4th time I have an issue like this on Firefox Wayland.

While I really like this project, have you guys considered just removing all the Mozilla telemetry URLs in the about.config (ie: set `browser.newtabpage.activity-stream.asrouter.providers.snippets` to empty)? This is basically what ungoogled-chromium does, and it works really well for them.

**Comment by pyllyukko** [comment]
Thanks for reporting this. Removing all the URLs has been discussed before, but I think that the proper way is to disable the features.
