### ISSUE TITLE
QA: How do I enable timezone ?

### ISSUE THREAD

**Issue by gerroon** [pyllyukko/user.js#480]
HI

How can I enable(or disable) correct time zone so that time in my browser is correct? Atm it is  about 5 hours ahead, and I suspect this is more to do with the fact that I am using user.js

thanks

**Comment by rusty-snake** [comment]
This is caust by RFP.
https://github.com/pyllyukko/user.js/blob/88cab942b4da5d5706acb7609a680d9d1938edda/user.js#L526-L531

At the moment the only way to get the correct TZ is to disable RFP, but then you lose all the protection from it.

**Comment by rusty-snake** [comment]
[bugzilla 1364261: Make UTC Timezone Spoofing optional when privacy.resistfingerprinting = true](https://bugzilla.mozilla.org/show_bug.cgi?id=1364261)

**Comment by gerroon** [comment]
Thanks for the quick reply, I have been looking all over in the user.js file but this was not obvious at all.
