### ISSUE TITLE
Twitter scrollbar inside interface 

### ISSUE THREAD

**Issue by nikoloskid** [pyllyukko/user.js#483]
![Screenshot_20200324_132158](https://user-images.githubusercontent.com/12738743/77429001-e3c22c80-6dd0-11ea-9daf-db51f2bd7a0f.png)

Tested Twitter on clean profile and Brave, I don't get the scrollbar. Anyone have idea why I got this, couple of days ago I did not have it, and I have not changed any settings...

**Comment by Atavic** [comment]
I'm lost with twitter on a browser. Pageload is insufferable.

**Comment by pyllyukko** [comment]
I've used Twitter plenty with `user.js` and haven't experienced any issues. Please re-open with more details if necessary.
