### ISSUE TITLE
Encrypted SNI

### ISSUE THREAD

**Issue by robo2bobo** [pyllyukko/user.js#484]
One setting that is missing and I always have to add it manually, is to enable encrypted SNI. I think by default its disabled in firefox.

You may check if your browser has it enabled by visiting: 
https://www.cloudflare.com/ssl/encrypted-sni/

To enable encrypted SNI, the following setting:
network.security.esni.enabled (true/false)

I believe its safe to enable in both master and relaxed branches.

Thank you.

**Comment by rusty-snake** [comment]
`network.security.esni.enabled=true` requires `network.trr.mode=2|3` see https://bugzilla.mozilla.org/show_bug.cgi?id=1500289

**Comment by robo2bobo** [comment]
Sure, it requires TRR to work, but that shouldn't stop us from setting esni to enabled by default.

Once someone enables TRR, then esni will be already enabled. If TRR is disabled then the status of esni is irrelevant and having it enabled does not hurt.

More details here:
https://wiki.mozilla.org/Trusted_Recursive_Resolver

**Comment by pyllyukko** [comment]
Thanks!
