### ISSUE TITLE
Makefile debian_locked with comment not processed

### ISSUE THREAD

**Issue by gdani2c4** [pyllyukko/user.js#485]
Possibly that is intended as such...  5 properties are not processed by the sed command in the Makefile because of a trailing comment, so they are not locked; maybe this is intentional since these target specific versions...  possibly this is in the README but I didn't see it.
Thanks that you share your investigation in _users.js_,
Dan

**Comment by nodiscc** [comment]
>  5 properties are not processed by the sed command

Which ones please?

> maybe this is intentional

I don't think it is

**Comment by gdani2c4** [comment]
nodiscc, these keys are displayed to me with `grep '^user_p' debian_locked.js`. This brings to me
```
user_pref("media.peerconnection.ice.default_address_only",  true); // Firefox 42-51
user_pref("media.peerconnection.ice.no_host",           true); // Firefox >= 52
user_pref("browser.safebrowsing.enabled",           true); // Firefox < 50
user_pref("browser.safebrowsing.phishing.enabled",      true); // firefox >= 50
user_pref("security.ssl3.ecdhe_ecdsa_aes_128_gcm_sha256",   true); // 0xc02b
user_pref("security.ssl3.ecdhe_rsa_aes_128_gcm_sha256",     true); // 0xc02f
```
The cause of this seems the trailing comment that I noted in the initial comment. Specifically, line 25,26 of the makefile:
```
debian_locked.js: user.js 
    sed 's/^user_pref(\("[^"]\+"\),\s\+\([^)]\+\));$$/pref(\1, \2, locked);/' $< >| $@
```
only matches lines that terminate in the ';'

**Comment by pyllyukko** [comment]
Good catch. Thanks!
