### ISSUE TITLE
[HowTo] Running unsigned add-ons in Firefox

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#49]
1) Via <code>xpinstall.signatures.require false</code>
2) Via an alternative Firefox [ESR[(https://www.mozilla.org/en-US/firefox/organizations/) version
3) Via [Nightly](https://nightly.mozilla.org/) or [Developer](https://www.mozilla.org/en-US/firefox/developer/) editions
4) What Mozilla said, a [special release](https://wiki.mozilla.org/Add-ons/Extension_Signing)
5) Use forks based on Firefox with integrated switch. 
6) Compile firefox with MOZ_ADDON_SIGNING=0

**Comment by pyllyukko** [comment]
Are you referring to the NoScript NSA with this?

**Comment by CHEF-KOCH** [comment]
Yes, and for beta people which using actually versions that are 'locked'. So it's more an common 'workaround' for everyone.

**Comment by fenque** [comment]
6) Compile firefox with MOZ_ADDON_SIGNING=0

**Comment by CHEF-KOCH** [comment]
Thanks, added. :+1:

**Comment by pyllyukko** [comment]
And apparently now it happened:

[Firefox 48 release notes](https://www.mozilla.org/en-US/firefox/48.0/releasenotes/): "Add-ons that have not been verified and signed by Mozilla will not load"

**Comment by Gitoffthelawn** [comment]
Here is a detailed article on gHacks detailing another technique.

Note also that Mozilla has made it very easy and fast to get extensions signed.  There is no financial cost.

**Comment by nodiscc** [comment]
Getting extensions signed has become really easy, and actually improves security/accountability of addon developers. It was problematic at the time of this change, but appears to no longer be.

I think this can be closed/archived.
