### ISSUE TITLE
Shellcheck tests are failing

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#492]
https://travis-ci.org/github/pyllyukko/user.js

**Comment by pyllyukko** [comment]
We need to ditch `cas.sh`, as it's not been updated in ages and is not working anymore.

**Comment by nodiscc** [comment]
https://github.com/pyllyukko/user.js/pull/514

**Comment by pyllyukko** [comment]
Also: " Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on."

**Comment by nodiscc** [comment]
> Since June 15th, 2021, the building on travis-ci.org is ceased

Yeah. I have moved most of my projects to Gitlab CI or Github Actions for this reason. Travis as a free CI service is basically dead. Do you want me to send a pull request to switch to GH actions? For a simple Makefile-based test suite it should be quite easy (https://github.com/nodiscc/hecat/blob/master/.github/workflows/ci.yml)

**Comment by pyllyukko** [comment]
> Do you want me to send a pull request to switch to GH actions?

Sure!
