### ISSUE TITLE
This is my output iam from morroco and i use VPN

### ISSUE THREAD

**Issue by mrhili** [pyllyukko/user.js#495]
Is this good ?

./cas.sh -C -P /home/osboxes/.mozilla/firefox/wjritila.PylyWay -a

importing CAs:
[-] error: file `/usr/share/ca-certificates/mozilla/AddTrust_External_Root.crt' not found!
  /usr/share/ca-certificates/mozilla/Baltimore_CyberTrust_Root.crt
  /usr/share/ca-certificates/mozilla/COMODO_Certification_Authority.crt
[-] error: file `/usr/share/ca-certificates/mozilla/Deutsche_Telekom_Root_CA_2.crt' not found!
  /usr/share/ca-certificates/mozilla/DigiCert_High_Assurance_EV_Root_CA.crt
  /usr/share/ca-certificates/mozilla/DigiCert_Global_Root_CA.crt
[-] error: file `/usr/share/ca-certificates/mozilla/Entrust.net_Secure_Server_CA.crt' not found!
  /usr/share/ca-certificates/mozilla/Entrust.net_Premium_2048_Secure_Server_CA.crt
  /usr/share/ca-certificates/mozilla/Entrust_Root_Certification_Authority.crt
[-] error: file `/usr/share/ca-certificates/mozilla/Equifax_Secure_CA.crt' not found!
[-] error: file `/usr/share/ca-certificates/mozilla/GTE_CyberTrust_Global_Root.crt' not found!
[-] error: file `/usr/share/ca-certificates/mozilla/GeoTrust_Global_CA.crt' not found!
[-] error: file `/usr/share/ca-certificates/mozilla/GeoTrust_Primary_Certification_Authority.crt' not found!
[-] error: file `/usr/share/ca-certificates/mozilla/GeoTrust_Primary_Certification_Authority_-_G3.crt' not found!
  /usr/share/ca-certificates/mozilla/GlobalSign_Root_CA.crt
  /usr/share/ca-certificates/mozilla/Go_Daddy_Class_2_CA.crt
  /usr/share/ca-certificates/mozilla/Go_Daddy_Root_Certificate_Authority_-_G2.crt
  /usr/share/ca-certificates/mozilla/Starfield_Class_2_CA.crt
[-] error: file `/usr/share/ca-certificates/mozilla/StartCom_Certification_Authority.crt' not found!
[-] error: file `/usr/share/ca-certificates/mozilla/UTN_USERFirst_Hardware_Root_CA.crt' not found!
[-] error: file `/usr/share/ca-certificates/mozilla/ValiCert_Class_2_VA.crt' not found!
  /usr/share/ca-certificates/mozilla/Verisign_Class_3_Public_Primary_Certification_Authority_-_G3.crt
[-] error: file `/usr/share/ca-certificates/mozilla/VeriSign_Class_3_Public_Primary_Certification_Authority_-_G5.crt' not found!
[-] error: file `/usr/share/ca-certificates/mozilla/thawte_Primary_Root_CA.crt' not found!
[-] error: file `/usr/share/ca-certificates/mozilla/thawte_Primary_Root_CA_-_G3.crt' not found!
  /usr/share/ca-certificates/mozilla/SecureTrust_CA.crt
  /usr/share/ca-certificates/mozilla/QuoVadis_Root_CA_2.crt
  /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt

current root CA list from /home/osboxes/.mozilla/firefox/wjritila.PylyWay/cert8.db (17 certificates):

subject=C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root CT,c,c
subject=C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO Certification Authority CT,c,c
subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA CT,c,c
subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA CT,c,c
subject=O = Entrust.net, OU = www.entrust.net/CPS_2048 incorp. by ref. (limits liab.), OU = (c) 1999 Entrust.net Limited, CN = Entrust.net Certification Authority (2048) CT,c,c
subject=C = US, O = "Entrust, Inc.", OU = www.entrust.net/CPS is incorporated by reference, OU = "(c) 2006 Entrust, Inc.", CN = Entrust Root Certification Authority CT,c,c
subject=C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA CT,c,c
subject=C = US, O = "The Go Daddy Group, Inc.", OU = Go Daddy Class 2 Certification Authority CT,c,c
subject=C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", CN = Go Daddy Root Certificate Authority - G2 CT,c,c
subject=C = US, O = "Starfield Technologies, Inc.", OU = Starfield Class 2 Certification Authority CT,c,c
subject=C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 1999 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primary Certification Authority - G3 CT,c,c
subject=C = US, O = SecureTrust Corporation, CN = SecureTrust CA CT,c,c
subject=C = BM, O = QuoVadis Limited, CN = QuoVadis Root CA 2 CT,c,c
subject=O = Digital Signature Trust Co., CN = DST Root CA X3 CT,c,c

countries (check the codes from https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements):

[-] warning: country not found for `subject=C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root'!
[-] warning: country not found for `subject=C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO Certification Authority'!
[-] warning: country not found for `subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA'!
[-] warning: country not found for `subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA'!
[-] warning: country not found for `subject=O = Entrust.net, OU = www.entrust.net/CPS_2048 incorp. by ref. (limits liab.), OU = (c) 1999 Entrust.net Limited, CN = Entrust.net Certification Authority (2048)'!
[-] warning: country not found for `subject=C = US, O = "Entrust, Inc.", OU = www.entrust.net/CPS is incorporated by reference, OU = "(c) 2006 Entrust, Inc.", CN = Entrust Root Certification Authority'!
[-] warning: country not found for `subject=C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA'!
[-] warning: country not found for `subject=C = US, O = "The Go Daddy Group, Inc.", OU = Go Daddy Class 2 Certification Authority'!
[-] warning: country not found for `subject=C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", CN = Go Daddy Root Certificate Authority - G2'!
[-] warning: country not found for `subject=C = US, O = "Starfield Technologies, Inc.", OU = Starfield Class 2 Certification Authority'!
[-] warning: country not found for `subject=C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 1999 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primary Certification Authority - G3'!
[-] warning: country not found for `subject=C = US, O = SecureTrust Corporation, CN = SecureTrust CA'!
[-] warning: country not found for `subject=C = BM, O = QuoVadis Limited, CN = QuoVadis Root CA 2'!
[-] warning: country not found for `subject=O = Digital Signature Trust Co., CN = DST Root CA X3'!

**Comment by pyllyukko** [comment]
Nope. Not good. The `cas.sh` script hasn't been touched in a while and it has rotten. I'll see if I can get it working again. In the meanwhile if you are trying to use it, at least the CA list itself should be updated. You can [look here](https://github.com/pyllyukko/harden.sh/blob/master/newconfs/ca-certificates.conf.new) for that.

**Comment by mrhili** [comment]
Thank you i will look for it and thank you for your efforts

**Comment by nodiscc** [comment]
`cas.sh` will be dropped in https://github.com/pyllyukko/user.js/pull/514

**Comment by nodiscc** [comment]
https://github.com/pyllyukko/user.js/pull/514 merged, this issue should be closed
