### ISSUE TITLE
Google Captcha

### ISSUE THREAD

**Issue by dducted** [pyllyukko/user.js#496]
Hi,

I am still having issues with google captchers. Is there a way to get around it? All options mentioned here in different issues didnt help for me.

Thanks!

**Comment by pyllyukko** [comment]
Have you tried disabling Firefox's built-in content blocking? That usually works for me.

**Comment by dducted** [comment]
Oddly all of a sudden it works now. Thanks for the tip though.

I have one more question. Could you tell me why you have set `user_pref("keyword.enabled", false);`?  I find it really helpful to just use the url bar for search queries however I would like to know why you have forbidden such behavior.

Thank you!

**Comment by pyllyukko** [comment]
> Oddly all of a sudden it works now.

Great! I'll close this issue then.

> I have one more question. Could you tell me why you have set `user_pref("keyword.enabled", false);`? I find it really helpful to just use the url bar for search queries however I would like to know why you have forbidden such behavior.

Because I don't want e.g. mistyped domains/addresses to go to search engines. I find `ctrl-k` convenient enough when I want (and choose) to use search engines.
