### ISSUE TITLE
Each tab in task bar

### ISSUE THREAD

**Issue by dducted** [pyllyukko/user.js#497]
Hi,

I am unsure if that is related to your user file or if its new in FF but I just noticed now that each tab appears to be a window in the taskbar. 

![img](https://i.imgur.com/j2fCEHf.png)

**Comment by rusty-snake** [comment]
Search on about:config for "browser.taskbar" or go on about:preferences to general -> tabs to change this. This user.js does not to contains browser.taksbar.*.

**Comment by dducted** [comment]
Oh I must've accidentally checked then. Thank you!
