### ISSUE TITLE
Set dom.storage.enabled to false cause issues with adobe websites [Info]

### ISSUE THREAD

**Issue by dennyamarojr** [pyllyukko/user.js#499]
Hi pyllyukko,

Find an issue with dom.storage.enabled, when put to false cause issues with adobe website
https://stock.adobe.com/free

Not sure if happens with other websites, but, when try to get in this websites just load and them shows a blank page.

Firefox version: 78.3.1esr (64-bit)

**Comment by quantumpacket** [comment]
@dennyamarojr The `user.js` file is meant to be a template, which you then customize for your needs. If you have an issue with a specific setting you can disable it. There are a lot of sites that require DOM storage. If you find that you are having to change a lot of settings often to get functionality then you can try out the https://github.com/pyllyukko/user.js/tree/relaxed branch.

**Comment by pyllyukko** [comment]
It does break a whole bunch of sites and that's why it was commented out in d4c98d9b4e116cc9b757ba042d3566c0dc5bf73a.
