### ISSUE TITLE
[question] commented options

### ISSUE THREAD

**Issue by zummuz** [pyllyukko/user.js#50]
Hi,
why this options are commented:
//user_pref("dom.storage.enabled",		false);
//user_pref("browser.cache.memory.enable",		false);?
Can it break something? I assume this entries are quite important for privacy, aren't they? The second one allows to set unique identificator by e-tag and the first one allows to set kind of cookies?

**Comment by CHEF-KOCH** [comment]
To disable DOM storage breaks additional addons and pages like e.g. the Mega addon/page. The cache entry is to set the entire cache in kilobyte. Since (I don't now exactly FF 30) there is an additional garbage collector which automatically 'optimize' it if you minimize FF for xyz amount of time. DOM isn't important for security, or not more like cookies e.g. cookies are insecure while htst is more secure but also can be used 'for evil things' to track. So whatever you set there must be always backward compatibility.

**Comment by zummuz** [comment]
So DOM storage is the least thing I should care about for privacy and memory cache is being reset from time to time? I don't get the part about 'garbage collector'. I went to http://ip-check.info/ and test showed that memory cache can be used to track and should be blocked or reset upon moving to another site.

**Comment by CHEF-KOCH** [comment]
Yes, everything 'could' track you. But could isn't automatically that every page will hunt you. Yes, I would more carry about cookies, without cookies most of all 'tracking test' pages will never work, same like javascript, but disabling these stuff would break almost everything (that's the reason why it's enabled by default in tor's browser). 

About the memory, I think the news about tracking the local files is correct but Firefox will change this dramatically in the next upcoming releases, so the question is if we need this option if it gets removed or protected by the new permission manager. E.g. here on GitHub you'll see an warning about HTML5 (only an example) such kind of notifications will be improved in the 44/45 releases. 

In the latest Tor browser this is also set to 'true', and after some searching someone said this will anyway protected by NoScript and other external AND internal tools. So, I wouldn't worry about it.

**Comment by zummuz** [comment]
Ok, thanks.

**Comment by CHEF-KOCH** [comment]
For the record: 

Under NoScript options -> Emeddings -> ensure 'Apply these restrictions to whitelisted sites too' + the stuff you want to local protect is checked, e.g. Java,Flash, <FRAME> and such. If this is checked even whitelisted sites are protected against this.
