### ISSUE TITLE
[Question/FR] Fenix/Fennec For Mobile

### ISSUE THREAD

**Issue by grravity** [pyllyukko/user.js#501]
I am inquiring if there is any good solution similar to ghacks user.js for Fenix (Fennec on F-Droid) on Android that has the goal of hardening as ghacks user.js does for desktop Firefox?

To my knowledge, you cannot simply use a user.js file on mobile, although I could be wrong? I know you can edit about:config, however manually doing this (and staying up to date on changes) will be insanely tedious.

I was curious if there is any possibilities or suggestions for this?

**Comment by nodiscc** [comment]
Look at https://github.com/pyllyukko/user.js#single-profile-installation README section (although this hasn't been tested for a while). Does this file location work?

**Comment by grravity** [comment]
I'm seeing /storage/emulated/0/Android/data/org.mozilla.fennec_fdroid but there's nothing in it

**Comment by grravity** [comment]
Still have not figured this out

**Comment by caviidae** [comment]
It's under `/data` which can only be accessed if your phone is rooted if I remember correctly.

**Comment by grravity** [comment]
Alright, that's a shame. Thank you

**Comment by ltGuillaume** [comment]
@seniorm0ment Late to the party, but you might want to have a look at Mull: https://f-droid.org/en/packages/us.spotco.fennec_dos/

**Comment by seniorm0ment** [comment]
Am using, it wasn't available at the time. Thanks :)
