### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by DanitiKain** [pyllyukko/user.js#503]
I want to keep all the settings in place but allow for open tabs when closed to be reopened and the login to be saved. I am creating a separate profile for chats so whatsapp, discord, slack etc and using web version. I would like them to all reopen when I launch this profile. I can't seem to get the right settings in place in the user.js file for this profile to reopen that tabs that were last active. Could you assist with what would be the correct values to keep the login and also reopen that tabs that were open on shutdown. I changed most of the settings for cookies and restoring tabs. As of right now its not working.

**Comment by nodiscc** [comment]
What comes to mind:
- disable permanent private browsing mode
- re-enable browsing history  retention

**Comment by DanitiKain** [comment]
Ok looks like I got the tabs to save but not the login. Any thoughts on how to get the login to save?
