### ISSUE TITLE
How to enable history?

### ISSUE THREAD

**Issue by gerroon** [pyllyukko/user.js#504]
Hi

I have been trying to figure this out for quite long time and finally I am buggin you. How can I bring the history back? I am mainly interested it for the reasons of autocomplete and I do not want to bookmark every site I visit to be able to autocomplete the url.

Here some I tried and these do not seem to help.

`user_pref("browser.privatebrowsing.autostart",          false);`

`user_pref("browser.cache.offline.enable",           false);`

`user_pref("places.history.enabled",             false);`

`user_pref("privacy.clearOnShutdown.history",            false);`

`user_pref("browser.cache.disk.enable",              false);`

I am using it with FF 84 Linux 

thanks

**Comment by mimecry** [comment]
`places.history.enabled` should be true no?

**Comment by gerroon** [comment]
Hi

Thanks I will try that too.

**Comment by pyllyukko** [comment]
> Thanks I will try that too.

Did it work?

**Comment by gerroon** [comment]
Yes it did.
