### ISSUE TITLE
Disable downloading of Favicons in response to Favicon fingerprinting technique

### ISSUE THREAD

**Issue by IL2P** [pyllyukko/user.js#508]
Suggest:

user.js add
```
// PREF: Disable downloading of Favicons in response to Favicon fingerprinting techniques
user_pref("browser.chrome.site_icons",			false);
```

See https://github.com/jonasstrehle/supercookie

Tested via https://supercookie.me/ and this change seems to prevent this fingerprinting method.

https://supercookie.me/ test goes in an infinite loop and never provide an ID result.

My current bookmarked Favicons are still there but new ones are not added.

**Comment by pyllyukko** [comment]
Thanks!

**Comment by e-t-l** [comment]
If this is enabled, is there any alternative way to manually download "safe" favicons? Don't really like the idea of a bunch of ugly default icons for every webpage
