### ISSUE TITLE
Repeat  PREF 4520 4614

### ISSUE THREAD

**Issue by polyproline** [pyllyukko/user.js#511]
/* 4520: disable chrome animations [FF77+] [RESTART]
 * [NOTE] pref added in FF63, but applied to chrome in FF77. RFP spoofs this for web content ***/
user_pref("ui.prefersReducedMotion", 1); // [HIDDEN PREF]

// 4614: enforce prefers-reduced-motion as no-preference [FF63+] [RESTART]
   // 0=no-preference, 1=reduce
user_pref("ui.prefersReducedMotion", 0); // [HIDDEN PREF]

**Comment by pyllyukko** [comment]
Why? What are the security/privacy implications of this feature?

**Comment by Thorin-Oakenpants** [comment]
@pyllyukko OP is quoting arkenfox's user.js

The reason it is listed twice, is: in order of the prefs in the user.js with some notes
```js
// we enable RFP by default
user_pref("privacy.resistFingerprinting", true); // RFP returns "no-preference" for web content

// RFP ignores this for web content so it's safe to change
// for one, it stops the megabar expanding until you start typing in it
// we set it here so no-one needs to change it
user_pref("ui.prefersReducedMotion", 1); // [HIDDEN PREF]

// then in a commented out RFP Alternatives section we have
// if a user disables RFP and uses the RFP Alts instead, the above value of 1 above does not override the value of 0 below
user_pref("ui.prefersReducedMotion", 0); // [HIDDEN PREF]
```

Hope that makes sense. We set a default before the alts, so that if alts is activated, it doesn't get overriden

**Comment by pyllyukko** [comment]
As I understood this is handled by RFP so I don't think we need to set this explicitly.

**Comment by pyllyukko** [comment]
I'm closing this for now. Please re-open with more details and references if necessary.
