### ISSUE TITLE
Can't change useragent

### ISSUE THREAD

**Issue by OliverTrust** [pyllyukko/user.js#512]
Use this "profile" in selenium python and can't change useragent. Problem in this profile. With another profile changing work

**Comment by fgeek** [comment]
What was the exact workflow? What problem? Give use case where you had an issue, thanks.

**Comment by OliverTrust** [comment]
Ok. 
`profile = webdriver.FirefoxProfile()`
`profile.set_preference('general.useragent.override', 'any_useragent')'
This perfectly work with default firefox profile. But with this user.js useragent all time "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"
p.s.
general.oscpu.override
general.platform.override
general.buildID.override
not work too

**Comment by OliverTrust** [comment]
In user.js i find (762 line) `// PREF: Spoof User-agent (disabled)` I can't change useragent?
