### ISSUE TITLE
Segmentation fault on OpenBSD

### ISSUE THREAD

**Issue by andreoss** [pyllyukko/user.js#516]
This line is causing segfault on OpenBSD 6.9 & Mozilla Firefox 88.0.1

https://github.com/pyllyukko/user.js/blob/9d18038056f27850356389edef7ea8e71ed634a1/user.js#L693

**Comment by pyllyukko** [comment]
What?! 😆 Sounds like a bug in Firefox. I recommend testing with the latest Firefox version and reporting it to Mozilla if it still segfaults.
