### ISSUE TITLE
"Plugin check" website opens on every Firefox start

### ISSUE THREAD

**Issue by jayphizzle** [pyllyukko/user.js#52]
A tab which opens "https://www.mozilla.org/de/plugincheck/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_campaign=plugincheck-update" on every Firefox Startup.

I created a fresh profile and copied only the user.js to this profile.

Version: 	42.0b4 (x64) @ Windows 7 Prof. x64
Build-ID: 	20151005144425

Please let me know if you need more informations.

**Comment by pyllyukko** [comment]
Indeed it does. Is it a problem? You can change this behavior by commenting out ```plugins.update.notifyUser```.

**Comment by jayphizzle** [comment]
Ok on the x64 Beta the plugin list was empty. Now on the x86 final the outdated plugins are listed.
So it makes sense now.

At work we need to use some older Java versions for compatibility reasons.
Workarround `plugins.update.notifyUser` does the trick. Thanks

**Comment by pyllyukko** [comment]
> At work we need to use some older Java versions for compatibility reasons.

Sounds dangerous.

So can we close this issue, or is there some problem with this behavior?

**Comment by jayphizzle** [comment]
> Sounds dangerous.

Yeah i know, i try to get that fixed.

> So can we close this issue, or is there some problem with this behavior?

You can close this.

**Comment by pyllyukko** [comment]
Ok.
