### ISSUE TITLE
Investigate use of the `sticky` flag on prefs

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#527]
Followup to https://github.com/pyllyukko/user.js/issues/415

> I upgraded to Firefox 60 ESR on Debian today and saw the following changes in the debian-provided default firefox-esr.js file:

```diff
- ...
+// Default to classic view for about:newtab
+pref("browser.newtabpage.enhanced", false, sticky);
```

It would be good to determine how to use the `sticky` flag on prefs/what it does, and if it is useful and relevant to this project.

**Comment by nodiscc** [comment]
I'm no longer working on this.

**Comment by pyllyukko** [comment]
> I'm no longer working on this.

Thanks for all your contributions during the years! ❤️

**Comment by nodiscc** [comment]
> determine how to use the sticky flag on prefs/what it does, and if it is useful and relevant to this project.

During an unrelated search, I found this page: https://www.devdoc.net/web/developer.mozilla.org/en-US/docs/Preferences/A_brief_guide_to_Mozilla_preferences.html#Sticky_Preferences

> Sticky preferences were introduced in Firefox 40 via [bug 1098343](https://bugzilla.mozilla.org/show_bug.cgi?id=1098343).

> Sticky preferences are created when they are defined using sticky_pref(). These preferences act as default preferences but whenever a value is created for the preference, that value is always written even when it matches the default. Sticky preferences are generally used for preferences that have a different default value in different channels with the intent being that once the user sets the preference in one channel, the preference will remain with that value when using a different channel with different defaults. For example, let's assume that Nightly has a preference "some.preference" which defaults to true while DeveloperEdition defaults the same preference to false and the user desires the preference to have the value true in both channels. If the preference is not a sticky preference and the user runs DeveloperEdition and flips the pref to true it will be saved as it is not the default. When the user then runs Nightly, the preference now has the same value as the default, so is not written by Nightly. When the user then runs DeveloperEdition again, the preference value will be false as no user preference was written by Nightly. If the preference is defined as a sticky preference, the value true will be written by Nightly even though it matches the current default, so when DeveloperEdition is run the preference keeps the desired value of true.

So I don't think it would be useful in the context of this user.js
