### ISSUE TITLE
Extensions don't show up

### ISSUE THREAD

**Issue by alx-alexpark** [pyllyukko/user.js#535]
Hey, just installed user.js in a **fresh profile**. and my extensions don't show up (yes I installed them in the new profile). I opened "customize toolbar" and it doesn't show up there either.

![Screenshot from 2022-02-05 09-32-30](https://user-images.githubusercontent.com/63802868/152648184-35e2cd98-8f22-4fe5-a96a-8fef04ac1431.png)
![Screenshot from 2022-02-05 09-33-51](https://user-images.githubusercontent.com/63802868/152648237-f3fbfa52-e9e8-484e-9741-b27f60f56029.png)
![Screenshot from 2022-02-05 09-33-28](https://user-images.githubusercontent.com/63802868/152648241-540b2921-ee66-4721-96c2-31bbfde51067.png)

**Comment by callmesia** [comment]
check Always use private browsing mode if its on then extensions should be allowed to run in private windows

**Comment by pyllyukko** [comment]
Is this still happening?

**Comment by gierdummy** [comment]
add extension with "Allow this extension to run in private windows" tick

**Comment by pyllyukko** [comment]
The recommendations above should fix this. Re-open the issue if the problem persists.
