### ISSUE TITLE
How to restore urlbar behaviour?

### ISSUE THREAD

**Issue by Bohmthedudevulture** [pyllyukko/user.js#536]
I am customizing my relaxed user.js and I would like to know how I could make that the urlbar give me to search in my preset search engine when I don't give a proper url.

**Comment by nodiscc** [comment]
https://github.com/pyllyukko/user.js/blob/master/user.js#L241

``js
// PREF: Do not submit invalid URIs entered in the address bar to the default search engine
// http://kb.mozillazine.org/Keyword.enabled
user_pref("keyword.enabled",					false);
```
