### ISSUE TITLE
Recommendation to support uBlock Origin "Back up to file"?

### ISSUE THREAD

**Issue by garrygosafe** [pyllyukko/user.js#541]
Hello, I am looking to locate the backup file on Chrome on a Mac, to create a bash script to pull the file. 
Would you be able to help with the location of the file please? I recently came across https://github.com/pyllyukko/user.js/issues/330 which discussed this with Firefox but I wasn't able to locate these files on a Mac. 
Many Thanks

**Comment by pyllyukko** [comment]
Hi.

I don't own a Mac so I could check this out. Maybe you should ask this in <https://github.com/gorhill/uBlock>. Closing this, as it doesn't relate to this project.
