### ISSUE TITLE
set `browser.sessionstore.max_tabs_undo = 0`

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#549]
While reviewing https://wiki.mozilla.org/Privacy/Privacy_Task_Force/firefox_about_config_privacy_tweeks, I found this pref which is currently not set in `user.js`

` browser.sessionstore.max_tabs_undo = 0`

> Even with Firefox set to not remember history, your closed tabs are stored temporarily at Menu -> History -> Recently Closed Tabs.

**Comment by pyllyukko** [comment]
Let's add this. Want to make a PR?

**Comment by nodiscc** [comment]
Sure, putting this on my list of things to do, expect a PR sometime soon.

**Comment by pyllyukko** [comment]
> Sure, putting this on my list of things to do, expect a PR sometime soon.

Awesome. Thanks!
