### ISSUE TITLE
set `network.http.referer.trimmingPolicy = 2`/`network.http.referer.XOriginTrimmingPolicy = 2`

### ISSUE THREAD

**Issue by nodiscc** [pyllyukko/user.js#550]
While reviewing https://wiki.mozilla.org/Privacy/Privacy_Task_Force/firefox_about_config_privacy_tweeks, I found these prefs which are currently not set in `user.js`

` network.http.referer.trimmingPolicy = 2`

> Send only the scheme, host, and port in the Referer header

       0 = Send the full URL in the Referer header
       1 = Send the URL without its query string in the Referer header
       2 = Send only the scheme, host, and port in the Referer header

` network.http.referer.XOriginTrimmingPolicy = 2`

> When sending Referer across origins, only send scheme, host, and port in the Referer header of cross-origin requests. Source

       0 = Send full url in Referer
       1 = Send url without query string in Referer
       2 = Only send scheme, host, and port in Referer
 

There is a comment in user.js about this pref:

```
TODO: https://github.com/pyllyukko/user.js/issues/94, commented-out XOriginPolicy/XOriginTrimmingPolicy = 2 prefs
```

This and #549 should cover all settings detailed on the mozilla wiki page.

**Comment by pyllyukko** [comment]
Sounds like something we want to add. Want to make a PR for this?

**Comment by nodiscc** [comment]
Sure, putting this on my list of things to do, expect a PR sometime soon.
