### ISSUE TITLE
Profile sync daemon and directory traversing for user.js not working

### ISSUE THREAD

**Issue by j0inty** [pyllyukko/user.js#557]
The README.md has a problem in [Update using git](https://github.com/pyllyukko/user.js/?tab=readme-ov-file#updating-using-git) Section. It mention a symlink with directory traversing, but this does not work when the profile is stored in a **tmpfs**. 

You need to create this symlink with the full path.

`user@host:~/.mozilla/firefox$ ln -s $HOME/.mozilla/firefox/user.js/user.js user.js`

Best regards

**Comment by pyllyukko** [comment]
Thanks!
