### ISSUE TITLE
Let's Encrypt (can we add it?) - yes we can! 

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#60]
[This project](https://letsencrypt.org/) is a big step forward for mass encryption on the net.

* https://letsencrypt.org/2015/10/19/lets-encrypt-is-trusted.html
* https://letsencrypt.org/certificates/
* https://github.com/letsencrypt/acme-spec

On Nov. 16 this will also hit Chrome, Firefox, all other browsers and you just need to be installed on it. With next releases they maybe get also integrated automatically. All for free. :+1:

**Comment by pyllyukko** [comment]
The Let's Encrypt project indeed seems quite promising. I guess there are no specific actions required regarding user.js other than add it to ```cas.sh```.

**Comment by CHEF-KOCH** [comment]
Yep, can you maybe add it or should I do this via PR? The Project author said to be he already opened several threads for all Browsers to get Support out-of-the-box. So we only may need to add this and can enjoy free encrypted web.

**Comment by fmarier** [comment]
As long as IdenTrust is trusted, then Let's Encrypt should just work: https://letsencrypt.org/2015/10/19/lets-encrypt-is-trusted.html

**Comment by CHEF-KOCH** [comment]
Why you re-post my link?

**Comment by pyllyukko** [comment]
It seems that "DST Root CA X3" is the root CA we need to trust.

**Comment by CHEF-KOCH** [comment]
Do it ! :laughing:
