### ISSUE TITLE
changes to trackingprotection and safebrowsing

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [pyllyukko/user.js#62]
for those who are interested (i noticed a TODO in user.js), i came across these and it seems like these 2 features might be merging or just adding new preferences in firefox 43 (user.js is also missing some of the older preferences such as privacy.trackingprotection.pbmode.enabled (just for the sake of it)) 

https://wiki.mozilla.org/Safe_Browsing
https://wiki.mozilla.org/Security/Tracking_protection

i personally disable both features so im not sure what the best course of action would be for user.js

if this brings nothing to the table close the issue i guess

**Comment by fmarier** [comment]
`privacy.trackingprotection.pbmode.enabled` is not necessary if you turn on tracking protection globally via `privacy.trackingprotection.enabled`.

**Comment by pyllyukko** [comment]
@fmarier: Thanks for the clarification and update.
