### ISSUE TITLE
blog: can we be tracked via mozilla's addon blocklist updates? [PARANOID MODE]

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [pyllyukko/user.js#74]
i just want to see what people think about this lol. its not me asking for anything to be put in user.js. i had uMatrix's behind-the-scene logger open and then firefox tried to update its addon blocklist. this was the url: `https://blocklist.addons.mozilla.org/blocklist/3/%7Bec8030f7-c20a-464f-9b0e-13a3a9e97384%7D/41.0.2/Firefox/20151014143721/WINNT_x86-msvc/en-US/release/Windows_NT%206.1/default/default/7/528/1/`. so i checked `about:config` and i saw that `extensions.blocklist.url = https://blocklist.addons.mozilla.org/blocklist/3/%APP_ID%/%APP_VERSION%/%PRODUCT%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/%PING_COUNT%/%TOTAL_PING_COUNT%/%DAYS_SINCE_LAST_PING%/`
this is the only update url in `about:config` that i can see which sends so many items in the url. i wondered if it really needed all that information. so i requested `https://blocklist.addons.mozilla.org/blocklist/3/%20/%20/%20/%20/%20/%20/%20/%20/%20/%20/%20/%20/%20/` and i got exactly the same results in return. as long as the right amount of values are in the url it gives the same blocklist. it doesnt matter what the values are. im guessing its just to build statistics or something?

then i thought about spoofing some of the values but then i realised that it wasnt worth it. but the ping values interested me. 
`%TOTAL_PING_COUNT%` seems to be the total amount of times my browser has updated its blocklist ever and it is stored in about:config as `extensions.blocklist.pingCountTotal`
`%PING_COUNT%` is the amount of times my browser has updated the blocklist on this browser version and the value is stored at `extensions.blocklist.pingCountVersion`
`%DAYS_SINCE_LAST_PING%` is what it sounds like and if u use ur browser everyday it will be `1` since the default blocklist update interval `extensions.blocklist.interval` is set to 24 hours

im definitely not claiming mozilla is tracking users through this lol, but maybe some people can see how it could be used that way. not only does the server recieve every day (if you are online everyday) your OS, browser version etc etc., it has unique numbers of how many times the url has been accessed and how long ago which greatly improve its ability to point back to you. remember its all probably linked back to your ip address too. what can they tell from it? probably not much lol. that you were online? you used your browser today?

if that bothers someone they could make user.js reset `extensions.blocklist.pingCountTotal` and `extensions.blocklist.pingCountVersion` or they could modify `extensions.blocklist.url` to always send a value like `1` or something else for the ping counts. though that would make you more trackable unless your ip changed a lot. the best thing would be to randomize the values, but that would require an extension probably and who cares enough to make that?

by the time i finished writing this my conviction that these are things we shouldnt mess with has only grown stronger. thanks for reading i dont know why i wrote this

**Comment by CHEF-KOCH** [comment]
>  im guessing its just to build statistics or something?

From what I know Mozilla not collect data which 'track' people speaking of fingerprinting/re-locating them. So, basic 'fingerprints' like OS version, Browser version and such are sent back. This is for statistics and to overall help if it really crashes (in bug report is enabled).


> but the ping values interested me.

The ping stuff is for e.g. the 'hello' chat to sent besides the TTL a request if you are away or not. The other ping is as you said for [blacklist](extensions.blocklist.pingCountTotal) reasons.


The main question is not if they collect it, the question is if they sell such statistics and what they do with it.

**Comment by berrythesoftwarecodeprogrammar** [comment]
thats true :)

**Comment by nodiscc** [comment]
No info/actionable items relevant to `user.js` have been mentioned. I think this can be closed.
