### ISSUE TITLE
include a method for users to easily include custom entries / override this user.js

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [pyllyukko/user.js#75]
didnt know how to word title properly.

info here  https://github.com/pyllyukko/user.js/pull/54
one may want to use this user.js but have a few things in it which they want configured differently. appending to the end of the file overrides previous entries but apparently that breaks git stuff

i just came across this http://kb.mozillazine.org/Locking_preferences
havent tried it yet but it if a file of lockprefs can override user.js then this might be a solution? people would just need to add their preferences as lockprefs in the lockprefs file. but i just realised, if it reads these files in a particular order, it may be possible to just put regular user_pref's in one of these files

will test

**Comment by mengele-chan** [comment]
One possible solution is to add `override.js` and `myuser.js` to `.gitignore`. Then one can simply `git pull && cat user.js override.js > myuser.js`, no?

**Comment by nodiscc** [comment]
@mengele-chan it would be a decent solution **if** it is confirmed that entries at the end of the file actually override entries above.

**Comment by mengele-chan** [comment]
https://github.com/pyllyukko/user.js/pull/54#issuecomment-147024370

**Comment by berrythesoftwarecodeprogrammar** [comment]
@pyllyukko ive found a solution, so you can close this if you want. maybe add some information about it to the readme for curious users?

this article has all the information: [http://kb.mozillazine.org/Locking_preferences](http://kb.mozillazine.org/Locking_preferences)

one has to create a `local-settings.js` file in their `%APP%\defaults\pref` folder. `%APP%` being the folder where the firefox or thunderbird executable resides (on windows). mine is `D:\Program Files (x86)\Mozilla Thunderbird\defaults\pref\`. the contents should be:
```
pref("general.config.obscure_value", 0);
pref("general.config.filename", "mozilla.cfg");
```

and then a `mozilla.cfg` file needs to be created in the same directory as the `.exe` e.g. `D:\Program Files (x86)\Mozilla Thunderbird\` where entries can be added to override `user.js`. they can either be normal preferences (which override), or they can be locked preferences which no addon or anything can change once the application starts. e.g:
```
lockPref("gfx.downloadable_fonts.enabled",true); // a locked preference
pref("permissions.default.image",1); // a normal preference
```

**Comment by pyllyukko** [comment]
Cool, thanks. I added a note to the README.
