### ISSUE TITLE
Breakage with FF35

### ISSUE THREAD

**Issue by dewbasaur** [pyllyukko/user.js#8]
With Firefox 34 and before, this user.js and my builds of the Firefox port of uBlock work perfectly fine together.

With Firefox 35, uBlock still works perfectly on its own - tested with new profiles - but using this user.js causes it to break:

https://gist.github.com/dewbasaur/8ddff1830856369db97f

**Comment by pyllyukko** [comment]
Interesting. No idea what that could be about. I'll look into that.

**Comment by pyllyukko** [comment]
Could you pull and try again? I re-enabled [IndexedDB](https://developer.mozilla.org/en-US/docs/IndexedDB) (ce5ba079ff69fc57cf990e8fda20bab8d71f66d7), which should fix this.

**Comment by dewbasaur** [comment]
That seems to be it. The ERROR became a WARN and it works as expected now, thanks.
