### ISSUE TITLE
Implement (some) JavaScript syntax checking as continuous integration

### ISSUE THREAD

**Issue by pyllyukko** [pyllyukko/user.js#83]
We need to try to avoid simple JavaScript syntax bugs and I think it should be possible by hooking the project to some continuous integration service.

Some of [these](https://github.com/integrations/feature/build)?

Any recommendations?

**Comment by CHEF-KOCH** [comment]
Hey, that is a nice idea. 

No sorry, I only worked with [travis](https://github.com/integrations/travis-ci) until now so I can't suggest any others plugins. I think it doesn't matter which one as long it respect regular expressions which will catch certain matches. From what I know [travis also supports javascript](http://docs.travis-ci.com/user/language-specific/) but don't ask me how to setup it to get the JavaScript validator working, I think we need then a bit investigating into the readme.

**Comment by pyllyukko** [comment]
I'm now testing this with Travis in [this branch](https://github.com/pyllyukko/user.js/tree/travis-ci). So far so good. I'm using [Acorn](https://github.com/ternjs/acorn) for the syntax checking.

**Comment by pyllyukko** [comment]
And now it's merged.
