### ISSUE TITLE
browser.pagethumbnails.capturing_disabled

### ISSUE THREAD

**Issue by SINE** [pyllyukko/user.js#87]
You have set
 user_pref("browser.pagethumbnails.capturing_disabled",		false); 

This means the feature is active.
Mozillas wiki page regarding that setting is contradictory, quote:
> Default value: true

>Values
>false (default)
>    The application creates screenshots of visited web pages.
>true
>    The application doesn't create screenshots of visited web pages. 

Given the name of the setting it must be assumed that setting it to **true means** the feature is **turned off**.

**Comment by kaihendry** [comment]
I hate these contradictory `_disabled` preferences. Wonder if it's worth filing a bug on Mozilla about that horrible practice.

**Comment by pyllyukko** [comment]
Thanks for spotting this.
