### ISSUE TITLE
Firefox’s Tracking Protection feature gets a boost soon which makes a lot of stuff obsolete 

### ISSUE THREAD

**Issue by CHEF-KOCH** [pyllyukko/user.js#89]
Firefox gets very soon a massive 'privacy' boost, you maybe know or not but  [Mozilla not need Google anymore](http://thenextweb.com/insider/2015/11/26/mozilla-says-it-will-thrive-without-googles-money/), which is pretty good, not that I have any problem with Google in this case but it's (for me) a big step forward. 

So, the real important news are the coming [improvements](http://www.ghacks.net/2015/11/30/firefoxs-tracking-protection-feature-gets-a-boost-soon/) which means that several stuff gets obsolete. 

![unbenannt](https://cloud.githubusercontent.com/assets/727123/11818138/fe941880-a358-11e5-811a-49d2816940c6.png)
- Ghostery 
- uBlock with several tracker lists (not the entire addon [yet?])
- Google's own list but will be still used by default from Mozilla
- (maybe) in the future no adblockers anymore (implemented, that would be an goal?) 

So I will track, if someone already found several switches let me know.

**Comment by CHEF-KOCH** [comment]
In private mode there are no fingerprints anymore, if you close the Browser everything gets wiped and this without any addons/tools out of the box. 

The internal blocklist (the strong one) fully replaces ghostery's list and blocks most known trackers.

**Comment by pyllyukko** [comment]
What fingerprints are you referring to?

**Comment by CHEF-KOCH** [comment]
I was talking about every fingerprinting mechanism because e.g. the new panopticlick version shows information which more plays with the fears of people instant that it shows something to avoid it. E.g. the screen size doesn't matter, there is no attack on earth that is relevant for this, it only plays a role if you e.g. on Amazon and compare the prices on Mobile <-> Desktop and you mostly see the prices are a bit different on Mobile version (don't know if that is fixed on Amazon, I complained and tested this 2 years ago) but it have nothing to do with fingerprinting. It's a technique which is necessary same like cookies, the question is if that is really then always attachable and how many effort need the attacker.

As I already mentioned in other threads it's now more and more hype without anything just to say that everything is evil in fact most attacks working very different e.g. they using XSS to infect the login field instead of trying to hack cookies/screen size. It's more easier since even some banking pages suffering from XSS problems. 

I think if you fully hide everything you are more on the radar as leaving some stuff 'non unique'. I think we already solved all spying relevant things, the rest of this is just to give workarounds for broken or old protocol failures/problems. E.g. canvas, if you entirely disable it you break some legit pages which possible using it (same like webrtc .. webrtc is e.g. used for hello chat or whatsapp webchat [both without any security problems so far]). So if we entirely disable it, we lowering the 'surfing' fun and more running into troubles, I think the rest should be fixed by the protocols/Browser itself and we got now more and more protection mechanism. I tested FF now with strongest settings out of the box (FF 43 fresh installation) and e.g. eff showing me some garbage which says I'm not unique and have possible some 'security' problems, in fact everything is fine and I not need to change anything.

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH I will disagree with the statement "the new panopticlick version shows information which more plays with the fears of people instant that it shows something to avoid it. E.g. the screen size doesn't matter, there is no attack on earth that is relevant for this..."

I don't think you're understanding how bits of entropy work.  Anything that is not in common for all users adds to an identification profile.  Screen resolution is such an identifier.  By itself, not powerful.  In conjunction with other data, very useful.

I will agree with the statement "I think if you fully hide everything you are more on the radar as leaving some stuff 'non unique'.".  This is very true.  If you hide everything, you are in a set that is fairly small: only those that are hiding everything.  That probably eliminates 99% of possibilities as it is fairly unique in and of itself.

**Comment by CHEF-KOCH** [comment]
I think I get this correctly but I complain about showing infos which are totally irrelevant because it confused people as shown over [here](http://www.ghacks.net/2015/12/17/eff-launches-panopticlick-2-0-with-new-tracking-tests/). We get the same results and as an result of such thing other peoples asking how accurate this really is.

> Screen resolution is such an identifier. By itself, not powerful. In conjunction with other data, very useful.

Yes, I agree in this, but why you show it then? If it makes only sense if it comes with other stuff enabled (which is mostly fixed in Firefox) then why not hide if xyz is detected as disabled? 

Don't get me wrong but I think such pages same like IPleak are not very useful, it can quickly help but it should not be used to test your 'security' especially if the results can be different with each configuration or mis-configuratio or loading page problems.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@Gitoffthelawn Why not use CanvasBlocker and allow it to randomize the result instead of disabling it?

**Comment by Gitoffthelawn** [comment]
@L-a-n-g-o-l-i-e-r-s I'm not sure if you intended your comment for me or someone else.  Let me know, or you may want redirect your question to the intended person.

I'm not sure to which *result* you are referring.  If you are referring to the screen resolution, I'm not sure if CanvasBlocker can do anything about that.  Do you have information that indicates it can?

**Comment by nodiscc** [comment]
I think this can be closed. No actionable items can be found in this issue.
