### ISSUE TITLE
Spelling error in readme.md

### ISSUE THREAD

**Issue by Dyras** [pyllyukko/user.js#91]
Hi.
"Harden the browser, so it doesn't spill >it's< guts when asked (have you seen what BeEF can do?)"
it's should say its.

Great project by the way! Do you know of any similar Chrome projects?

**Comment by pyllyukko** [comment]
Thanks.

No, I'm not aware of anything similar regarding Chrome, but haven't really looked into it... as I am a dedicated Firefox user after all :)
