### ISSUE TITLE
about:networking

### ISSUE THREAD

**Issue by patwincky007** [pyllyukko/user.js#93]
Hello
Question [about:networking] -- How to disable the experimental real time recordings for Http [Hostnames] | Sockets [IP @] | DNS | WebSockets ???
Your solutions in "about:config" please for the privacy ...
Thanks for your precious help ...
Regards,

**Comment by pyllyukko** [comment]
I'm not entirely sure whether I understand your question. So you want for Firefox to "stop recording" the stuff you see on ```about:networking``` or what?

**Comment by patwincky007** [comment]
Hello 

Ya, I want to stop all the experimental recordings in real time I see on
about:networking ... despite with all your configuration settings in
about:config I changed. Is it possible ??? 

If yes, a solution please ... 

Regards, 

On 2015-12-29 06:43 PM, pyllyukko wrote: 

> I'm not entirely sure whether I understand your question. So you want for Firefox to "stop recording" the stuff you see on about:networking or what? 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/pyllyukko/user.js/issues/93#issuecomment-167841456

**Comment by pyllyukko** [comment]
> Ya, I want to stop all the experimental recordings in real time I see on about:networking ... despite with all your configuration settings in about:config I changed. Is it possible ??? If yes, a solution please ...

Is there some specific reason you want to do this? I mean... it's not like it's leaking that data outside (at least to my knowledge). What about [network monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor), which is a similar feature?

Honestly, I haven't even thought about how to prevent this, as I see no threat about being able to view your browser's network connections (by yourself). On the contrary, it is good that you're able to see where the browser is talking to.

Am I missing something here now? What's the threat that you're trying to protect yourself from with this?

**Comment by patwincky007** [comment]
Hello 

When I saw all the datas in real time, I immediatly thought about the
privacy ... Mozilla can collect the history datas ??? 

For you, it's just a simple browser's network monitor ... and I hope so.
I'm going to test with WireShark ... 

Thanks your sincere answer ... 

Bye 

On 2015-12-30 10:38 PM, pyllyukko wrote: 

>> Ya, I want to stop all the experimental recordings in real time I see on about:networking ... despite with all your configuration settings in about:config I changed. Is it possible ??? If yes, a solution please ...
> 
> Is there some specific reason you want to do this? I mean... it's not like it's leaking that data outside (at least to my knowledge). What about network monitor [1], which is a similar feature? 
> 
> Honestly, I haven't even thought about how to prevent this, as I see no threat about being able to view your browser's network connections (by yourself). On the contrary, it is good that you're able to see where the browser is talking to. 
> 
> Am I missing something here now? What's the threat that you're trying to protect yourself from with this? 
> 
> --
> Reply to this email directly or view it on GitHub [2].

 

Links:
------
[1] https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor
[2]
https://github.com/pyllyukko/user.js/issues/93#issuecomment-168078422

**Comment by nodiscc** [comment]
I don't think this feature reports anything. It's just a network monitor...

**Comment by CHEF-KOCH** [comment]
It's only listening to local interface and not connect to internet.

**Comment by patwincky007** [comment]
Hello 

Thanks a lot for your answer ... 

Bye 

On 2016-01-15 06:26 PM, CHEF-KOCH wrote: 

> It's only listening to local interface and not connect to internet. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/pyllyukko/user.js/issues/93#issuecomment-172024591

**Comment by Atavic** [comment]
There's something going here:

[https://bugzilla.mozilla.org/show_bug.cgi?id=1527256](socket process: make about:networking work)
[Get SocketData from socket process](https://phabricator.services.mozilla.com/D20354)
[Get DNSCacheEntries from socket process](https://phabricator.services.mozilla.com/D20355)

..like get Socket Data from the Dashboard **->** hostname + hostaddr
