### ISSUE TITLE
Can't search in Address/URL bar?

### ISSUE THREAD

**Issue by alabrand** [pyllyukko/user.js#97]
Seems like I can't search anymore in the Adress/URL bar. It only works with the dedicated search bar. The error I get is "Server not found". Any idea which setting I need to change in order to fix this?

**Comment by pyllyukko** [comment]
That would be [keyword.enabled](http://kb.mozillazine.org/Keyword.enabled).

**Comment by alabrand** [comment]
Thanks! I assume that is disabled because of privacy reasons, but it severely limits the usability in my case. I just can't get used to using the dedicated Search Bar.

**Comment by Gitoffthelawn** [comment]
How would that be a privacy issue?

**Comment by nodiscc** [comment]
I have also have re enabled this feature. The only case in which it would affect privacy is when a user mistypes an URL, that partially wrong URL would be sent to the default search engine (eg. typing `whate ver.com` with a space)

**Comment by pyllyukko** [comment]
> The only case in which it would affect privacy is when a user mistypes an URL, that partially wrong URL would be sent to the default search engine (eg. typing whate ver.com with a space)

And that is the exact reason. Happened to me more often than not. It is also documented in the [caveats](http://kb.mozillazine.org/Keyword.enabled#Caveats).

But you can learn to live with this. Just use the [Ctrl-K](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly?redirectlocale=en-US&redirectslug=Keyboard+shortcuts#w_search) keyboard shortcut. It took me a while to learn, but once you do, you don't miss the URL bar keyword search feature :)

**Comment by CHEF-KOCH** [comment]
In newer Firefox versions this option is obsolete since you get an [hint](https://bugzilla.mozilla.org/show_bug.cgi?id=1235065) with an small button next to it to + you can [individual configure it](https://support.mozilla.org/en-US/kb/settings-privacy-browsing-history-do-not-track) as long the clipboard events are disabled nothing else can be tracked for now. 

I suggest we remove it and let the user handle it.

**Comment by pyllyukko** [comment]
I can't find a setting in the GUI that would completely disable the "I don't know what to do with your request, so I'll just submit it to Google" feature regarding the location bar. So I think we should stick with it.

But those links provided one more setting to disable (just to be sure), which is the ```browser.urlbar.suggest.searches``` or "Show search suggestions in location bar results".

**Comment by CHEF-KOCH** [comment]
> I can't find a setting in the GUI that would completely disable the "I don't know what to do with your request, so I'll just submit it to Google" 

I not understand what you mean by that, but nothing will be sent except safebrowsing which checks: url, downloads and/or malware check. The only additional check which will be done via e.g. network.predictor.* +  network.http.speculative-parallel-limit which want for the future request dns-requests, handshakes and pre-connections but there is no known attack from what I know which compromise your security.

**Comment by pyllyukko** [comment]
I'm talking about the keyword feature, that will eventually fallback to submitting your (invalid URL) from the location bar to a search engine.

**Comment by CHEF-KOCH** [comment]
Okay thanks for clarification, from what I know we using duckduckgo which not collects any metadata. The entire process is explained [over here](https://wiki.mozilla.org/Firefox/URL_Bar_Algorithm) including the algorithm. As I said besides DNS and the other stuff nothing will be collected which 'harm' your privacy.

**Comment by berrythesoftwarecodeprogrammar** [comment]
u can also do something like this:
![keywords](https://cloud.githubusercontent.com/assets/6548571/12369701/9f66a83a-bc50-11e5-83e0-d74cf8848b93.png)

make bookmarks with a %s in them and attach a keyword. e.g. for google search:
https://encrypted.google.com/search?ie=UTF-8&safe=off&pws=0&complete=0&as_qdr=all&site=webhp&q=%s
and i made my keyword `g'

so in the urlbar i just type "g something" and it searches google for "something"

**Comment by collinbarrett** [comment]
I am having trouble re-enabling the ability to search from the location bar. I set the following in my `mozilla.cfg` file for global settings, but I still get "The address isn't valid" when attempting a keyword search from the location bar. I understand the privacy risks and am willing to make the tradeoff for ease-of -use. Thanks!

```lockPref("keyword.enabled",					true);```
