### ISSUE TITLE
love this. can't use twitch though

### ISSUE THREAD

**Issue by lackofbettername** [pyllyukko/user.js#98]
thanks!

**Comment by pyllyukko** [comment]
Thanks. Why doesn't [Twitch](http://www.twitch.tv/) work? It uses Flash, so you might need to temporarily allow it from the plugins settings.

**Comment by lackofbettername** [comment]
got it to work. thanks!

**Comment by pyllyukko** [comment]
> got it to work. thanks!

Glad to hear that!
